// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	core "gochat/internal/gateway/core"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionIDGenerator is a mock of SessionIDGenerator interface.
type MockSessionIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionIDGeneratorMockRecorder
	isgomock struct{}
}

// MockSessionIDGeneratorMockRecorder is the mock recorder for MockSessionIDGenerator.
type MockSessionIDGeneratorMockRecorder struct {
	mock *MockSessionIDGenerator
}

// NewMockSessionIDGenerator creates a new mock instance.
func NewMockSessionIDGenerator(ctrl *gomock.Controller) *MockSessionIDGenerator {
	mock := &MockSessionIDGenerator{ctrl: ctrl}
	mock.recorder = &MockSessionIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionIDGenerator) EXPECT() *MockSessionIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockSessionIDGenerator) Generate() core.SessionID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(core.SessionID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockSessionIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSessionIDGenerator)(nil).Generate))
}
