// Code generated by MockGen. DO NOT EDIT.
// Source: friendship_repository.go
//
// Generated by this command:
//
//	mockgen -source=friendship_repository.go -destination=./mocks/mock_friendship_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFriendshipRepository is a mock of FriendshipRepository interface.
type MockFriendshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipRepositoryMockRecorder
	isgomock struct{}
}

// MockFriendshipRepositoryMockRecorder is the mock recorder for MockFriendshipRepository.
type MockFriendshipRepositoryMockRecorder struct {
	mock *MockFriendshipRepository
}

// NewMockFriendshipRepository creates a new mock instance.
func NewMockFriendshipRepository(ctrl *gomock.Controller) *MockFriendshipRepository {
	mock := &MockFriendshipRepository{ctrl: ctrl}
	mock.recorder = &MockFriendshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipRepository) EXPECT() *MockFriendshipRepositoryMockRecorder {
	return m.recorder
}

// ExistByUserID mocks base method.
func (m *MockFriendshipRepository) ExistByUserID(ctx context.Context, userID1, userID2 kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserID", ctx, userID1, userID2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserID indicates an expected call of ExistByUserID.
func (mr *MockFriendshipRepositoryMockRecorder) ExistByUserID(ctx, userID1, userID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserID", reflect.TypeOf((*MockFriendshipRepository)(nil).ExistByUserID), ctx, userID1, userID2)
}

// Save mocks base method.
func (m *MockFriendshipRepository) Save(ctx context.Context, friendship *domain.Friendship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, friendship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFriendshipRepositoryMockRecorder) Save(ctx, friendship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFriendshipRepository)(nil).Save), ctx, friendship)
}

// MockFriendshipSaver is a mock of FriendshipSaver interface.
type MockFriendshipSaver struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipSaverMockRecorder
	isgomock struct{}
}

// MockFriendshipSaverMockRecorder is the mock recorder for MockFriendshipSaver.
type MockFriendshipSaverMockRecorder struct {
	mock *MockFriendshipSaver
}

// NewMockFriendshipSaver creates a new mock instance.
func NewMockFriendshipSaver(ctrl *gomock.Controller) *MockFriendshipSaver {
	mock := &MockFriendshipSaver{ctrl: ctrl}
	mock.recorder = &MockFriendshipSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipSaver) EXPECT() *MockFriendshipSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockFriendshipSaver) Save(ctx context.Context, friendship *domain.Friendship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, friendship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFriendshipSaverMockRecorder) Save(ctx, friendship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFriendshipSaver)(nil).Save), ctx, friendship)
}

// MockFriendshipExisterByUserID is a mock of FriendshipExisterByUserID interface.
type MockFriendshipExisterByUserID struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipExisterByUserIDMockRecorder
	isgomock struct{}
}

// MockFriendshipExisterByUserIDMockRecorder is the mock recorder for MockFriendshipExisterByUserID.
type MockFriendshipExisterByUserIDMockRecorder struct {
	mock *MockFriendshipExisterByUserID
}

// NewMockFriendshipExisterByUserID creates a new mock instance.
func NewMockFriendshipExisterByUserID(ctrl *gomock.Controller) *MockFriendshipExisterByUserID {
	mock := &MockFriendshipExisterByUserID{ctrl: ctrl}
	mock.recorder = &MockFriendshipExisterByUserIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipExisterByUserID) EXPECT() *MockFriendshipExisterByUserIDMockRecorder {
	return m.recorder
}

// ExistByUserID mocks base method.
func (m *MockFriendshipExisterByUserID) ExistByUserID(ctx context.Context, userID1, userID2 kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserID", ctx, userID1, userID2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserID indicates an expected call of ExistByUserID.
func (mr *MockFriendshipExisterByUserIDMockRecorder) ExistByUserID(ctx, userID1, userID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserID", reflect.TypeOf((*MockFriendshipExisterByUserID)(nil).ExistByUserID), ctx, userID1, userID2)
}
