// Code generated by MockGen. DO NOT EDIT.
// Source: roomship_repository.go
//
// Generated by this command:
//
//	mockgen -source=roomship_repository.go -destination=./mocks/mock_roomship_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomshipRepository is a mock of RoomshipRepository interface.
type MockRoomshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomshipRepositoryMockRecorder is the mock recorder for MockRoomshipRepository.
type MockRoomshipRepositoryMockRecorder struct {
	mock *MockRoomshipRepository
}

// NewMockRoomshipRepository creates a new mock instance.
func NewMockRoomshipRepository(ctrl *gomock.Controller) *MockRoomshipRepository {
	mock := &MockRoomshipRepository{ctrl: ctrl}
	mock.recorder = &MockRoomshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipRepository) EXPECT() *MockRoomshipRepositoryMockRecorder {
	return m.recorder
}

// ExistByUserIDAndRoomID mocks base method.
func (m *MockRoomshipRepository) ExistByUserIDAndRoomID(ctx context.Context, roomID kernel.RoomID, userID kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomID", ctx, roomID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomID indicates an expected call of ExistByUserIDAndRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) ExistByUserIDAndRoomID(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).ExistByUserIDAndRoomID), ctx, roomID, userID)
}

// FindsByRoomID mocks base method.
func (m *MockRoomshipRepository) FindsByRoomID(ctx context.Context, id kernel.RoomID) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomID", ctx, id)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomID indicates an expected call of FindsByRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) FindsByRoomID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindsByRoomID), ctx, id)
}

// Save mocks base method.
func (m *MockRoomshipRepository) Save(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomshipRepositoryMockRecorder) Save(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomshipRepository)(nil).Save), ctx, roomship)
}

// MockRoomshipSaver is a mock of RoomshipSaver interface.
type MockRoomshipSaver struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipSaverMockRecorder
	isgomock struct{}
}

// MockRoomshipSaverMockRecorder is the mock recorder for MockRoomshipSaver.
type MockRoomshipSaverMockRecorder struct {
	mock *MockRoomshipSaver
}

// NewMockRoomshipSaver creates a new mock instance.
func NewMockRoomshipSaver(ctrl *gomock.Controller) *MockRoomshipSaver {
	mock := &MockRoomshipSaver{ctrl: ctrl}
	mock.recorder = &MockRoomshipSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipSaver) EXPECT() *MockRoomshipSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRoomshipSaver) Save(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomshipSaverMockRecorder) Save(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomshipSaver)(nil).Save), ctx, roomship)
}

// MockRoomshipExisterByUserIDAndRoomID is a mock of RoomshipExisterByUserIDAndRoomID interface.
type MockRoomshipExisterByUserIDAndRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipExisterByUserIDAndRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipExisterByUserIDAndRoomIDMockRecorder is the mock recorder for MockRoomshipExisterByUserIDAndRoomID.
type MockRoomshipExisterByUserIDAndRoomIDMockRecorder struct {
	mock *MockRoomshipExisterByUserIDAndRoomID
}

// NewMockRoomshipExisterByUserIDAndRoomID creates a new mock instance.
func NewMockRoomshipExisterByUserIDAndRoomID(ctrl *gomock.Controller) *MockRoomshipExisterByUserIDAndRoomID {
	mock := &MockRoomshipExisterByUserIDAndRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipExisterByUserIDAndRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipExisterByUserIDAndRoomID) EXPECT() *MockRoomshipExisterByUserIDAndRoomIDMockRecorder {
	return m.recorder
}

// ExistByUserIDAndRoomID mocks base method.
func (m *MockRoomshipExisterByUserIDAndRoomID) ExistByUserIDAndRoomID(ctx context.Context, roomID kernel.RoomID, userID kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomID", ctx, roomID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomID indicates an expected call of ExistByUserIDAndRoomID.
func (mr *MockRoomshipExisterByUserIDAndRoomIDMockRecorder) ExistByUserIDAndRoomID(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipExisterByUserIDAndRoomID)(nil).ExistByUserIDAndRoomID), ctx, roomID, userID)
}

// MockRoomshipsFinderByRoomID is a mock of RoomshipsFinderByRoomID interface.
type MockRoomshipsFinderByRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipsFinderByRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipsFinderByRoomIDMockRecorder is the mock recorder for MockRoomshipsFinderByRoomID.
type MockRoomshipsFinderByRoomIDMockRecorder struct {
	mock *MockRoomshipsFinderByRoomID
}

// NewMockRoomshipsFinderByRoomID creates a new mock instance.
func NewMockRoomshipsFinderByRoomID(ctrl *gomock.Controller) *MockRoomshipsFinderByRoomID {
	mock := &MockRoomshipsFinderByRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipsFinderByRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipsFinderByRoomID) EXPECT() *MockRoomshipsFinderByRoomIDMockRecorder {
	return m.recorder
}

// FindsByRoomID mocks base method.
func (m *MockRoomshipsFinderByRoomID) FindsByRoomID(ctx context.Context, id kernel.RoomID) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomID", ctx, id)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomID indicates an expected call of FindsByRoomID.
func (mr *MockRoomshipsFinderByRoomIDMockRecorder) FindsByRoomID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomID", reflect.TypeOf((*MockRoomshipsFinderByRoomID)(nil).FindsByRoomID), ctx, id)
}
