// Code generated by MockGen. DO NOT EDIT.
// Source: room_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=room_message_repository.go -destination=./mocks/mock_room_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomMessageRepository is a mock of RoomMessageRepository interface.
type MockRoomMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomMessageRepositoryMockRecorder is the mock recorder for MockRoomMessageRepository.
type MockRoomMessageRepositoryMockRecorder struct {
	mock *MockRoomMessageRepository
}

// NewMockRoomMessageRepository creates a new mock instance.
func NewMockRoomMessageRepository(ctrl *gomock.Controller) *MockRoomMessageRepository {
	mock := &MockRoomMessageRepository{ctrl: ctrl}
	mock.recorder = &MockRoomMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageRepository) EXPECT() *MockRoomMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomMessageRepository) Create(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomMessageRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomMessageRepository)(nil).Create), ctx, message)
}

// FindRoomMessage mocks base method.
func (m *MockRoomMessageRepository) FindRoomMessage(ctx context.Context, messageID kernel.MessageID) (*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessage indicates an expected call of FindRoomMessage.
func (mr *MockRoomMessageRepositoryMockRecorder) FindRoomMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessage", reflect.TypeOf((*MockRoomMessageRepository)(nil).FindRoomMessage), ctx, messageID)
}

// FindRoomMessagesByRecipientIDAndState mocks base method.
func (m *MockRoomMessageRepository) FindRoomMessagesByRecipientIDAndState(ctx context.Context, recipientID kernel.UserID, state domain.MessageState, limit int) ([]*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessagesByRecipientIDAndState", ctx, recipientID, state, limit)
	ret0, _ := ret[0].([]*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessagesByRecipientIDAndState indicates an expected call of FindRoomMessagesByRecipientIDAndState.
func (mr *MockRoomMessageRepositoryMockRecorder) FindRoomMessagesByRecipientIDAndState(ctx, recipientID, state, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessagesByRecipientIDAndState", reflect.TypeOf((*MockRoomMessageRepository)(nil).FindRoomMessagesByRecipientIDAndState), ctx, recipientID, state, limit)
}

// Updates mocks base method.
func (m *MockRoomMessageRepository) Updates(ctx context.Context, messages []*domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockRoomMessageRepositoryMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockRoomMessageRepository)(nil).Updates), ctx, messages)
}

// MockRoomMessageCreator is a mock of RoomMessageCreator interface.
type MockRoomMessageCreator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageCreatorMockRecorder
	isgomock struct{}
}

// MockRoomMessageCreatorMockRecorder is the mock recorder for MockRoomMessageCreator.
type MockRoomMessageCreatorMockRecorder struct {
	mock *MockRoomMessageCreator
}

// NewMockRoomMessageCreator creates a new mock instance.
func NewMockRoomMessageCreator(ctrl *gomock.Controller) *MockRoomMessageCreator {
	mock := &MockRoomMessageCreator{ctrl: ctrl}
	mock.recorder = &MockRoomMessageCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageCreator) EXPECT() *MockRoomMessageCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomMessageCreator) Create(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomMessageCreatorMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomMessageCreator)(nil).Create), ctx, message)
}

// MockRoomMessagesUpdater is a mock of RoomMessagesUpdater interface.
type MockRoomMessagesUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessagesUpdaterMockRecorder
	isgomock struct{}
}

// MockRoomMessagesUpdaterMockRecorder is the mock recorder for MockRoomMessagesUpdater.
type MockRoomMessagesUpdaterMockRecorder struct {
	mock *MockRoomMessagesUpdater
}

// NewMockRoomMessagesUpdater creates a new mock instance.
func NewMockRoomMessagesUpdater(ctrl *gomock.Controller) *MockRoomMessagesUpdater {
	mock := &MockRoomMessagesUpdater{ctrl: ctrl}
	mock.recorder = &MockRoomMessagesUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessagesUpdater) EXPECT() *MockRoomMessagesUpdaterMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockRoomMessagesUpdater) Updates(ctx context.Context, messages []*domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockRoomMessagesUpdaterMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockRoomMessagesUpdater)(nil).Updates), ctx, messages)
}

// MockRoomMessageFinder is a mock of RoomMessageFinder interface.
type MockRoomMessageFinder struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageFinderMockRecorder
	isgomock struct{}
}

// MockRoomMessageFinderMockRecorder is the mock recorder for MockRoomMessageFinder.
type MockRoomMessageFinderMockRecorder struct {
	mock *MockRoomMessageFinder
}

// NewMockRoomMessageFinder creates a new mock instance.
func NewMockRoomMessageFinder(ctrl *gomock.Controller) *MockRoomMessageFinder {
	mock := &MockRoomMessageFinder{ctrl: ctrl}
	mock.recorder = &MockRoomMessageFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageFinder) EXPECT() *MockRoomMessageFinderMockRecorder {
	return m.recorder
}

// FindRoomMessage mocks base method.
func (m *MockRoomMessageFinder) FindRoomMessage(ctx context.Context, messageID kernel.MessageID) (*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessage indicates an expected call of FindRoomMessage.
func (mr *MockRoomMessageFinderMockRecorder) FindRoomMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessage", reflect.TypeOf((*MockRoomMessageFinder)(nil).FindRoomMessage), ctx, messageID)
}

// MockRoomMessagesFinderByRecipientIDAndState is a mock of RoomMessagesFinderByRecipientIDAndState interface.
type MockRoomMessagesFinderByRecipientIDAndState struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessagesFinderByRecipientIDAndStateMockRecorder
	isgomock struct{}
}

// MockRoomMessagesFinderByRecipientIDAndStateMockRecorder is the mock recorder for MockRoomMessagesFinderByRecipientIDAndState.
type MockRoomMessagesFinderByRecipientIDAndStateMockRecorder struct {
	mock *MockRoomMessagesFinderByRecipientIDAndState
}

// NewMockRoomMessagesFinderByRecipientIDAndState creates a new mock instance.
func NewMockRoomMessagesFinderByRecipientIDAndState(ctrl *gomock.Controller) *MockRoomMessagesFinderByRecipientIDAndState {
	mock := &MockRoomMessagesFinderByRecipientIDAndState{ctrl: ctrl}
	mock.recorder = &MockRoomMessagesFinderByRecipientIDAndStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessagesFinderByRecipientIDAndState) EXPECT() *MockRoomMessagesFinderByRecipientIDAndStateMockRecorder {
	return m.recorder
}

// FindRoomMessagesByRecipientIDAndState mocks base method.
func (m *MockRoomMessagesFinderByRecipientIDAndState) FindRoomMessagesByRecipientIDAndState(ctx context.Context, recipientID kernel.UserID, state domain.MessageState, limit int) ([]*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessagesByRecipientIDAndState", ctx, recipientID, state, limit)
	ret0, _ := ret[0].([]*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessagesByRecipientIDAndState indicates an expected call of FindRoomMessagesByRecipientIDAndState.
func (mr *MockRoomMessagesFinderByRecipientIDAndStateMockRecorder) FindRoomMessagesByRecipientIDAndState(ctx, recipientID, state, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessagesByRecipientIDAndState", reflect.TypeOf((*MockRoomMessagesFinderByRecipientIDAndState)(nil).FindRoomMessagesByRecipientIDAndState), ctx, recipientID, state, limit)
}
