// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrivateMessageNotifier is a mock of PrivateMessageNotifier interface.
type MockPrivateMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageNotifierMockRecorder
	isgomock struct{}
}

// MockPrivateMessageNotifierMockRecorder is the mock recorder for MockPrivateMessageNotifier.
type MockPrivateMessageNotifierMockRecorder struct {
	mock *MockPrivateMessageNotifier
}

// NewMockPrivateMessageNotifier creates a new mock instance.
func NewMockPrivateMessageNotifier(ctrl *gomock.Controller) *MockPrivateMessageNotifier {
	mock := &MockPrivateMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageNotifier) EXPECT() *MockPrivateMessageNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockPrivateMessageNotifier) Notify(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockPrivateMessageNotifierMockRecorder) Notify(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockPrivateMessageNotifier)(nil).Notify), ctx, message)
}

// MockRoomMessageNotifier is a mock of RoomMessageNotifier interface.
type MockRoomMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageNotifierMockRecorder
	isgomock struct{}
}

// MockRoomMessageNotifierMockRecorder is the mock recorder for MockRoomMessageNotifier.
type MockRoomMessageNotifierMockRecorder struct {
	mock *MockRoomMessageNotifier
}

// NewMockRoomMessageNotifier creates a new mock instance.
func NewMockRoomMessageNotifier(ctrl *gomock.Controller) *MockRoomMessageNotifier {
	mock := &MockRoomMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockRoomMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageNotifier) EXPECT() *MockRoomMessageNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockRoomMessageNotifier) Notify(ctx context.Context, message *domain.RoomMessage, recipients []kernel.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, message, recipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockRoomMessageNotifierMockRecorder) Notify(ctx, message, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockRoomMessageNotifier)(nil).Notify), ctx, message, recipients)
}
