// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageIDGenerator is a mock of MessageIDGenerator interface.
type MockMessageIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockMessageIDGeneratorMockRecorder
	isgomock struct{}
}

// MockMessageIDGeneratorMockRecorder is the mock recorder for MockMessageIDGenerator.
type MockMessageIDGeneratorMockRecorder struct {
	mock *MockMessageIDGenerator
}

// NewMockMessageIDGenerator creates a new mock instance.
func NewMockMessageIDGenerator(ctrl *gomock.Controller) *MockMessageIDGenerator {
	mock := &MockMessageIDGenerator{ctrl: ctrl}
	mock.recorder = &MockMessageIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageIDGenerator) EXPECT() *MockMessageIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockMessageIDGenerator) Generate() kernel.MessageID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(kernel.MessageID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockMessageIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockMessageIDGenerator)(nil).Generate))
}
