// Code generated by MockGen. DO NOT EDIT.
// Source: private_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=private_message_repository.go -destination=./mocks/mock_private_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrivateMessageRepository is a mock of PrivateMessageRepository interface.
type MockPrivateMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockPrivateMessageRepositoryMockRecorder is the mock recorder for MockPrivateMessageRepository.
type MockPrivateMessageRepositoryMockRecorder struct {
	mock *MockPrivateMessageRepository
}

// NewMockPrivateMessageRepository creates a new mock instance.
func NewMockPrivateMessageRepository(ctrl *gomock.Controller) *MockPrivateMessageRepository {
	mock := &MockPrivateMessageRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageRepository) EXPECT() *MockPrivateMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPrivateMessageRepository) Create(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPrivateMessageRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Create), ctx, message)
}

// FindsByUserIDs mocks base method.
func (m *MockPrivateMessageRepository) FindsByUserIDs(ctx context.Context, userID1, userID2 kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserIDs", ctx, userID1, userID2, limit, baseID)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserIDs indicates an expected call of FindsByUserIDs.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindsByUserIDs(ctx, userID1, userID2, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserIDs", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindsByUserIDs), ctx, userID1, userID2, limit, baseID)
}

// MockPrivateMessageCreator is a mock of PrivateMessageCreator interface.
type MockPrivateMessageCreator struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageCreatorMockRecorder
	isgomock struct{}
}

// MockPrivateMessageCreatorMockRecorder is the mock recorder for MockPrivateMessageCreator.
type MockPrivateMessageCreatorMockRecorder struct {
	mock *MockPrivateMessageCreator
}

// NewMockPrivateMessageCreator creates a new mock instance.
func NewMockPrivateMessageCreator(ctrl *gomock.Controller) *MockPrivateMessageCreator {
	mock := &MockPrivateMessageCreator{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageCreator) EXPECT() *MockPrivateMessageCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPrivateMessageCreator) Create(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPrivateMessageCreatorMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPrivateMessageCreator)(nil).Create), ctx, message)
}

// MockPrivateMessagesFinderByUserIDs is a mock of PrivateMessagesFinderByUserIDs interface.
type MockPrivateMessagesFinderByUserIDs struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesFinderByUserIDsMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesFinderByUserIDsMockRecorder is the mock recorder for MockPrivateMessagesFinderByUserIDs.
type MockPrivateMessagesFinderByUserIDsMockRecorder struct {
	mock *MockPrivateMessagesFinderByUserIDs
}

// NewMockPrivateMessagesFinderByUserIDs creates a new mock instance.
func NewMockPrivateMessagesFinderByUserIDs(ctrl *gomock.Controller) *MockPrivateMessagesFinderByUserIDs {
	mock := &MockPrivateMessagesFinderByUserIDs{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesFinderByUserIDsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesFinderByUserIDs) EXPECT() *MockPrivateMessagesFinderByUserIDsMockRecorder {
	return m.recorder
}

// FindsByUserIDs mocks base method.
func (m *MockPrivateMessagesFinderByUserIDs) FindsByUserIDs(ctx context.Context, userID1, userID2 kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserIDs", ctx, userID1, userID2, limit, baseID)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserIDs indicates an expected call of FindsByUserIDs.
func (mr *MockPrivateMessagesFinderByUserIDsMockRecorder) FindsByUserIDs(ctx, userID1, userID2, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserIDs", reflect.TypeOf((*MockPrivateMessagesFinderByUserIDs)(nil).FindsByUserIDs), ctx, userID1, userID2, limit, baseID)
}
