// Code generated by MockGen. DO NOT EDIT.
// Source: roomship_repository.go
//
// Generated by this command:
//
//	mockgen -source=roomship_repository.go -destination=./mocks/mock_roomship_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomshipRepository is a mock of RoomshipRepository interface.
type MockRoomshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomshipRepositoryMockRecorder is the mock recorder for MockRoomshipRepository.
type MockRoomshipRepositoryMockRecorder struct {
	mock *MockRoomshipRepository
}

// NewMockRoomshipRepository creates a new mock instance.
func NewMockRoomshipRepository(ctrl *gomock.Controller) *MockRoomshipRepository {
	mock := &MockRoomshipRepository{ctrl: ctrl}
	mock.recorder = &MockRoomshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipRepository) EXPECT() *MockRoomshipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomshipRepository) Create(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomshipRepositoryMockRecorder) Create(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomshipRepository)(nil).Create), ctx, roomship)
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipRepository) FindByUserIDAndRoomID(ctx context.Context, roomID kernel.RoomID, userID kernel.UserID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, roomID, userID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) FindByUserIDAndRoomID(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindByUserIDAndRoomID), ctx, roomID, userID)
}

// FindsByID mocks base method.
func (m *MockRoomshipRepository) FindsByID(ctx context.Context, id kernel.RoomID) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByID", ctx, id)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByID indicates an expected call of FindsByID.
func (mr *MockRoomshipRepositoryMockRecorder) FindsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindsByID), ctx, id)
}

// MockRoomshipCreator is a mock of RoomshipCreator interface.
type MockRoomshipCreator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipCreatorMockRecorder
	isgomock struct{}
}

// MockRoomshipCreatorMockRecorder is the mock recorder for MockRoomshipCreator.
type MockRoomshipCreatorMockRecorder struct {
	mock *MockRoomshipCreator
}

// NewMockRoomshipCreator creates a new mock instance.
func NewMockRoomshipCreator(ctrl *gomock.Controller) *MockRoomshipCreator {
	mock := &MockRoomshipCreator{ctrl: ctrl}
	mock.recorder = &MockRoomshipCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipCreator) EXPECT() *MockRoomshipCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomshipCreator) Create(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomshipCreatorMockRecorder) Create(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomshipCreator)(nil).Create), ctx, roomship)
}

// MockRoomshipFinderByUserIDAndRoomID is a mock of RoomshipFinderByUserIDAndRoomID interface.
type MockRoomshipFinderByUserIDAndRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipFinderByUserIDAndRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipFinderByUserIDAndRoomIDMockRecorder is the mock recorder for MockRoomshipFinderByUserIDAndRoomID.
type MockRoomshipFinderByUserIDAndRoomIDMockRecorder struct {
	mock *MockRoomshipFinderByUserIDAndRoomID
}

// NewMockRoomshipFinderByUserIDAndRoomID creates a new mock instance.
func NewMockRoomshipFinderByUserIDAndRoomID(ctrl *gomock.Controller) *MockRoomshipFinderByUserIDAndRoomID {
	mock := &MockRoomshipFinderByUserIDAndRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipFinderByUserIDAndRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipFinderByUserIDAndRoomID) EXPECT() *MockRoomshipFinderByUserIDAndRoomIDMockRecorder {
	return m.recorder
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipFinderByUserIDAndRoomID) FindByUserIDAndRoomID(ctx context.Context, roomID kernel.RoomID, userID kernel.UserID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, roomID, userID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipFinderByUserIDAndRoomIDMockRecorder) FindByUserIDAndRoomID(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipFinderByUserIDAndRoomID)(nil).FindByUserIDAndRoomID), ctx, roomID, userID)
}

// MockRoomshipsFinderByRoomID is a mock of RoomshipsFinderByRoomID interface.
type MockRoomshipsFinderByRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipsFinderByRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipsFinderByRoomIDMockRecorder is the mock recorder for MockRoomshipsFinderByRoomID.
type MockRoomshipsFinderByRoomIDMockRecorder struct {
	mock *MockRoomshipsFinderByRoomID
}

// NewMockRoomshipsFinderByRoomID creates a new mock instance.
func NewMockRoomshipsFinderByRoomID(ctrl *gomock.Controller) *MockRoomshipsFinderByRoomID {
	mock := &MockRoomshipsFinderByRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipsFinderByRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipsFinderByRoomID) EXPECT() *MockRoomshipsFinderByRoomIDMockRecorder {
	return m.recorder
}

// FindsByID mocks base method.
func (m *MockRoomshipsFinderByRoomID) FindsByID(ctx context.Context, id kernel.RoomID) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByID", ctx, id)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByID indicates an expected call of FindsByID.
func (mr *MockRoomshipsFinderByRoomIDMockRecorder) FindsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByID", reflect.TypeOf((*MockRoomshipsFinderByRoomID)(nil).FindsByID), ctx, id)
}
