// Code generated by MockGen. DO NOT EDIT.
// Source: room_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=room_message_repository.go -destination=./mocks/mock_room_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomMessageRepository is a mock of RoomMessageRepository interface.
type MockRoomMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomMessageRepositoryMockRecorder is the mock recorder for MockRoomMessageRepository.
type MockRoomMessageRepositoryMockRecorder struct {
	mock *MockRoomMessageRepository
}

// NewMockRoomMessageRepository creates a new mock instance.
func NewMockRoomMessageRepository(ctrl *gomock.Controller) *MockRoomMessageRepository {
	mock := &MockRoomMessageRepository{ctrl: ctrl}
	mock.recorder = &MockRoomMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageRepository) EXPECT() *MockRoomMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomMessageRepository) Create(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomMessageRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomMessageRepository)(nil).Create), ctx, message)
}

// FindRoomMessage mocks base method.
func (m *MockRoomMessageRepository) FindRoomMessage(ctx context.Context, messageID kernel.MessageID) (*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessage indicates an expected call of FindRoomMessage.
func (mr *MockRoomMessageRepositoryMockRecorder) FindRoomMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessage", reflect.TypeOf((*MockRoomMessageRepository)(nil).FindRoomMessage), ctx, messageID)
}

// FindsByRoomIDAndUserIDWithoutRecipients mocks base method.
func (m *MockRoomMessageRepository) FindsByRoomIDAndUserIDWithoutRecipients(ctx context.Context, roomID kernel.RoomID, userID kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomIDAndUserIDWithoutRecipients", ctx, roomID, userID, limit, baseID)
	ret0, _ := ret[0].([]*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomIDAndUserIDWithoutRecipients indicates an expected call of FindsByRoomIDAndUserIDWithoutRecipients.
func (mr *MockRoomMessageRepositoryMockRecorder) FindsByRoomIDAndUserIDWithoutRecipients(ctx, roomID, userID, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomIDAndUserIDWithoutRecipients", reflect.TypeOf((*MockRoomMessageRepository)(nil).FindsByRoomIDAndUserIDWithoutRecipients), ctx, roomID, userID, limit, baseID)
}

// MockRoomMessageCreator is a mock of RoomMessageCreator interface.
type MockRoomMessageCreator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageCreatorMockRecorder
	isgomock struct{}
}

// MockRoomMessageCreatorMockRecorder is the mock recorder for MockRoomMessageCreator.
type MockRoomMessageCreatorMockRecorder struct {
	mock *MockRoomMessageCreator
}

// NewMockRoomMessageCreator creates a new mock instance.
func NewMockRoomMessageCreator(ctrl *gomock.Controller) *MockRoomMessageCreator {
	mock := &MockRoomMessageCreator{ctrl: ctrl}
	mock.recorder = &MockRoomMessageCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageCreator) EXPECT() *MockRoomMessageCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomMessageCreator) Create(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomMessageCreatorMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomMessageCreator)(nil).Create), ctx, message)
}

// MockRoomMessageFinder is a mock of RoomMessageFinder interface.
type MockRoomMessageFinder struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageFinderMockRecorder
	isgomock struct{}
}

// MockRoomMessageFinderMockRecorder is the mock recorder for MockRoomMessageFinder.
type MockRoomMessageFinderMockRecorder struct {
	mock *MockRoomMessageFinder
}

// NewMockRoomMessageFinder creates a new mock instance.
func NewMockRoomMessageFinder(ctrl *gomock.Controller) *MockRoomMessageFinder {
	mock := &MockRoomMessageFinder{ctrl: ctrl}
	mock.recorder = &MockRoomMessageFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageFinder) EXPECT() *MockRoomMessageFinderMockRecorder {
	return m.recorder
}

// FindRoomMessage mocks base method.
func (m *MockRoomMessageFinder) FindRoomMessage(ctx context.Context, messageID kernel.MessageID) (*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessage indicates an expected call of FindRoomMessage.
func (mr *MockRoomMessageFinderMockRecorder) FindRoomMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessage", reflect.TypeOf((*MockRoomMessageFinder)(nil).FindRoomMessage), ctx, messageID)
}

// MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients is a mock of RoomMessagesFinderByRoomIDAndUserIDWithoutRecipients interface.
type MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipientsMockRecorder
	isgomock struct{}
}

// MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipientsMockRecorder is the mock recorder for MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients.
type MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipientsMockRecorder struct {
	mock *MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients
}

// NewMockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients creates a new mock instance.
func NewMockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients(ctrl *gomock.Controller) *MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients {
	mock := &MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients{ctrl: ctrl}
	mock.recorder = &MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipientsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients) EXPECT() *MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipientsMockRecorder {
	return m.recorder
}

// FindsByRoomIDAndUserIDWithoutRecipients mocks base method.
func (m *MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients) FindsByRoomIDAndUserIDWithoutRecipients(ctx context.Context, roomID kernel.RoomID, userID kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomIDAndUserIDWithoutRecipients", ctx, roomID, userID, limit, baseID)
	ret0, _ := ret[0].([]*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomIDAndUserIDWithoutRecipients indicates an expected call of FindsByRoomIDAndUserIDWithoutRecipients.
func (mr *MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipientsMockRecorder) FindsByRoomIDAndUserIDWithoutRecipients(ctx, roomID, userID, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomIDAndUserIDWithoutRecipients", reflect.TypeOf((*MockRoomMessagesFinderByRoomIDAndUserIDWithoutRecipients)(nil).FindsByRoomIDAndUserIDWithoutRecipients), ctx, roomID, userID, limit, baseID)
}
