// Code generated by MockGen. DO NOT EDIT.
// Source: private_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=private_message_repository.go -destination=./mocks/mock_private_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrivateMessageRepository is a mock of PrivateMessageRepository interface.
type MockPrivateMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockPrivateMessageRepositoryMockRecorder is the mock recorder for MockPrivateMessageRepository.
type MockPrivateMessageRepositoryMockRecorder struct {
	mock *MockPrivateMessageRepository
}

// NewMockPrivateMessageRepository creates a new mock instance.
func NewMockPrivateMessageRepository(ctrl *gomock.Controller) *MockPrivateMessageRepository {
	mock := &MockPrivateMessageRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageRepository) EXPECT() *MockPrivateMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPrivateMessageRepository) Create(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPrivateMessageRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Create), ctx, message)
}

// FindPrivateMessage mocks base method.
func (m *MockPrivateMessageRepository) FindPrivateMessage(ctx context.Context, messageID kernel.MessageID) (*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessage indicates an expected call of FindPrivateMessage.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindPrivateMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessage", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindPrivateMessage), ctx, messageID)
}

// FindPrivateMessagesByRecipientIDAndState mocks base method.
func (m *MockPrivateMessageRepository) FindPrivateMessagesByRecipientIDAndState(ctx context.Context, recipientID kernel.UserID, state domain.MessageState) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessagesByRecipientIDAndState", ctx, recipientID, state)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessagesByRecipientIDAndState indicates an expected call of FindPrivateMessagesByRecipientIDAndState.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindPrivateMessagesByRecipientIDAndState(ctx, recipientID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessagesByRecipientIDAndState", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindPrivateMessagesByRecipientIDAndState), ctx, recipientID, state)
}

// Updates mocks base method.
func (m *MockPrivateMessageRepository) Updates(ctx context.Context, messages []*domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockPrivateMessageRepositoryMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Updates), ctx, messages)
}

// MockPrivateMessageCreator is a mock of PrivateMessageCreator interface.
type MockPrivateMessageCreator struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageCreatorMockRecorder
	isgomock struct{}
}

// MockPrivateMessageCreatorMockRecorder is the mock recorder for MockPrivateMessageCreator.
type MockPrivateMessageCreatorMockRecorder struct {
	mock *MockPrivateMessageCreator
}

// NewMockPrivateMessageCreator creates a new mock instance.
func NewMockPrivateMessageCreator(ctrl *gomock.Controller) *MockPrivateMessageCreator {
	mock := &MockPrivateMessageCreator{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageCreator) EXPECT() *MockPrivateMessageCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPrivateMessageCreator) Create(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPrivateMessageCreatorMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPrivateMessageCreator)(nil).Create), ctx, message)
}

// MockPrivateMessagesUpdater is a mock of PrivateMessagesUpdater interface.
type MockPrivateMessagesUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesUpdaterMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesUpdaterMockRecorder is the mock recorder for MockPrivateMessagesUpdater.
type MockPrivateMessagesUpdaterMockRecorder struct {
	mock *MockPrivateMessagesUpdater
}

// NewMockPrivateMessagesUpdater creates a new mock instance.
func NewMockPrivateMessagesUpdater(ctrl *gomock.Controller) *MockPrivateMessagesUpdater {
	mock := &MockPrivateMessagesUpdater{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesUpdater) EXPECT() *MockPrivateMessagesUpdaterMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockPrivateMessagesUpdater) Updates(ctx context.Context, messages []*domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockPrivateMessagesUpdaterMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPrivateMessagesUpdater)(nil).Updates), ctx, messages)
}

// MockPrivateMessageFinder is a mock of PrivateMessageFinder interface.
type MockPrivateMessageFinder struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageFinderMockRecorder
	isgomock struct{}
}

// MockPrivateMessageFinderMockRecorder is the mock recorder for MockPrivateMessageFinder.
type MockPrivateMessageFinderMockRecorder struct {
	mock *MockPrivateMessageFinder
}

// NewMockPrivateMessageFinder creates a new mock instance.
func NewMockPrivateMessageFinder(ctrl *gomock.Controller) *MockPrivateMessageFinder {
	mock := &MockPrivateMessageFinder{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageFinder) EXPECT() *MockPrivateMessageFinderMockRecorder {
	return m.recorder
}

// FindPrivateMessage mocks base method.
func (m *MockPrivateMessageFinder) FindPrivateMessage(ctx context.Context, messageID kernel.MessageID) (*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessage indicates an expected call of FindPrivateMessage.
func (mr *MockPrivateMessageFinderMockRecorder) FindPrivateMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessage", reflect.TypeOf((*MockPrivateMessageFinder)(nil).FindPrivateMessage), ctx, messageID)
}

// MockPrivateMessagesFinderByRecipientIDAndState is a mock of PrivateMessagesFinderByRecipientIDAndState interface.
type MockPrivateMessagesFinderByRecipientIDAndState struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder is the mock recorder for MockPrivateMessagesFinderByRecipientIDAndState.
type MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder struct {
	mock *MockPrivateMessagesFinderByRecipientIDAndState
}

// NewMockPrivateMessagesFinderByRecipientIDAndState creates a new mock instance.
func NewMockPrivateMessagesFinderByRecipientIDAndState(ctrl *gomock.Controller) *MockPrivateMessagesFinderByRecipientIDAndState {
	mock := &MockPrivateMessagesFinderByRecipientIDAndState{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesFinderByRecipientIDAndState) EXPECT() *MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder {
	return m.recorder
}

// FindPrivateMessagesByRecipientIDAndState mocks base method.
func (m *MockPrivateMessagesFinderByRecipientIDAndState) FindPrivateMessagesByRecipientIDAndState(ctx context.Context, recipientID kernel.UserID, state domain.MessageState) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessagesByRecipientIDAndState", ctx, recipientID, state)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessagesByRecipientIDAndState indicates an expected call of FindPrivateMessagesByRecipientIDAndState.
func (mr *MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder) FindPrivateMessagesByRecipientIDAndState(ctx, recipientID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessagesByRecipientIDAndState", reflect.TypeOf((*MockPrivateMessagesFinderByRecipientIDAndState)(nil).FindPrivateMessagesByRecipientIDAndState), ctx, recipientID, state)
}
