// Code generated by MockGen. DO NOT EDIT.
// Source: private_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=private_message_repository.go -destination=./mocks/mock_private_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/chat/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrivateMessageRepository is a mock of PrivateMessageRepository interface.
type MockPrivateMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockPrivateMessageRepositoryMockRecorder is the mock recorder for MockPrivateMessageRepository.
type MockPrivateMessageRepositoryMockRecorder struct {
	mock *MockPrivateMessageRepository
}

// NewMockPrivateMessageRepository creates a new mock instance.
func NewMockPrivateMessageRepository(ctrl *gomock.Controller) *MockPrivateMessageRepository {
	mock := &MockPrivateMessageRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageRepository) EXPECT() *MockPrivateMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPrivateMessageRepository) Create(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPrivateMessageRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Create), ctx, message)
}

// FindPrivateMessage mocks base method.
func (m *MockPrivateMessageRepository) FindPrivateMessage(ctx context.Context, messageID kernel.MessageID) (*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessage indicates an expected call of FindPrivateMessage.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindPrivateMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessage", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindPrivateMessage), ctx, messageID)
}

// FindPrivateMessagesByRecipientIDAndState mocks base method.
func (m *MockPrivateMessageRepository) FindPrivateMessagesByRecipientIDAndState(ctx context.Context, recipientID kernel.UserID, state domain.MessageState, limit int) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessagesByRecipientIDAndState", ctx, recipientID, state, limit)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessagesByRecipientIDAndState indicates an expected call of FindPrivateMessagesByRecipientIDAndState.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindPrivateMessagesByRecipientIDAndState(ctx, recipientID, state, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessagesByRecipientIDAndState", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindPrivateMessagesByRecipientIDAndState), ctx, recipientID, state, limit)
}

// FindsByUserIDs mocks base method.
func (m *MockPrivateMessageRepository) FindsByUserIDs(ctx context.Context, userID1, userID2 kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserIDs", ctx, userID1, userID2, limit, baseID)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserIDs indicates an expected call of FindsByUserIDs.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindsByUserIDs(ctx, userID1, userID2, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserIDs", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindsByUserIDs), ctx, userID1, userID2, limit, baseID)
}

// Updates mocks base method.
func (m *MockPrivateMessageRepository) Updates(ctx context.Context, messages []*domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockPrivateMessageRepositoryMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Updates), ctx, messages)
}

// UpdatesByMessageIDs mocks base method.
func (m *MockPrivateMessageRepository) UpdatesByMessageIDs(ctx context.Context, userID kernel.UserID, ids []kernel.MessageID, state domain.MessageState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatesByMessageIDs", ctx, userID, ids, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatesByMessageIDs indicates an expected call of UpdatesByMessageIDs.
func (mr *MockPrivateMessageRepositoryMockRecorder) UpdatesByMessageIDs(ctx, userID, ids, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatesByMessageIDs", reflect.TypeOf((*MockPrivateMessageRepository)(nil).UpdatesByMessageIDs), ctx, userID, ids, state)
}

// UpdatesByUserID mocks base method.
func (m *MockPrivateMessageRepository) UpdatesByUserID(ctx context.Context, senderID, recipientID kernel.UserID, state domain.MessageState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatesByUserID", ctx, senderID, recipientID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatesByUserID indicates an expected call of UpdatesByUserID.
func (mr *MockPrivateMessageRepositoryMockRecorder) UpdatesByUserID(ctx, senderID, recipientID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatesByUserID", reflect.TypeOf((*MockPrivateMessageRepository)(nil).UpdatesByUserID), ctx, senderID, recipientID, state)
}

// MockPrivateMessageCreator is a mock of PrivateMessageCreator interface.
type MockPrivateMessageCreator struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageCreatorMockRecorder
	isgomock struct{}
}

// MockPrivateMessageCreatorMockRecorder is the mock recorder for MockPrivateMessageCreator.
type MockPrivateMessageCreatorMockRecorder struct {
	mock *MockPrivateMessageCreator
}

// NewMockPrivateMessageCreator creates a new mock instance.
func NewMockPrivateMessageCreator(ctrl *gomock.Controller) *MockPrivateMessageCreator {
	mock := &MockPrivateMessageCreator{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageCreator) EXPECT() *MockPrivateMessageCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPrivateMessageCreator) Create(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPrivateMessageCreatorMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPrivateMessageCreator)(nil).Create), ctx, message)
}

// MockPrivateMessagesUpdater is a mock of PrivateMessagesUpdater interface.
type MockPrivateMessagesUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesUpdaterMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesUpdaterMockRecorder is the mock recorder for MockPrivateMessagesUpdater.
type MockPrivateMessagesUpdaterMockRecorder struct {
	mock *MockPrivateMessagesUpdater
}

// NewMockPrivateMessagesUpdater creates a new mock instance.
func NewMockPrivateMessagesUpdater(ctrl *gomock.Controller) *MockPrivateMessagesUpdater {
	mock := &MockPrivateMessagesUpdater{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesUpdater) EXPECT() *MockPrivateMessagesUpdaterMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockPrivateMessagesUpdater) Updates(ctx context.Context, messages []*domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockPrivateMessagesUpdaterMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPrivateMessagesUpdater)(nil).Updates), ctx, messages)
}

// MockPrivateMessageFinder is a mock of PrivateMessageFinder interface.
type MockPrivateMessageFinder struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageFinderMockRecorder
	isgomock struct{}
}

// MockPrivateMessageFinderMockRecorder is the mock recorder for MockPrivateMessageFinder.
type MockPrivateMessageFinderMockRecorder struct {
	mock *MockPrivateMessageFinder
}

// NewMockPrivateMessageFinder creates a new mock instance.
func NewMockPrivateMessageFinder(ctrl *gomock.Controller) *MockPrivateMessageFinder {
	mock := &MockPrivateMessageFinder{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageFinder) EXPECT() *MockPrivateMessageFinderMockRecorder {
	return m.recorder
}

// FindPrivateMessage mocks base method.
func (m *MockPrivateMessageFinder) FindPrivateMessage(ctx context.Context, messageID kernel.MessageID) (*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessage indicates an expected call of FindPrivateMessage.
func (mr *MockPrivateMessageFinderMockRecorder) FindPrivateMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessage", reflect.TypeOf((*MockPrivateMessageFinder)(nil).FindPrivateMessage), ctx, messageID)
}

// MockPrivateMessagesFinderByRecipientIDAndState is a mock of PrivateMessagesFinderByRecipientIDAndState interface.
type MockPrivateMessagesFinderByRecipientIDAndState struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder is the mock recorder for MockPrivateMessagesFinderByRecipientIDAndState.
type MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder struct {
	mock *MockPrivateMessagesFinderByRecipientIDAndState
}

// NewMockPrivateMessagesFinderByRecipientIDAndState creates a new mock instance.
func NewMockPrivateMessagesFinderByRecipientIDAndState(ctrl *gomock.Controller) *MockPrivateMessagesFinderByRecipientIDAndState {
	mock := &MockPrivateMessagesFinderByRecipientIDAndState{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesFinderByRecipientIDAndState) EXPECT() *MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder {
	return m.recorder
}

// FindPrivateMessagesByRecipientIDAndState mocks base method.
func (m *MockPrivateMessagesFinderByRecipientIDAndState) FindPrivateMessagesByRecipientIDAndState(ctx context.Context, recipientID kernel.UserID, state domain.MessageState, limit int) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateMessagesByRecipientIDAndState", ctx, recipientID, state, limit)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateMessagesByRecipientIDAndState indicates an expected call of FindPrivateMessagesByRecipientIDAndState.
func (mr *MockPrivateMessagesFinderByRecipientIDAndStateMockRecorder) FindPrivateMessagesByRecipientIDAndState(ctx, recipientID, state, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateMessagesByRecipientIDAndState", reflect.TypeOf((*MockPrivateMessagesFinderByRecipientIDAndState)(nil).FindPrivateMessagesByRecipientIDAndState), ctx, recipientID, state, limit)
}

// MockPrivateMessagesStatesUpdaterByUserID is a mock of PrivateMessagesStatesUpdaterByUserID interface.
type MockPrivateMessagesStatesUpdaterByUserID struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesStatesUpdaterByUserIDMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesStatesUpdaterByUserIDMockRecorder is the mock recorder for MockPrivateMessagesStatesUpdaterByUserID.
type MockPrivateMessagesStatesUpdaterByUserIDMockRecorder struct {
	mock *MockPrivateMessagesStatesUpdaterByUserID
}

// NewMockPrivateMessagesStatesUpdaterByUserID creates a new mock instance.
func NewMockPrivateMessagesStatesUpdaterByUserID(ctrl *gomock.Controller) *MockPrivateMessagesStatesUpdaterByUserID {
	mock := &MockPrivateMessagesStatesUpdaterByUserID{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesStatesUpdaterByUserIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesStatesUpdaterByUserID) EXPECT() *MockPrivateMessagesStatesUpdaterByUserIDMockRecorder {
	return m.recorder
}

// UpdatesByUserID mocks base method.
func (m *MockPrivateMessagesStatesUpdaterByUserID) UpdatesByUserID(ctx context.Context, senderID, recipientID kernel.UserID, state domain.MessageState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatesByUserID", ctx, senderID, recipientID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatesByUserID indicates an expected call of UpdatesByUserID.
func (mr *MockPrivateMessagesStatesUpdaterByUserIDMockRecorder) UpdatesByUserID(ctx, senderID, recipientID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatesByUserID", reflect.TypeOf((*MockPrivateMessagesStatesUpdaterByUserID)(nil).UpdatesByUserID), ctx, senderID, recipientID, state)
}

// MockPrivateMessagesStatesUpdaterByMessageIDs is a mock of PrivateMessagesStatesUpdaterByMessageIDs interface.
type MockPrivateMessagesStatesUpdaterByMessageIDs struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesStatesUpdaterByMessageIDsMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesStatesUpdaterByMessageIDsMockRecorder is the mock recorder for MockPrivateMessagesStatesUpdaterByMessageIDs.
type MockPrivateMessagesStatesUpdaterByMessageIDsMockRecorder struct {
	mock *MockPrivateMessagesStatesUpdaterByMessageIDs
}

// NewMockPrivateMessagesStatesUpdaterByMessageIDs creates a new mock instance.
func NewMockPrivateMessagesStatesUpdaterByMessageIDs(ctrl *gomock.Controller) *MockPrivateMessagesStatesUpdaterByMessageIDs {
	mock := &MockPrivateMessagesStatesUpdaterByMessageIDs{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesStatesUpdaterByMessageIDsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesStatesUpdaterByMessageIDs) EXPECT() *MockPrivateMessagesStatesUpdaterByMessageIDsMockRecorder {
	return m.recorder
}

// UpdatesByMessageIDs mocks base method.
func (m *MockPrivateMessagesStatesUpdaterByMessageIDs) UpdatesByMessageIDs(ctx context.Context, userID kernel.UserID, ids []kernel.MessageID, state domain.MessageState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatesByMessageIDs", ctx, userID, ids, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatesByMessageIDs indicates an expected call of UpdatesByMessageIDs.
func (mr *MockPrivateMessagesStatesUpdaterByMessageIDsMockRecorder) UpdatesByMessageIDs(ctx, userID, ids, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatesByMessageIDs", reflect.TypeOf((*MockPrivateMessagesStatesUpdaterByMessageIDs)(nil).UpdatesByMessageIDs), ctx, userID, ids, state)
}

// MockPrivateMessagesFinderByUserIDs is a mock of PrivateMessagesFinderByUserIDs interface.
type MockPrivateMessagesFinderByUserIDs struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesFinderByUserIDsMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesFinderByUserIDsMockRecorder is the mock recorder for MockPrivateMessagesFinderByUserIDs.
type MockPrivateMessagesFinderByUserIDsMockRecorder struct {
	mock *MockPrivateMessagesFinderByUserIDs
}

// NewMockPrivateMessagesFinderByUserIDs creates a new mock instance.
func NewMockPrivateMessagesFinderByUserIDs(ctrl *gomock.Controller) *MockPrivateMessagesFinderByUserIDs {
	mock := &MockPrivateMessagesFinderByUserIDs{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesFinderByUserIDsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesFinderByUserIDs) EXPECT() *MockPrivateMessagesFinderByUserIDsMockRecorder {
	return m.recorder
}

// FindsByUserIDs mocks base method.
func (m *MockPrivateMessagesFinderByUserIDs) FindsByUserIDs(ctx context.Context, userID1, userID2 kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserIDs", ctx, userID1, userID2, limit, baseID)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserIDs indicates an expected call of FindsByUserIDs.
func (mr *MockPrivateMessagesFinderByUserIDsMockRecorder) FindsByUserIDs(ctx, userID1, userID2, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserIDs", reflect.TypeOf((*MockPrivateMessagesFinderByUserIDs)(nil).FindsByUserIDs), ctx, userID1, userID2, limit, baseID)
}
