// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "gochat/internal/profile/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProfileIDGenerator is a mock of ProfileIDGenerator interface.
type MockProfileIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockProfileIDGeneratorMockRecorder
	isgomock struct{}
}

// MockProfileIDGeneratorMockRecorder is the mock recorder for MockProfileIDGenerator.
type MockProfileIDGeneratorMockRecorder struct {
	mock *MockProfileIDGenerator
}

// NewMockProfileIDGenerator creates a new mock instance.
func NewMockProfileIDGenerator(ctrl *gomock.Controller) *MockProfileIDGenerator {
	mock := &MockProfileIDGenerator{ctrl: ctrl}
	mock.recorder = &MockProfileIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileIDGenerator) EXPECT() *MockProfileIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockProfileIDGenerator) Generate() domain.ProfileID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(domain.ProfileID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockProfileIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockProfileIDGenerator)(nil).Generate))
}
