// Code generated by MockGen. DO NOT EDIT.
// Source: room_profile_repository.go
//
// Generated by this command:
//
//	mockgen -source=room_profile_repository.go -destination=./mocks/mock_room_profile_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockRoomProfileRepository is a mock of RoomProfileRepository interface.
type MockRoomProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomProfileRepositoryMockRecorder is the mock recorder for MockRoomProfileRepository.
type MockRoomProfileRepositoryMockRecorder struct {
	mock *MockRoomProfileRepository
}

// NewMockRoomProfileRepository creates a new mock instance.
func NewMockRoomProfileRepository(ctrl *gomock.Controller) *MockRoomProfileRepository {
	mock := &MockRoomProfileRepository{ctrl: ctrl}
	mock.recorder = &MockRoomProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomProfileRepository) EXPECT() *MockRoomProfileRepositoryMockRecorder {
	return m.recorder
}
