// Code generated by MockGen. DO NOT EDIT.
// Source: roomship_repository.go
//
// Generated by this command:
//
//	mockgen -source=roomship_repository.go -destination=./mocks/mock_roomship_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/profile/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomshipRepository is a mock of RoomshipRepository interface.
type MockRoomshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomshipRepositoryMockRecorder is the mock recorder for MockRoomshipRepository.
type MockRoomshipRepositoryMockRecorder struct {
	mock *MockRoomshipRepository
}

// NewMockRoomshipRepository creates a new mock instance.
func NewMockRoomshipRepository(ctrl *gomock.Controller) *MockRoomshipRepository {
	mock := &MockRoomshipRepository{ctrl: ctrl}
	mock.recorder = &MockRoomshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipRepository) EXPECT() *MockRoomshipRepositoryMockRecorder {
	return m.recorder
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipRepository) FindByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) FindByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindByUserIDAndRoomID), ctx, userID, roomID)
}

// Save mocks base method.
func (m *MockRoomshipRepository) Save(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomshipRepositoryMockRecorder) Save(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomshipRepository)(nil).Save), ctx, roomship)
}

// MockRoomshipSaver is a mock of RoomshipSaver interface.
type MockRoomshipSaver struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipSaverMockRecorder
	isgomock struct{}
}

// MockRoomshipSaverMockRecorder is the mock recorder for MockRoomshipSaver.
type MockRoomshipSaverMockRecorder struct {
	mock *MockRoomshipSaver
}

// NewMockRoomshipSaver creates a new mock instance.
func NewMockRoomshipSaver(ctrl *gomock.Controller) *MockRoomshipSaver {
	mock := &MockRoomshipSaver{ctrl: ctrl}
	mock.recorder = &MockRoomshipSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipSaver) EXPECT() *MockRoomshipSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRoomshipSaver) Save(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomshipSaverMockRecorder) Save(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomshipSaver)(nil).Save), ctx, roomship)
}

// MockRoomshipFinderByUserIDAndRoomID is a mock of RoomshipFinderByUserIDAndRoomID interface.
type MockRoomshipFinderByUserIDAndRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipFinderByUserIDAndRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipFinderByUserIDAndRoomIDMockRecorder is the mock recorder for MockRoomshipFinderByUserIDAndRoomID.
type MockRoomshipFinderByUserIDAndRoomIDMockRecorder struct {
	mock *MockRoomshipFinderByUserIDAndRoomID
}

// NewMockRoomshipFinderByUserIDAndRoomID creates a new mock instance.
func NewMockRoomshipFinderByUserIDAndRoomID(ctrl *gomock.Controller) *MockRoomshipFinderByUserIDAndRoomID {
	mock := &MockRoomshipFinderByUserIDAndRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipFinderByUserIDAndRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipFinderByUserIDAndRoomID) EXPECT() *MockRoomshipFinderByUserIDAndRoomIDMockRecorder {
	return m.recorder
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipFinderByUserIDAndRoomID) FindByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipFinderByUserIDAndRoomIDMockRecorder) FindByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipFinderByUserIDAndRoomID)(nil).FindByUserIDAndRoomID), ctx, userID, roomID)
}
