// Code generated by MockGen. DO NOT EDIT.
// Source: room_repository.go
//
// Generated by this command:
//
//	mockgen -source=room_repository.go -destination=./mocks/mock_room_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/profile/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomRepository is a mock of RoomRepository interface.
type MockRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomRepositoryMockRecorder is the mock recorder for MockRoomRepository.
type MockRoomRepositoryMockRecorder struct {
	mock *MockRoomRepository
}

// NewMockRoomRepository creates a new mock instance.
func NewMockRoomRepository(ctrl *gomock.Controller) *MockRoomRepository {
	mock := &MockRoomRepository{ctrl: ctrl}
	mock.recorder = &MockRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepository) EXPECT() *MockRoomRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRoomRepository) Save(ctx context.Context, room *domain.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomRepositoryMockRecorder) Save(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomRepository)(nil).Save), ctx, room)
}

// MockRoomSaver is a mock of RoomSaver interface.
type MockRoomSaver struct {
	ctrl     *gomock.Controller
	recorder *MockRoomSaverMockRecorder
	isgomock struct{}
}

// MockRoomSaverMockRecorder is the mock recorder for MockRoomSaver.
type MockRoomSaverMockRecorder struct {
	mock *MockRoomSaver
}

// NewMockRoomSaver creates a new mock instance.
func NewMockRoomSaver(ctrl *gomock.Controller) *MockRoomSaver {
	mock := &MockRoomSaver{ctrl: ctrl}
	mock.recorder = &MockRoomSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomSaver) EXPECT() *MockRoomSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRoomSaver) Save(ctx context.Context, room *domain.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomSaverMockRecorder) Save(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomSaver)(nil).Save), ctx, room)
}
