// Code generated by MockGen. DO NOT EDIT.
// Source: gateway_service.go
//
// Generated by this command:
//
//	mockgen -source=gateway_service.go -destination=./mocks/mock_gateway_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	core "gochat/internal/gateway/core"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGatewayService is a mock of GatewayService interface.
type MockGatewayService struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayServiceMockRecorder
	isgomock struct{}
}

// MockGatewayServiceMockRecorder is the mock recorder for MockGatewayService.
type MockGatewayServiceMockRecorder struct {
	mock *MockGatewayService
}

// NewMockGatewayService creates a new mock instance.
func NewMockGatewayService(ctrl *gomock.Controller) *MockGatewayService {
	mock := &MockGatewayService{ctrl: ctrl}
	mock.recorder = &MockGatewayServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayService) EXPECT() *MockGatewayServiceMockRecorder {
	return m.recorder
}

// PushToUser mocks base method.
func (m *MockGatewayService) PushToUser(ctx context.Context, userID kernel.UserID, envelop *core.DownstreamEnvelop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushToUser", ctx, userID, envelop)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushToUser indicates an expected call of PushToUser.
func (mr *MockGatewayServiceMockRecorder) PushToUser(ctx, userID, envelop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushToUser", reflect.TypeOf((*MockGatewayService)(nil).PushToUser), ctx, userID, envelop)
}
