// Code generated by MockGen. DO NOT EDIT.
// Source: system_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=system_message_repository.go -destination=./mocks/mock_system_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/notification/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSystemMessageRepository is a mock of SystemMessageRepository interface.
type MockSystemMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockSystemMessageRepositoryMockRecorder is the mock recorder for MockSystemMessageRepository.
type MockSystemMessageRepositoryMockRecorder struct {
	mock *MockSystemMessageRepository
}

// NewMockSystemMessageRepository creates a new mock instance.
func NewMockSystemMessageRepository(ctrl *gomock.Controller) *MockSystemMessageRepository {
	mock := &MockSystemMessageRepository{ctrl: ctrl}
	mock.recorder = &MockSystemMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMessageRepository) EXPECT() *MockSystemMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSystemMessageRepository) Create(ctx context.Context, message *domain.SystemMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSystemMessageRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSystemMessageRepository)(nil).Create), ctx, message)
}

// FindByID mocks base method.
func (m *MockSystemMessageRepository) FindByID(ctx context.Context, messageID kernel.MessageID) (*domain.SystemMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, messageID)
	ret0, _ := ret[0].(*domain.SystemMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSystemMessageRepositoryMockRecorder) FindByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSystemMessageRepository)(nil).FindByID), ctx, messageID)
}

// FindsByState mocks base method.
func (m *MockSystemMessageRepository) FindsByState(ctx context.Context, userID kernel.UserID, state domain.MessageState, limit int) ([]*domain.SystemMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByState", ctx, userID, state, limit)
	ret0, _ := ret[0].([]*domain.SystemMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByState indicates an expected call of FindsByState.
func (mr *MockSystemMessageRepositoryMockRecorder) FindsByState(ctx, userID, state, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByState", reflect.TypeOf((*MockSystemMessageRepository)(nil).FindsByState), ctx, userID, state, limit)
}

// FindsByUserID mocks base method.
func (m *MockSystemMessageRepository) FindsByUserID(ctx context.Context, userID kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.SystemMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserID", ctx, userID, limit, baseID)
	ret0, _ := ret[0].([]*domain.SystemMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserID indicates an expected call of FindsByUserID.
func (mr *MockSystemMessageRepositoryMockRecorder) FindsByUserID(ctx, userID, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserID", reflect.TypeOf((*MockSystemMessageRepository)(nil).FindsByUserID), ctx, userID, limit, baseID)
}

// UpdatesByMessageIDs mocks base method.
func (m *MockSystemMessageRepository) UpdatesByMessageIDs(ctx context.Context, userID kernel.UserID, ids []kernel.MessageID, state domain.MessageState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatesByMessageIDs", ctx, userID, ids, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatesByMessageIDs indicates an expected call of UpdatesByMessageIDs.
func (mr *MockSystemMessageRepositoryMockRecorder) UpdatesByMessageIDs(ctx, userID, ids, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatesByMessageIDs", reflect.TypeOf((*MockSystemMessageRepository)(nil).UpdatesByMessageIDs), ctx, userID, ids, state)
}

// MockSystemMessagesStatesUpdaterByMessageIDs is a mock of SystemMessagesStatesUpdaterByMessageIDs interface.
type MockSystemMessagesStatesUpdaterByMessageIDs struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMessagesStatesUpdaterByMessageIDsMockRecorder
	isgomock struct{}
}

// MockSystemMessagesStatesUpdaterByMessageIDsMockRecorder is the mock recorder for MockSystemMessagesStatesUpdaterByMessageIDs.
type MockSystemMessagesStatesUpdaterByMessageIDsMockRecorder struct {
	mock *MockSystemMessagesStatesUpdaterByMessageIDs
}

// NewMockSystemMessagesStatesUpdaterByMessageIDs creates a new mock instance.
func NewMockSystemMessagesStatesUpdaterByMessageIDs(ctrl *gomock.Controller) *MockSystemMessagesStatesUpdaterByMessageIDs {
	mock := &MockSystemMessagesStatesUpdaterByMessageIDs{ctrl: ctrl}
	mock.recorder = &MockSystemMessagesStatesUpdaterByMessageIDsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMessagesStatesUpdaterByMessageIDs) EXPECT() *MockSystemMessagesStatesUpdaterByMessageIDsMockRecorder {
	return m.recorder
}

// UpdatesByMessageIDs mocks base method.
func (m *MockSystemMessagesStatesUpdaterByMessageIDs) UpdatesByMessageIDs(ctx context.Context, userID kernel.UserID, ids []kernel.MessageID, state domain.MessageState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatesByMessageIDs", ctx, userID, ids, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatesByMessageIDs indicates an expected call of UpdatesByMessageIDs.
func (mr *MockSystemMessagesStatesUpdaterByMessageIDsMockRecorder) UpdatesByMessageIDs(ctx, userID, ids, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatesByMessageIDs", reflect.TypeOf((*MockSystemMessagesStatesUpdaterByMessageIDs)(nil).UpdatesByMessageIDs), ctx, userID, ids, state)
}

// MockSystemMessageCreator is a mock of SystemMessageCreator interface.
type MockSystemMessageCreator struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMessageCreatorMockRecorder
	isgomock struct{}
}

// MockSystemMessageCreatorMockRecorder is the mock recorder for MockSystemMessageCreator.
type MockSystemMessageCreatorMockRecorder struct {
	mock *MockSystemMessageCreator
}

// NewMockSystemMessageCreator creates a new mock instance.
func NewMockSystemMessageCreator(ctrl *gomock.Controller) *MockSystemMessageCreator {
	mock := &MockSystemMessageCreator{ctrl: ctrl}
	mock.recorder = &MockSystemMessageCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMessageCreator) EXPECT() *MockSystemMessageCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSystemMessageCreator) Create(ctx context.Context, message *domain.SystemMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSystemMessageCreatorMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSystemMessageCreator)(nil).Create), ctx, message)
}

// MockSystemMessageFinderByID is a mock of SystemMessageFinderByID interface.
type MockSystemMessageFinderByID struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMessageFinderByIDMockRecorder
	isgomock struct{}
}

// MockSystemMessageFinderByIDMockRecorder is the mock recorder for MockSystemMessageFinderByID.
type MockSystemMessageFinderByIDMockRecorder struct {
	mock *MockSystemMessageFinderByID
}

// NewMockSystemMessageFinderByID creates a new mock instance.
func NewMockSystemMessageFinderByID(ctrl *gomock.Controller) *MockSystemMessageFinderByID {
	mock := &MockSystemMessageFinderByID{ctrl: ctrl}
	mock.recorder = &MockSystemMessageFinderByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMessageFinderByID) EXPECT() *MockSystemMessageFinderByIDMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockSystemMessageFinderByID) FindByID(ctx context.Context, messageID kernel.MessageID) (*domain.SystemMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, messageID)
	ret0, _ := ret[0].(*domain.SystemMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSystemMessageFinderByIDMockRecorder) FindByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSystemMessageFinderByID)(nil).FindByID), ctx, messageID)
}

// MockUserSystemMessagesFinderByState is a mock of UserSystemMessagesFinderByState interface.
type MockUserSystemMessagesFinderByState struct {
	ctrl     *gomock.Controller
	recorder *MockUserSystemMessagesFinderByStateMockRecorder
	isgomock struct{}
}

// MockUserSystemMessagesFinderByStateMockRecorder is the mock recorder for MockUserSystemMessagesFinderByState.
type MockUserSystemMessagesFinderByStateMockRecorder struct {
	mock *MockUserSystemMessagesFinderByState
}

// NewMockUserSystemMessagesFinderByState creates a new mock instance.
func NewMockUserSystemMessagesFinderByState(ctrl *gomock.Controller) *MockUserSystemMessagesFinderByState {
	mock := &MockUserSystemMessagesFinderByState{ctrl: ctrl}
	mock.recorder = &MockUserSystemMessagesFinderByStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSystemMessagesFinderByState) EXPECT() *MockUserSystemMessagesFinderByStateMockRecorder {
	return m.recorder
}

// FindsByState mocks base method.
func (m *MockUserSystemMessagesFinderByState) FindsByState(ctx context.Context, userID kernel.UserID, state domain.MessageState, limit int) ([]*domain.SystemMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByState", ctx, userID, state, limit)
	ret0, _ := ret[0].([]*domain.SystemMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByState indicates an expected call of FindsByState.
func (mr *MockUserSystemMessagesFinderByStateMockRecorder) FindsByState(ctx, userID, state, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByState", reflect.TypeOf((*MockUserSystemMessagesFinderByState)(nil).FindsByState), ctx, userID, state, limit)
}

// MockSystemMessageFinderByUserID is a mock of SystemMessageFinderByUserID interface.
type MockSystemMessageFinderByUserID struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMessageFinderByUserIDMockRecorder
	isgomock struct{}
}

// MockSystemMessageFinderByUserIDMockRecorder is the mock recorder for MockSystemMessageFinderByUserID.
type MockSystemMessageFinderByUserIDMockRecorder struct {
	mock *MockSystemMessageFinderByUserID
}

// NewMockSystemMessageFinderByUserID creates a new mock instance.
func NewMockSystemMessageFinderByUserID(ctrl *gomock.Controller) *MockSystemMessageFinderByUserID {
	mock := &MockSystemMessageFinderByUserID{ctrl: ctrl}
	mock.recorder = &MockSystemMessageFinderByUserIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMessageFinderByUserID) EXPECT() *MockSystemMessageFinderByUserIDMockRecorder {
	return m.recorder
}

// FindsByUserID mocks base method.
func (m *MockSystemMessageFinderByUserID) FindsByUserID(ctx context.Context, userID kernel.UserID, limit int, baseID kernel.MessageID) ([]*domain.SystemMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserID", ctx, userID, limit, baseID)
	ret0, _ := ret[0].([]*domain.SystemMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserID indicates an expected call of FindsByUserID.
func (mr *MockSystemMessageFinderByUserIDMockRecorder) FindsByUserID(ctx, userID, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserID", reflect.TypeOf((*MockSystemMessageFinderByUserID)(nil).FindsByUserID), ctx, userID, limit, baseID)
}
