// Code generated by MockGen. DO NOT EDIT.
// Source: private_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=private_message_repository.go -destination=./mocks/mock_private_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/notification/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrivateMessageRepository is a mock of PrivateMessageRepository interface.
type MockPrivateMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockPrivateMessageRepositoryMockRecorder is the mock recorder for MockPrivateMessageRepository.
type MockPrivateMessageRepositoryMockRecorder struct {
	mock *MockPrivateMessageRepository
}

// NewMockPrivateMessageRepository creates a new mock instance.
func NewMockPrivateMessageRepository(ctrl *gomock.Controller) *MockPrivateMessageRepository {
	mock := &MockPrivateMessageRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageRepository) EXPECT() *MockPrivateMessageRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockPrivateMessageRepository) FindByID(ctx context.Context, messageID kernel.MessageID) (*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, messageID)
	ret0, _ := ret[0].(*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindByID), ctx, messageID)
}

// FindsByState mocks base method.
func (m *MockPrivateMessageRepository) FindsByState(ctx context.Context, userID kernel.UserID, state domain.MessageState) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByState", ctx, userID, state)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByState indicates an expected call of FindsByState.
func (mr *MockPrivateMessageRepositoryMockRecorder) FindsByState(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByState", reflect.TypeOf((*MockPrivateMessageRepository)(nil).FindsByState), ctx, userID, state)
}

// Save mocks base method.
func (m *MockPrivateMessageRepository) Save(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPrivateMessageRepositoryMockRecorder) Save(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Save), ctx, message)
}

// Update mocks base method.
func (m *MockPrivateMessageRepository) Update(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPrivateMessageRepositoryMockRecorder) Update(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Update), ctx, message)
}

// Updates mocks base method.
func (m *MockPrivateMessageRepository) Updates(ctx context.Context, messages []*domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockPrivateMessageRepositoryMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPrivateMessageRepository)(nil).Updates), ctx, messages)
}

// MockPrivateMessageSaver is a mock of PrivateMessageSaver interface.
type MockPrivateMessageSaver struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageSaverMockRecorder
	isgomock struct{}
}

// MockPrivateMessageSaverMockRecorder is the mock recorder for MockPrivateMessageSaver.
type MockPrivateMessageSaverMockRecorder struct {
	mock *MockPrivateMessageSaver
}

// NewMockPrivateMessageSaver creates a new mock instance.
func NewMockPrivateMessageSaver(ctrl *gomock.Controller) *MockPrivateMessageSaver {
	mock := &MockPrivateMessageSaver{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageSaver) EXPECT() *MockPrivateMessageSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockPrivateMessageSaver) Save(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPrivateMessageSaverMockRecorder) Save(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPrivateMessageSaver)(nil).Save), ctx, message)
}

// MockPrivateMessageUpdater is a mock of PrivateMessageUpdater interface.
type MockPrivateMessageUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageUpdaterMockRecorder
	isgomock struct{}
}

// MockPrivateMessageUpdaterMockRecorder is the mock recorder for MockPrivateMessageUpdater.
type MockPrivateMessageUpdaterMockRecorder struct {
	mock *MockPrivateMessageUpdater
}

// NewMockPrivateMessageUpdater creates a new mock instance.
func NewMockPrivateMessageUpdater(ctrl *gomock.Controller) *MockPrivateMessageUpdater {
	mock := &MockPrivateMessageUpdater{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageUpdater) EXPECT() *MockPrivateMessageUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockPrivateMessageUpdater) Update(ctx context.Context, message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPrivateMessageUpdaterMockRecorder) Update(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPrivateMessageUpdater)(nil).Update), ctx, message)
}

// MockPrivateMessagesUpdater is a mock of PrivateMessagesUpdater interface.
type MockPrivateMessagesUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessagesUpdaterMockRecorder
	isgomock struct{}
}

// MockPrivateMessagesUpdaterMockRecorder is the mock recorder for MockPrivateMessagesUpdater.
type MockPrivateMessagesUpdaterMockRecorder struct {
	mock *MockPrivateMessagesUpdater
}

// NewMockPrivateMessagesUpdater creates a new mock instance.
func NewMockPrivateMessagesUpdater(ctrl *gomock.Controller) *MockPrivateMessagesUpdater {
	mock := &MockPrivateMessagesUpdater{ctrl: ctrl}
	mock.recorder = &MockPrivateMessagesUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessagesUpdater) EXPECT() *MockPrivateMessagesUpdaterMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockPrivateMessagesUpdater) Updates(ctx context.Context, messages []*domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockPrivateMessagesUpdaterMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockPrivateMessagesUpdater)(nil).Updates), ctx, messages)
}

// MockPrivateMessageFinderByID is a mock of PrivateMessageFinderByID interface.
type MockPrivateMessageFinderByID struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageFinderByIDMockRecorder
	isgomock struct{}
}

// MockPrivateMessageFinderByIDMockRecorder is the mock recorder for MockPrivateMessageFinderByID.
type MockPrivateMessageFinderByIDMockRecorder struct {
	mock *MockPrivateMessageFinderByID
}

// NewMockPrivateMessageFinderByID creates a new mock instance.
func NewMockPrivateMessageFinderByID(ctrl *gomock.Controller) *MockPrivateMessageFinderByID {
	mock := &MockPrivateMessageFinderByID{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageFinderByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageFinderByID) EXPECT() *MockPrivateMessageFinderByIDMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockPrivateMessageFinderByID) FindByID(ctx context.Context, messageID kernel.MessageID) (*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, messageID)
	ret0, _ := ret[0].(*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPrivateMessageFinderByIDMockRecorder) FindByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPrivateMessageFinderByID)(nil).FindByID), ctx, messageID)
}

// MockUserPrivateMessagesFinderByState is a mock of UserPrivateMessagesFinderByState interface.
type MockUserPrivateMessagesFinderByState struct {
	ctrl     *gomock.Controller
	recorder *MockUserPrivateMessagesFinderByStateMockRecorder
	isgomock struct{}
}

// MockUserPrivateMessagesFinderByStateMockRecorder is the mock recorder for MockUserPrivateMessagesFinderByState.
type MockUserPrivateMessagesFinderByStateMockRecorder struct {
	mock *MockUserPrivateMessagesFinderByState
}

// NewMockUserPrivateMessagesFinderByState creates a new mock instance.
func NewMockUserPrivateMessagesFinderByState(ctrl *gomock.Controller) *MockUserPrivateMessagesFinderByState {
	mock := &MockUserPrivateMessagesFinderByState{ctrl: ctrl}
	mock.recorder = &MockUserPrivateMessagesFinderByStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPrivateMessagesFinderByState) EXPECT() *MockUserPrivateMessagesFinderByStateMockRecorder {
	return m.recorder
}

// FindsByState mocks base method.
func (m *MockUserPrivateMessagesFinderByState) FindsByState(ctx context.Context, userID kernel.UserID, state domain.MessageState) ([]*domain.PrivateMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByState", ctx, userID, state)
	ret0, _ := ret[0].([]*domain.PrivateMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByState indicates an expected call of FindsByState.
func (mr *MockUserPrivateMessagesFinderByStateMockRecorder) FindsByState(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByState", reflect.TypeOf((*MockUserPrivateMessagesFinderByState)(nil).FindsByState), ctx, userID, state)
}
