// Code generated by MockGen. DO NOT EDIT.
// Source: room_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=room_message_repository.go -destination=./mocks/mock_room_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/notification/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomMessageRepository is a mock of RoomMessageRepository interface.
type MockRoomMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomMessageRepositoryMockRecorder is the mock recorder for MockRoomMessageRepository.
type MockRoomMessageRepositoryMockRecorder struct {
	mock *MockRoomMessageRepository
}

// NewMockRoomMessageRepository creates a new mock instance.
func NewMockRoomMessageRepository(ctrl *gomock.Controller) *MockRoomMessageRepository {
	mock := &MockRoomMessageRepository{ctrl: ctrl}
	mock.recorder = &MockRoomMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageRepository) EXPECT() *MockRoomMessageRepositoryMockRecorder {
	return m.recorder
}

// FindRoomMessage mocks base method.
func (m *MockRoomMessageRepository) FindRoomMessage(ctx context.Context, messageID kernel.MessageID) (*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessage indicates an expected call of FindRoomMessage.
func (mr *MockRoomMessageRepositoryMockRecorder) FindRoomMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessage", reflect.TypeOf((*MockRoomMessageRepository)(nil).FindRoomMessage), ctx, messageID)
}

// FindsByState mocks base method.
func (m *MockRoomMessageRepository) FindsByState(ctx context.Context, userID kernel.UserID, state domain.MessageState) ([]*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByState", ctx, userID, state)
	ret0, _ := ret[0].([]*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByState indicates an expected call of FindsByState.
func (mr *MockRoomMessageRepositoryMockRecorder) FindsByState(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByState", reflect.TypeOf((*MockRoomMessageRepository)(nil).FindsByState), ctx, userID, state)
}

// Save mocks base method.
func (m *MockRoomMessageRepository) Save(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomMessageRepositoryMockRecorder) Save(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomMessageRepository)(nil).Save), ctx, message)
}

// Update mocks base method.
func (m *MockRoomMessageRepository) Update(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoomMessageRepositoryMockRecorder) Update(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoomMessageRepository)(nil).Update), ctx, message)
}

// Updates mocks base method.
func (m *MockRoomMessageRepository) Updates(ctx context.Context, messages []*domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockRoomMessageRepositoryMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockRoomMessageRepository)(nil).Updates), ctx, messages)
}

// MockRoomMessageSaver is a mock of RoomMessageSaver interface.
type MockRoomMessageSaver struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageSaverMockRecorder
	isgomock struct{}
}

// MockRoomMessageSaverMockRecorder is the mock recorder for MockRoomMessageSaver.
type MockRoomMessageSaverMockRecorder struct {
	mock *MockRoomMessageSaver
}

// NewMockRoomMessageSaver creates a new mock instance.
func NewMockRoomMessageSaver(ctrl *gomock.Controller) *MockRoomMessageSaver {
	mock := &MockRoomMessageSaver{ctrl: ctrl}
	mock.recorder = &MockRoomMessageSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageSaver) EXPECT() *MockRoomMessageSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRoomMessageSaver) Save(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRoomMessageSaverMockRecorder) Save(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoomMessageSaver)(nil).Save), ctx, message)
}

// MockRoomMessageUpdater is a mock of RoomMessageUpdater interface.
type MockRoomMessageUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageUpdaterMockRecorder
	isgomock struct{}
}

// MockRoomMessageUpdaterMockRecorder is the mock recorder for MockRoomMessageUpdater.
type MockRoomMessageUpdaterMockRecorder struct {
	mock *MockRoomMessageUpdater
}

// NewMockRoomMessageUpdater creates a new mock instance.
func NewMockRoomMessageUpdater(ctrl *gomock.Controller) *MockRoomMessageUpdater {
	mock := &MockRoomMessageUpdater{ctrl: ctrl}
	mock.recorder = &MockRoomMessageUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageUpdater) EXPECT() *MockRoomMessageUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockRoomMessageUpdater) Update(ctx context.Context, message *domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoomMessageUpdaterMockRecorder) Update(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoomMessageUpdater)(nil).Update), ctx, message)
}

// MockRoomMessagesUpdater is a mock of RoomMessagesUpdater interface.
type MockRoomMessagesUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessagesUpdaterMockRecorder
	isgomock struct{}
}

// MockRoomMessagesUpdaterMockRecorder is the mock recorder for MockRoomMessagesUpdater.
type MockRoomMessagesUpdaterMockRecorder struct {
	mock *MockRoomMessagesUpdater
}

// NewMockRoomMessagesUpdater creates a new mock instance.
func NewMockRoomMessagesUpdater(ctrl *gomock.Controller) *MockRoomMessagesUpdater {
	mock := &MockRoomMessagesUpdater{ctrl: ctrl}
	mock.recorder = &MockRoomMessagesUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessagesUpdater) EXPECT() *MockRoomMessagesUpdaterMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockRoomMessagesUpdater) Updates(ctx context.Context, messages []*domain.RoomMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockRoomMessagesUpdaterMockRecorder) Updates(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockRoomMessagesUpdater)(nil).Updates), ctx, messages)
}

// MockRoomMessageFinderByID is a mock of RoomMessageFinderByID interface.
type MockRoomMessageFinderByID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageFinderByIDMockRecorder
	isgomock struct{}
}

// MockRoomMessageFinderByIDMockRecorder is the mock recorder for MockRoomMessageFinderByID.
type MockRoomMessageFinderByIDMockRecorder struct {
	mock *MockRoomMessageFinderByID
}

// NewMockRoomMessageFinderByID creates a new mock instance.
func NewMockRoomMessageFinderByID(ctrl *gomock.Controller) *MockRoomMessageFinderByID {
	mock := &MockRoomMessageFinderByID{ctrl: ctrl}
	mock.recorder = &MockRoomMessageFinderByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageFinderByID) EXPECT() *MockRoomMessageFinderByIDMockRecorder {
	return m.recorder
}

// FindRoomMessage mocks base method.
func (m *MockRoomMessageFinderByID) FindRoomMessage(ctx context.Context, messageID kernel.MessageID) (*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoomMessage", ctx, messageID)
	ret0, _ := ret[0].(*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoomMessage indicates an expected call of FindRoomMessage.
func (mr *MockRoomMessageFinderByIDMockRecorder) FindRoomMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoomMessage", reflect.TypeOf((*MockRoomMessageFinderByID)(nil).FindRoomMessage), ctx, messageID)
}

// MockUserRoomMessagesFinderByState is a mock of UserRoomMessagesFinderByState interface.
type MockUserRoomMessagesFinderByState struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoomMessagesFinderByStateMockRecorder
	isgomock struct{}
}

// MockUserRoomMessagesFinderByStateMockRecorder is the mock recorder for MockUserRoomMessagesFinderByState.
type MockUserRoomMessagesFinderByStateMockRecorder struct {
	mock *MockUserRoomMessagesFinderByState
}

// NewMockUserRoomMessagesFinderByState creates a new mock instance.
func NewMockUserRoomMessagesFinderByState(ctrl *gomock.Controller) *MockUserRoomMessagesFinderByState {
	mock := &MockUserRoomMessagesFinderByState{ctrl: ctrl}
	mock.recorder = &MockUserRoomMessagesFinderByStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoomMessagesFinderByState) EXPECT() *MockUserRoomMessagesFinderByStateMockRecorder {
	return m.recorder
}

// FindsByState mocks base method.
func (m *MockUserRoomMessagesFinderByState) FindsByState(ctx context.Context, userID kernel.UserID, state domain.MessageState) ([]*domain.RoomMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByState", ctx, userID, state)
	ret0, _ := ret[0].([]*domain.RoomMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByState indicates an expected call of FindsByState.
func (mr *MockUserRoomMessagesFinderByStateMockRecorder) FindsByState(ctx, userID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByState", reflect.TypeOf((*MockUserRoomMessagesFinderByState)(nil).FindsByState), ctx, userID, state)
}
