// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "gochat/internal/notification/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrivateMessageNotifier is a mock of PrivateMessageNotifier interface.
type MockPrivateMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageNotifierMockRecorder
	isgomock struct{}
}

// MockPrivateMessageNotifierMockRecorder is the mock recorder for MockPrivateMessageNotifier.
type MockPrivateMessageNotifierMockRecorder struct {
	mock *MockPrivateMessageNotifier
}

// NewMockPrivateMessageNotifier creates a new mock instance.
func NewMockPrivateMessageNotifier(ctrl *gomock.Controller) *MockPrivateMessageNotifier {
	mock := &MockPrivateMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageNotifier) EXPECT() *MockPrivateMessageNotifierMockRecorder {
	return m.recorder
}

// NotifyPrivateMessage mocks base method.
func (m *MockPrivateMessageNotifier) NotifyPrivateMessage(message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPrivateMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPrivateMessage indicates an expected call of NotifyPrivateMessage.
func (mr *MockPrivateMessageNotifierMockRecorder) NotifyPrivateMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPrivateMessage", reflect.TypeOf((*MockPrivateMessageNotifier)(nil).NotifyPrivateMessage), message)
}

// MockRoomMessageNotifier is a mock of RoomMessageNotifier interface.
type MockRoomMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageNotifierMockRecorder
	isgomock struct{}
}

// MockRoomMessageNotifierMockRecorder is the mock recorder for MockRoomMessageNotifier.
type MockRoomMessageNotifierMockRecorder struct {
	mock *MockRoomMessageNotifier
}

// NewMockRoomMessageNotifier creates a new mock instance.
func NewMockRoomMessageNotifier(ctrl *gomock.Controller) *MockRoomMessageNotifier {
	mock := &MockRoomMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockRoomMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageNotifier) EXPECT() *MockRoomMessageNotifierMockRecorder {
	return m.recorder
}

// NotifyRoomMessage mocks base method.
func (m *MockRoomMessageNotifier) NotifyRoomMessage(message *domain.RoomMessage, recipients []kernel.UserID) ([]kernel.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyRoomMessage", message, recipients)
	ret0, _ := ret[0].([]kernel.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyRoomMessage indicates an expected call of NotifyRoomMessage.
func (mr *MockRoomMessageNotifierMockRecorder) NotifyRoomMessage(message, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyRoomMessage", reflect.TypeOf((*MockRoomMessageNotifier)(nil).NotifyRoomMessage), message, recipients)
}
