// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/notification/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSystemMessageNotifier is a mock of SystemMessageNotifier interface.
type MockSystemMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMessageNotifierMockRecorder
	isgomock struct{}
}

// MockSystemMessageNotifierMockRecorder is the mock recorder for MockSystemMessageNotifier.
type MockSystemMessageNotifierMockRecorder struct {
	mock *MockSystemMessageNotifier
}

// NewMockSystemMessageNotifier creates a new mock instance.
func NewMockSystemMessageNotifier(ctrl *gomock.Controller) *MockSystemMessageNotifier {
	mock := &MockSystemMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockSystemMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMessageNotifier) EXPECT() *MockSystemMessageNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockSystemMessageNotifier) Notify(message *domain.SystemMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockSystemMessageNotifierMockRecorder) Notify(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockSystemMessageNotifier)(nil).Notify), message)
}

// MockWelcomeEmailNotifier is a mock of WelcomeEmailNotifier interface.
type MockWelcomeEmailNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockWelcomeEmailNotifierMockRecorder
	isgomock struct{}
}

// MockWelcomeEmailNotifierMockRecorder is the mock recorder for MockWelcomeEmailNotifier.
type MockWelcomeEmailNotifierMockRecorder struct {
	mock *MockWelcomeEmailNotifier
}

// NewMockWelcomeEmailNotifier creates a new mock instance.
func NewMockWelcomeEmailNotifier(ctrl *gomock.Controller) *MockWelcomeEmailNotifier {
	mock := &MockWelcomeEmailNotifier{ctrl: ctrl}
	mock.recorder = &MockWelcomeEmailNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWelcomeEmailNotifier) EXPECT() *MockWelcomeEmailNotifierMockRecorder {
	return m.recorder
}

// NotifyWelcomeEmail mocks base method.
func (m *MockWelcomeEmailNotifier) NotifyWelcomeEmail(ctx context.Context, email kernel.Email, number kernel.UserNumber) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyWelcomeEmail", ctx, email, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyWelcomeEmail indicates an expected call of NotifyWelcomeEmail.
func (mr *MockWelcomeEmailNotifierMockRecorder) NotifyWelcomeEmail(ctx, email, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyWelcomeEmail", reflect.TypeOf((*MockWelcomeEmailNotifier)(nil).NotifyWelcomeEmail), ctx, email, number)
}
