// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "gochat/internal/notification/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSystemMessageNotifier is a mock of SystemMessageNotifier interface.
type MockSystemMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMessageNotifierMockRecorder
	isgomock struct{}
}

// MockSystemMessageNotifierMockRecorder is the mock recorder for MockSystemMessageNotifier.
type MockSystemMessageNotifierMockRecorder struct {
	mock *MockSystemMessageNotifier
}

// NewMockSystemMessageNotifier creates a new mock instance.
func NewMockSystemMessageNotifier(ctrl *gomock.Controller) *MockSystemMessageNotifier {
	mock := &MockSystemMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockSystemMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMessageNotifier) EXPECT() *MockSystemMessageNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockSystemMessageNotifier) Notify(message *domain.SystemMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockSystemMessageNotifierMockRecorder) Notify(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockSystemMessageNotifier)(nil).Notify), message)
}

// MockPrivateMessageNotifier is a mock of PrivateMessageNotifier interface.
type MockPrivateMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateMessageNotifierMockRecorder
	isgomock struct{}
}

// MockPrivateMessageNotifierMockRecorder is the mock recorder for MockPrivateMessageNotifier.
type MockPrivateMessageNotifierMockRecorder struct {
	mock *MockPrivateMessageNotifier
}

// NewMockPrivateMessageNotifier creates a new mock instance.
func NewMockPrivateMessageNotifier(ctrl *gomock.Controller) *MockPrivateMessageNotifier {
	mock := &MockPrivateMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockPrivateMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateMessageNotifier) EXPECT() *MockPrivateMessageNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockPrivateMessageNotifier) Notify(message *domain.PrivateMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockPrivateMessageNotifierMockRecorder) Notify(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockPrivateMessageNotifier)(nil).Notify), message)
}

// MockRoomMessageNotifier is a mock of RoomMessageNotifier interface.
type MockRoomMessageNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMessageNotifierMockRecorder
	isgomock struct{}
}

// MockRoomMessageNotifierMockRecorder is the mock recorder for MockRoomMessageNotifier.
type MockRoomMessageNotifierMockRecorder struct {
	mock *MockRoomMessageNotifier
}

// NewMockRoomMessageNotifier creates a new mock instance.
func NewMockRoomMessageNotifier(ctrl *gomock.Controller) *MockRoomMessageNotifier {
	mock := &MockRoomMessageNotifier{ctrl: ctrl}
	mock.recorder = &MockRoomMessageNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomMessageNotifier) EXPECT() *MockRoomMessageNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockRoomMessageNotifier) Notify(message *domain.RoomMessage, recipients []kernel.UserID) ([]kernel.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", message, recipients)
	ret0, _ := ret[0].([]kernel.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Notify indicates an expected call of Notify.
func (mr *MockRoomMessageNotifierMockRecorder) Notify(message, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockRoomMessageNotifier)(nil).Notify), message, recipients)
}

// MockMessageIDGenerator is a mock of MessageIDGenerator interface.
type MockMessageIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockMessageIDGeneratorMockRecorder
	isgomock struct{}
}

// MockMessageIDGeneratorMockRecorder is the mock recorder for MockMessageIDGenerator.
type MockMessageIDGeneratorMockRecorder struct {
	mock *MockMessageIDGenerator
}

// NewMockMessageIDGenerator creates a new mock instance.
func NewMockMessageIDGenerator(ctrl *gomock.Controller) *MockMessageIDGenerator {
	mock := &MockMessageIDGenerator{ctrl: ctrl}
	mock.recorder = &MockMessageIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageIDGenerator) EXPECT() *MockMessageIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockMessageIDGenerator) Generate() kernel.MessageID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(kernel.MessageID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockMessageIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockMessageIDGenerator)(nil).Generate))
}
