// Code generated by MockGen. DO NOT EDIT.
// Source: command.go
//
// Generated by this command:
//
//	mockgen -source=command.go -destination=./mocks/mock_command.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	command "gochat/internal/shared/command"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Action mocks base method.
func (m *MockCommand) Action() command.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Action")
	ret0, _ := ret[0].(command.Action)
	return ret0
}

// Action indicates an expected call of Action.
func (mr *MockCommandMockRecorder) Action() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Action", reflect.TypeOf((*MockCommand)(nil).Action))
}

// AddHeader mocks base method.
func (m *MockCommand) AddHeader(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeader", key, value)
}

// AddHeader indicates an expected call of AddHeader.
func (mr *MockCommandMockRecorder) AddHeader(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeader", reflect.TypeOf((*MockCommand)(nil).AddHeader), key, value)
}

// AddHeaders mocks base method.
func (m *MockCommand) AddHeaders(headers map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeaders", headers)
}

// AddHeaders indicates an expected call of AddHeaders.
func (mr *MockCommandMockRecorder) AddHeaders(headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeaders", reflect.TypeOf((*MockCommand)(nil).AddHeaders), headers)
}

// AggregateID mocks base method.
func (m *MockCommand) AggregateID() kernel.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateID")
	ret0, _ := ret[0].(kernel.ID)
	return ret0
}

// AggregateID indicates an expected call of AggregateID.
func (mr *MockCommandMockRecorder) AggregateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateID", reflect.TypeOf((*MockCommand)(nil).AggregateID))
}

// Headers mocks base method.
func (m *MockCommand) Headers() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headers")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Headers indicates an expected call of Headers.
func (mr *MockCommandMockRecorder) Headers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headers", reflect.TypeOf((*MockCommand)(nil).Headers))
}

// ID mocks base method.
func (m *MockCommand) ID() command.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(command.ID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockCommandMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockCommand)(nil).ID))
}

// OccurredAt mocks base method.
func (m *MockCommand) OccurredAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OccurredAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// OccurredAt indicates an expected call of OccurredAt.
func (mr *MockCommandMockRecorder) OccurredAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OccurredAt", reflect.TypeOf((*MockCommand)(nil).OccurredAt))
}

// Payload mocks base method.
func (m *MockCommand) Payload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Payload indicates an expected call of Payload.
func (mr *MockCommandMockRecorder) Payload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockCommand)(nil).Payload))
}

// MockSpecificCommand is a mock of SpecificCommand interface.
type MockSpecificCommand struct {
	ctrl     *gomock.Controller
	recorder *MockSpecificCommandMockRecorder
	isgomock struct{}
}

// MockSpecificCommandMockRecorder is the mock recorder for MockSpecificCommand.
type MockSpecificCommandMockRecorder struct {
	mock *MockSpecificCommand
}

// NewMockSpecificCommand creates a new mock instance.
func NewMockSpecificCommand(ctrl *gomock.Controller) *MockSpecificCommand {
	mock := &MockSpecificCommand{ctrl: ctrl}
	mock.recorder = &MockSpecificCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecificCommand) EXPECT() *MockSpecificCommandMockRecorder {
	return m.recorder
}

// Action mocks base method.
func (m *MockSpecificCommand) Action() command.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Action")
	ret0, _ := ret[0].(command.Action)
	return ret0
}

// Action indicates an expected call of Action.
func (mr *MockSpecificCommandMockRecorder) Action() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Action", reflect.TypeOf((*MockSpecificCommand)(nil).Action))
}

// AddHeader mocks base method.
func (m *MockSpecificCommand) AddHeader(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeader", key, value)
}

// AddHeader indicates an expected call of AddHeader.
func (mr *MockSpecificCommandMockRecorder) AddHeader(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeader", reflect.TypeOf((*MockSpecificCommand)(nil).AddHeader), key, value)
}

// AddHeaders mocks base method.
func (m *MockSpecificCommand) AddHeaders(headers map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeaders", headers)
}

// AddHeaders indicates an expected call of AddHeaders.
func (mr *MockSpecificCommandMockRecorder) AddHeaders(headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeaders", reflect.TypeOf((*MockSpecificCommand)(nil).AddHeaders), headers)
}

// AggregateID mocks base method.
func (m *MockSpecificCommand) AggregateID() kernel.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateID")
	ret0, _ := ret[0].(kernel.ID)
	return ret0
}

// AggregateID indicates an expected call of AggregateID.
func (mr *MockSpecificCommandMockRecorder) AggregateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateID", reflect.TypeOf((*MockSpecificCommand)(nil).AggregateID))
}

// Headers mocks base method.
func (m *MockSpecificCommand) Headers() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headers")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Headers indicates an expected call of Headers.
func (mr *MockSpecificCommandMockRecorder) Headers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headers", reflect.TypeOf((*MockSpecificCommand)(nil).Headers))
}

// ID mocks base method.
func (m *MockSpecificCommand) ID() command.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(command.ID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockSpecificCommandMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockSpecificCommand)(nil).ID))
}

// Marshal mocks base method.
func (m *MockSpecificCommand) Marshal() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockSpecificCommandMockRecorder) Marshal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockSpecificCommand)(nil).Marshal))
}

// OccurredAt mocks base method.
func (m *MockSpecificCommand) OccurredAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OccurredAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// OccurredAt indicates an expected call of OccurredAt.
func (mr *MockSpecificCommandMockRecorder) OccurredAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OccurredAt", reflect.TypeOf((*MockSpecificCommand)(nil).OccurredAt))
}

// Payload mocks base method.
func (m *MockSpecificCommand) Payload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Payload indicates an expected call of Payload.
func (mr *MockSpecificCommandMockRecorder) Payload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockSpecificCommand)(nil).Payload))
}

// Unmarshal mocks base method.
func (m *MockSpecificCommand) Unmarshal(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockSpecificCommandMockRecorder) Unmarshal(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockSpecificCommand)(nil).Unmarshal), data)
}
