// Code generated by MockGen. DO NOT EDIT.
// Source: command_publisher.go
//
// Generated by this command:
//
//	mockgen -source=command_publisher.go -destination=./mocks/mock_command_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	command "gochat/internal/shared/command"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncPublisher is a mock of SyncPublisher interface.
type MockSyncPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockSyncPublisherMockRecorder
	isgomock struct{}
}

// MockSyncPublisherMockRecorder is the mock recorder for MockSyncPublisher.
type MockSyncPublisherMockRecorder struct {
	mock *MockSyncPublisher
}

// NewMockSyncPublisher creates a new mock instance.
func NewMockSyncPublisher(ctrl *gomock.Controller) *MockSyncPublisher {
	mock := &MockSyncPublisher{ctrl: ctrl}
	mock.recorder = &MockSyncPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncPublisher) EXPECT() *MockSyncPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSyncPublisher) Publish(ctx context.Context, arg1 command.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSyncPublisherMockRecorder) Publish(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSyncPublisher)(nil).Publish), ctx, arg1)
}
