// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	command "gochat/internal/shared/command"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncPublisher is a mock of SyncPublisher interface.
type MockSyncPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockSyncPublisherMockRecorder
	isgomock struct{}
}

// MockSyncPublisherMockRecorder is the mock recorder for MockSyncPublisher.
type MockSyncPublisherMockRecorder struct {
	mock *MockSyncPublisher
}

// NewMockSyncPublisher creates a new mock instance.
func NewMockSyncPublisher(ctrl *gomock.Controller) *MockSyncPublisher {
	mock := &MockSyncPublisher{ctrl: ctrl}
	mock.recorder = &MockSyncPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncPublisher) EXPECT() *MockSyncPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSyncPublisher) Publish(ctx context.Context, arg1 command.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSyncPublisherMockRecorder) Publish(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSyncPublisher)(nil).Publish), ctx, arg1)
}

// MockReceiptAsyncPublisher is a mock of ReceiptAsyncPublisher interface.
type MockReceiptAsyncPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockReceiptAsyncPublisherMockRecorder
	isgomock struct{}
}

// MockReceiptAsyncPublisherMockRecorder is the mock recorder for MockReceiptAsyncPublisher.
type MockReceiptAsyncPublisherMockRecorder struct {
	mock *MockReceiptAsyncPublisher
}

// NewMockReceiptAsyncPublisher creates a new mock instance.
func NewMockReceiptAsyncPublisher(ctrl *gomock.Controller) *MockReceiptAsyncPublisher {
	mock := &MockReceiptAsyncPublisher{ctrl: ctrl}
	mock.recorder = &MockReceiptAsyncPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiptAsyncPublisher) EXPECT() *MockReceiptAsyncPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockReceiptAsyncPublisher) Publish(ctx context.Context, receipt command.Receipt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, receipt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockReceiptAsyncPublisherMockRecorder) Publish(ctx, receipt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockReceiptAsyncPublisher)(nil).Publish), ctx, receipt)
}

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockIDGenerator) Generate() command.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(command.ID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockIDGenerator)(nil).Generate))
}

// MockReceiptIDGenerator is a mock of ReceiptIDGenerator interface.
type MockReceiptIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockReceiptIDGeneratorMockRecorder
	isgomock struct{}
}

// MockReceiptIDGeneratorMockRecorder is the mock recorder for MockReceiptIDGenerator.
type MockReceiptIDGeneratorMockRecorder struct {
	mock *MockReceiptIDGenerator
}

// NewMockReceiptIDGenerator creates a new mock instance.
func NewMockReceiptIDGenerator(ctrl *gomock.Controller) *MockReceiptIDGenerator {
	mock := &MockReceiptIDGenerator{ctrl: ctrl}
	mock.recorder = &MockReceiptIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiptIDGenerator) EXPECT() *MockReceiptIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockReceiptIDGenerator) Generate() command.ReceiptID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(command.ReceiptID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockReceiptIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockReceiptIDGenerator)(nil).Generate))
}
