// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gochat/config"
)

// Injectors from wire.go:

// Initialize wires up the dependencies for main
func Initialize(appConfig *config.App) (*Dependencies, error) {
	eventIDGenerator := provideEventIDGenerator()
	userIDGenerator := provideAuthorizationUserIDGenerator()
	userNumberGenerator, err := provideAuthorizationUserNumberGenerator(appConfig)
	if err != nil {
		return nil, err
	}
	hasher := provideHasher(appConfig)
	db, err := provideMysql(appConfig)
	if err != nil {
		return nil, err
	}
	metrics := provideMetrics()
	unitOfWork := provideUnitOfWork(db, metrics)
	userRepository := provideAuthorizationUserRepository(unitOfWork)
	eventRepository := provideEventRepository(unitOfWork)
	signUpUseCase := provideSignUpUseCase(eventIDGenerator, userIDGenerator, userNumberGenerator, hasher, userRepository, eventRepository, unitOfWork)
	client, err := provideRedis(appConfig)
	if err != nil {
		return nil, err
	}
	refreshTokenRepository := provideAuthorizationRefreshTokenRepository(client)
	accessTokenManager := provideAccessTokenManager(appConfig)
	refreshTokenGenerator := provideRefreshTokenGenerator(appConfig)
	loginUseCase := provideLoginUseCase(eventIDGenerator, hasher, userRepository, refreshTokenRepository, accessTokenManager, refreshTokenGenerator)
	refreshAccessTokenUseCase := provideRefreshAccessTokenUseCase(refreshTokenRepository, refreshTokenRepository, accessTokenManager, refreshTokenGenerator)
	parseAccessTokenUseCase := provideParseAccessTokenUseCase(accessTokenManager)
	messageIDGenerator := provideMessageIDGenerator()
	repositoryUserRepository := provideChatUserRepository(unitOfWork)
	privateMessageRepository := provideChatPrivateMessageRepository(unitOfWork)
	sendPrivateMessageUseCase := provideSendPrivateMessageUseCase(messageIDGenerator, eventIDGenerator, repositoryUserRepository, privateMessageRepository, eventRepository, unitOfWork)
	roomRepository := provideChatRoomRepository(unitOfWork)
	roomMessageRepository := provideChatRoomMessageRepository(unitOfWork)
	sendRoomMessageUseCase := provideSendRoomMessageUseCase(messageIDGenerator, eventIDGenerator, roomRepository, roomMessageRepository, eventRepository, unitOfWork)
	roomIDGenerator := provideSocialRoomIDGenerator()
	roomNumberGenerator, err := provideSocialRoomNumberGenerator(appConfig)
	if err != nil {
		return nil, err
	}
	repositoryRoomRepository := provideSocialRoomRepository(unitOfWork)
	createRoomUseCase := provideCreateRoomUseCase(eventIDGenerator, roomIDGenerator, roomNumberGenerator, hasher, repositoryRoomRepository, eventRepository, unitOfWork)
	joinRoomUseCase := provideJoinRoomUseCase(eventIDGenerator, eventRepository, repositoryRoomRepository, hasher, repositoryRoomRepository, unitOfWork)
	leaveRoomUseCase := provideLeaveRoomUseCase(eventIDGenerator, repositoryRoomRepository, repositoryRoomRepository, eventRepository, unitOfWork)
	validator, err := provideValidator()
	if err != nil {
		return nil, err
	}
	upgrader := provideWebsocketUpgrader(appConfig)
	manager := provideWebsocketManager(upgrader, metrics)
	repositoryPrivateMessageRepository := provideNotificationPrivateMessageRepository(unitOfWork)
	privateMessageReadUseCase := provideNotificationPrivateMessageReadUseCase(repositoryPrivateMessageRepository)
	repositoryRoomMessageRepository := provideNotificationRoomMessageRepository(unitOfWork)
	roomMessageReadUseCase := provideNotificationRoomMessageReadUseCase(repositoryRoomMessageRepository)
	router := provideWebsocketRouter(appConfig, privateMessageReadUseCase, roomMessageReadUseCase)
	server := provideWebsocketServer(manager, router, eventRepository, eventIDGenerator)
	engine := provideHttpRouter(appConfig, signUpUseCase, loginUseCase, refreshAccessTokenUseCase, parseAccessTokenUseCase, sendPrivateMessageUseCase, sendRoomMessageUseCase, createRoomUseCase, joinRoomUseCase, leaveRoomUseCase, validator, client, server, metrics)
	ginServer := provideHttpServer(appConfig, engine)
	eventPublisher, err := provideKafkaPublisher(appConfig, eventRepository, metrics)
	if err != nil {
		return nil, err
	}
	eventSubscriber, err := provideKafkaSubscriber(appConfig, eventRepository, metrics)
	if err != nil {
		return nil, err
	}
	canal, err := provideCanal(appConfig)
	if err != nil {
		return nil, err
	}
	outboxConsumer := provideCanalOutboxConsumer(canal, eventPublisher, eventRepository, metrics)
	dialer, err := provideGomailDialer(appConfig)
	if err != nil {
		return nil, err
	}
	emailNotifier := provideEmailNotifier(appConfig, dialer)
	diEmailServiceAvailable := provideEmailAvailable(dialer)
	diKafkaTopicEnsured := provideTopicsEnsured(appConfig)
	userSessionStartedUseCase := provideWebsocketUserSessionStartedUseCase(eventIDGenerator, eventRepository)
	userCreatedUseCase := provideAuthUserCreatedUseCase(eventIDGenerator, eventRepository, userRepository)
	userRepository2 := provideSocialUserRepository(unitOfWork)
	applicationUserCreatedUseCase := provideSocialUserCreatedUseCase(userRepository2)
	roomCreatedUseCase := provideSocialRoomCreatedUseCase(eventIDGenerator, eventRepository, repositoryRoomRepository)
	roomJoinedUseCase := provideSocialRoomJoinedUseCase(eventIDGenerator, eventRepository)
	roomLeftUseCase := provideSocialRoomLeftUseCase(eventIDGenerator, eventRepository)
	userCreatedUseCase2 := provideChatUserCreatedUseCase(repositoryUserRepository)
	applicationRoomCreatedUseCase := provideChatRoomCreatedUseCase(roomRepository, unitOfWork)
	applicationRoomJoinedUseCase := provideChatRoomJoinedUseCase(roomRepository)
	applicationRoomLeftUseCase := provideChatRoomLeftUseCase(roomRepository)
	privateMessageCreatedUseCase := provideChatPrivateMessageCreatedUseCase(eventIDGenerator, eventRepository, privateMessageRepository)
	roomMessageCreatedUseCase := provideChatRoomMessageCreatedUseCase(eventIDGenerator, eventRepository, roomRepository, roomMessageRepository)
	welcomeEmailNotificationRequestedUseCase := provideNotificationWelcomeEmailNotificationRequestedUseCase(emailNotifier)
	privateMessageNotifier := providePrivateMessageNotifier(manager)
	privateMessageNotificationRequestedUseCase := provideNotificationPrivateMessageNotificationRequestedUseCase(repositoryPrivateMessageRepository, privateMessageNotifier)
	receivedPrivateMessageNotificationRequestedUseCase := provideNotificationReceivedPrivateMessageNotificationRequestedUseCase(repositoryPrivateMessageRepository, privateMessageNotifier)
	roomMessageNotifier := provideRoomMessageNotifier(manager)
	roomMessageNotificationRequestedUseCase := provideNotificationRoomMessageNotificationRequestedUseCase(repositoryRoomMessageRepository, roomMessageNotifier)
	receivedRoomMessageNotificationRequestedUseCase := provideNotificationReceivedRoomMessageNotificationRequestedUseCase(repositoryRoomMessageRepository, roomMessageNotifier)
	diKafkaTopicSubscribed := provideKafkaTopicsSubscribed(diKafkaTopicEnsured, eventSubscriber, diEmailServiceAvailable, userSessionStartedUseCase, userCreatedUseCase, applicationUserCreatedUseCase, roomCreatedUseCase, roomJoinedUseCase, roomLeftUseCase, userCreatedUseCase2, applicationRoomCreatedUseCase, applicationRoomJoinedUseCase, applicationRoomLeftUseCase, privateMessageCreatedUseCase, roomMessageCreatedUseCase, welcomeEmailNotificationRequestedUseCase, privateMessageNotificationRequestedUseCase, receivedPrivateMessageNotificationRequestedUseCase, roomMessageNotificationRequestedUseCase, receivedRoomMessageNotificationRequestedUseCase)
	diDatabaseMigrated := provideDatabaseMigrated(db)
	dependencies, err := BuildDependencies(ginServer, eventPublisher, eventSubscriber, outboxConsumer, emailNotifier, diEmailServiceAvailable, diKafkaTopicEnsured, diKafkaTopicSubscribed, diDatabaseMigrated)
	if err != nil {
		return nil, err
	}
	return dependencies, nil
}
