// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gochat/config"
)

// Injectors from wire.go:

// Initialize wires up the dependencies for main
func Initialize(appConfig *config.App) (*Dependencies, error) {
	eventIDGenerator := provideEventIDGenerator()
	userIDGenerator := provideAuthorizationUserIDGenerator()
	userNumberGenerator, err := provideAuthorizationUserNumberGenerator(appConfig)
	if err != nil {
		return nil, err
	}
	hasher := provideHasher(appConfig)
	db, err := provideMysql(appConfig)
	if err != nil {
		return nil, err
	}
	eventRepository := provideEventRepository(db)
	userRepository := provideAuthorizationUserRepository(db, eventRepository)
	signUpUseCase := provideSignUpUseCase(eventIDGenerator, userIDGenerator, userNumberGenerator, hasher, userRepository)
	accessTokenManager := provideAccessTokenManager(appConfig)
	refreshTokenGenerator := provideRefreshTokenGenerator(appConfig)
	client, err := provideRedis(appConfig)
	if err != nil {
		return nil, err
	}
	refreshTokenRepository := provideAuthorizationRefreshTokenRepository(client)
	loginUseCase := provideLoginUseCase(eventIDGenerator, hasher, accessTokenManager, refreshTokenGenerator, userRepository, refreshTokenRepository)
	refreshAccessTokenUseCase := provideRefreshAccessTokenUseCase(refreshTokenRepository, accessTokenManager, refreshTokenGenerator)
	parseAccessTokenUseCase := provideParseAccessTokenUseCase(accessTokenManager)
	messageIDGenerator := provideMessageIDGenerator()
	privateMessageRepository := provideChatPrivateMessageRepository(db, eventRepository)
	sendPrivateMessageUseCase := provideSendPrivateMessageUseCase(messageIDGenerator, eventIDGenerator, privateMessageRepository)
	roomRepository := provideChatRoomRepository(db)
	roomMessageRepository := provideChatRoomMessageRepository(db, eventRepository)
	sendRoomMessageUseCase := provideSendRoomMessageUseCase(messageIDGenerator, eventIDGenerator, roomRepository, roomMessageRepository)
	friendshipRepository := provideFriendshipFriendshipRepository(db, eventRepository)
	friendRequestRepository := provideFriendshipFriendRequestRepository(db, eventRepository)
	operationIDGenerator := provideFriendshipOperationIDGenerator()
	sendFriendRequestUseCase, err := provideSendFriendRequestUseCase(friendshipRepository, friendRequestRepository, eventIDGenerator, operationIDGenerator)
	if err != nil {
		return nil, err
	}
	agreeFriendRequestUseCase, err := provideAgreeFriendRequestUseCase(friendRequestRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	refuseFriendRequestUseCase, err := provideRefuseFriendRequestUseCase(friendRequestRepository)
	if err != nil {
		return nil, err
	}
	listFriendRequestsUseCase, err := provideListFriendRequestsUseCase(friendRequestRepository)
	if err != nil {
		return nil, err
	}
	validator, err := provideValidator()
	if err != nil {
		return nil, err
	}
	upgrader := provideWebsocketUpgrader(appConfig)
	manager := provideWebsocketManager()
	repositoryPrivateMessageRepository := provideNotificationPrivateMessageRepository(db)
	readPrivateMessageUseCase := provideNotificationReadPrivateMessageUseCase(repositoryPrivateMessageRepository)
	repositoryRoomMessageRepository := provideNotificationRoomMessageRepository(db)
	readRoomMessageUseCase := provideNotificationReadRoomMessageUseCase(repositoryRoomMessageRepository)
	router := provideWebsocketRouter(appConfig, sendPrivateMessageUseCase, sendRoomMessageUseCase, readPrivateMessageUseCase, readRoomMessageUseCase)
	userSessionStartedUseCase := provideWebsocketUserSessionStartedUseCase(eventIDGenerator, eventRepository)
	server := provideWebsocketServer(upgrader, manager, router, userSessionStartedUseCase)
	metrics := provideMetrics()
	engine := provideHttpRouter(appConfig, signUpUseCase, loginUseCase, refreshAccessTokenUseCase, parseAccessTokenUseCase, sendPrivateMessageUseCase, sendRoomMessageUseCase, sendFriendRequestUseCase, agreeFriendRequestUseCase, refuseFriendRequestUseCase, listFriendRequestsUseCase, validator, client, server, metrics)
	ginServer := provideHttpServer(appConfig, engine)
	eventPublisher, err := provideKafkaPublisher(appConfig, eventRepository, metrics)
	if err != nil {
		return nil, err
	}
	diKafkaTopicEnsured := provideTopicsEnsured(appConfig)
	dialer, err := provideGomailDialer(appConfig)
	if err != nil {
		return nil, err
	}
	diEmailServiceAvailable := provideEmailAvailable(dialer)
	userCreatedUseCase := provideAuthUserCreatedUseCase(eventIDGenerator, eventRepository, userRepository)
	repositoryUserRepository := provideRoomshipUserRepository(db)
	applicationUserCreatedUseCase, err := provideRoomshipUserCreatedUseCase(repositoryUserRepository)
	if err != nil {
		return nil, err
	}
	userRepository2 := provideChatUserRepository(db)
	userCreatedUseCase2 := provideChatUserCreatedUseCase(userRepository2)
	roomCreatedUseCase := provideChatRoomCreatedUseCase(roomRepository)
	roomJoinedUseCase := provideChatRoomJoinedUseCase(roomRepository)
	roomLeftUseCase := provideChatRoomLeftUseCase(roomRepository)
	privateMessageCreatedUseCase := provideChatPrivateMessageCreatedUseCase(eventIDGenerator, eventRepository, privateMessageRepository)
	roomMessageCreatedUseCase := provideChatRoomMessageCreatedUseCase(eventIDGenerator, eventRepository, roomRepository, roomMessageRepository)
	emailNotifier := provideEmailNotifier(appConfig, dialer)
	welcomeEmailNotificationRequestedUseCase := provideNotificationWelcomeEmailNotificationRequestedUseCase(emailNotifier)
	systemMessageRepository := provideNotificationSystemMessageRepository(db)
	systemMessageNotifier := provideSystemMessageNotifier(manager)
	friendRequestCreatedNotificationRequestedUseCase, err := provideNotificationFriendRequestCreatedNotificationRequestedUseCase(messageIDGenerator, systemMessageRepository, systemMessageNotifier)
	if err != nil {
		return nil, err
	}
	friendshipCreatedNotificationRequestedUseCase, err := provideNotificationFriendshipCreatedNotificationRequestedUseCase(messageIDGenerator, systemMessageRepository, systemMessageNotifier)
	if err != nil {
		return nil, err
	}
	privateMessageNotifier := providePrivateMessageNotifier(manager)
	privateMessageNotificationRequestedUseCase := provideNotificationPrivateMessageNotificationRequestedUseCase(repositoryPrivateMessageRepository, privateMessageNotifier)
	roomMessageNotifier := provideRoomMessageNotifier(manager)
	roomMessageNotificationRequestedUseCase := provideNotificationRoomMessageNotificationRequestedUseCase(repositoryRoomMessageRepository, roomMessageNotifier)
	undeliveredMessagesNotificationRequestedUseCase := provideNotificationUndeliveredMessagesNotificationRequestedUseCase(systemMessageRepository, systemMessageNotifier, repositoryPrivateMessageRepository, privateMessageNotifier, repositoryRoomMessageRepository, roomMessageNotifier)
	userRepository3 := provideFriendshipUserRepository(db)
	userCreatedUseCase3, err := provideFriendshipUserCreatedUseCase(userRepository3)
	if err != nil {
		return nil, err
	}
	friendshipIDGenerator := provideFriendshipFriendshipIDGenerator()
	friendRequestAgreedUseCase, err := provideFriendshipFriendRequestAgreedUseCase(friendRequestRepository, friendshipRepository, friendshipIDGenerator, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	friendRequestCreatedUseCase, err := provideFriendshipFriendRequestCreatedUseCase(friendRequestRepository, eventRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	friendshipCreatedUseCase, err := provideFriendshipFriendshipCreatedUseCase(friendshipRepository, eventRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	kafkaRouter := provideKafkaRouter(diKafkaTopicEnsured, diEmailServiceAvailable, appConfig, userCreatedUseCase, applicationUserCreatedUseCase, userCreatedUseCase2, roomCreatedUseCase, roomJoinedUseCase, roomLeftUseCase, privateMessageCreatedUseCase, roomMessageCreatedUseCase, welcomeEmailNotificationRequestedUseCase, friendRequestCreatedNotificationRequestedUseCase, friendshipCreatedNotificationRequestedUseCase, privateMessageNotificationRequestedUseCase, roomMessageNotificationRequestedUseCase, undeliveredMessagesNotificationRequestedUseCase, userCreatedUseCase3, friendRequestAgreedUseCase, friendRequestCreatedUseCase, friendshipCreatedUseCase)
	consumer, err := provideKafkaConsumer(appConfig, kafkaRouter, eventRepository)
	if err != nil {
		return nil, err
	}
	canal, err := provideCanal(appConfig)
	if err != nil {
		return nil, err
	}
	unpublishedEventsCreatedUseCase := provideUnpublishedEventsCreatedCase(eventPublisher, eventRepository)
	eventHandler := provideCanalBinlogReaderHandler(unpublishedEventsCreatedUseCase)
	binlogReader := provideCanalBinlogReader(canal, eventHandler)
	diDatabaseMigrated := provideDatabaseMigrated(db)
	dependencies, err := BuildDependencies(ginServer, eventPublisher, consumer, binlogReader, emailNotifier, diEmailServiceAvailable, diKafkaTopicEnsured, diDatabaseMigrated)
	if err != nil {
		return nil, err
	}
	return dependencies, nil
}
