// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gochat/config"
)

// Injectors from wire.go:

// Initialize wires up the dependencies for main
func Initialize(appConfig *config.App) (*Dependencies, error) {
	eventIDGenerator := provideEventIDGenerator()
	userIDGenerator := provideAuthorizationUserIDGenerator()
	userNumberGenerator, err := provideAuthorizationUserNumberGenerator(appConfig)
	if err != nil {
		return nil, err
	}
	hasher := provideHasher(appConfig)
	db, err := provideMysqlConnection(appConfig)
	if err != nil {
		return nil, err
	}
	eventRepository := provideEventRepository(db)
	userRepository := provideAuthorizationUserRepository(db, eventRepository)
	signUpUseCase, err := provideSignUpUseCase(eventIDGenerator, userIDGenerator, userNumberGenerator, hasher, userRepository)
	if err != nil {
		return nil, err
	}
	accessTokenManager := provideAccessTokenManager(appConfig)
	refreshTokenGenerator := provideRefreshTokenGenerator(appConfig)
	client, err := provideRedisConnection(appConfig)
	if err != nil {
		return nil, err
	}
	refreshTokenRepository := provideAuthorizationRefreshTokenRepository(client)
	loginUseCase, err := provideLoginUseCase(hasher, accessTokenManager, refreshTokenGenerator, userRepository, refreshTokenRepository)
	if err != nil {
		return nil, err
	}
	refreshAccessTokenUseCase, err := provideRefreshAccessTokenUseCase(refreshTokenRepository, accessTokenManager, refreshTokenGenerator)
	if err != nil {
		return nil, err
	}
	parseAccessTokenUseCase, err := provideParseAccessTokenUseCase(accessTokenManager)
	if err != nil {
		return nil, err
	}
	userProfileRepository := provideProfileUserProfileRepository(db)
	getUserProfileUseCase, err := provideProfileGetUserProfileUseCase(userProfileRepository)
	if err != nil {
		return nil, err
	}
	httpLimiter := provideHTTPLimiter(client, appConfig)
	roomProfileRepository := provideProfileRoomProfileRepository(db)
	getRoomProfileUseCase, err := provideProfileGetRoomProfileUseCase(roomProfileRepository)
	if err != nil {
		return nil, err
	}
	updateUserProfileUseCase, err := provideProfileUpdateUserProfileUseCase(userProfileRepository)
	if err != nil {
		return nil, err
	}
	roomshipRepository := provideProfileRoomshipRepository(db)
	updateRoomProfileUseCase, err := provideProfileUpdateRoomProfileUseCase(roomshipRepository, roomProfileRepository)
	if err != nil {
		return nil, err
	}
	messageIDGenerator := provideMessageIDGenerator()
	manager := provideWebsocketManager()
	privateMessageNotifier := providePrivateMessageNotifier(manager)
	privateMessageRepository := provideChatPrivateMessageRepository(db, eventRepository)
	friendshipRepository := provideChatFriendshipRepository(db)
	sendPrivateMessageUseCase, err := provideSendPrivateMessageUseCase(messageIDGenerator, privateMessageNotifier, privateMessageRepository, friendshipRepository)
	if err != nil {
		return nil, err
	}
	roomMessageNotifier := provideRoomMessageNotifier(manager)
	repositoryRoomshipRepository := provideChatRoomshipRepository(db)
	roomMessageRepository := provideChatRoomMessageRepository(db, eventRepository)
	sendRoomMessageUseCase, err := provideSendRoomMessageUseCase(messageIDGenerator, roomMessageNotifier, repositoryRoomshipRepository, roomMessageRepository)
	if err != nil {
		return nil, err
	}
	readPrivateMessagesUseCase, err := provideChatReadPrivateMessagesUseCase(privateMessageRepository)
	if err != nil {
		return nil, err
	}
	readRoomMessagesUseCase, err := provideChatReadRoomMessagesUseCase(roomMessageRepository)
	if err != nil {
		return nil, err
	}
	listPrivateMessagesUseCase, err := provideListPrivateMessagesUseCase(privateMessageRepository)
	if err != nil {
		return nil, err
	}
	listRoomMessagesUseCase, err := provideListRoomMessagesUseCase(roomMessageRepository)
	if err != nil {
		return nil, err
	}
	roomRepository := provideRoomshipRoomRepository(db, eventRepository)
	roomIDGenerator := provideRoomshipRoomIDGenerator()
	roomNumberGenerator, err := provideRoomshipRoomNumberGenerator(appConfig)
	if err != nil {
		return nil, err
	}
	createRoomUseCase, err := provideCreateRoomUseCase(hasher, roomRepository, eventIDGenerator, roomIDGenerator, roomNumberGenerator)
	if err != nil {
		return nil, err
	}
	roomshipRepository2 := provideRoomshipRoomshipRepository(db, eventRepository)
	listRoomMembersUseCase, err := provideListRoomMembersUseCase(roomshipRepository2)
	if err != nil {
		return nil, err
	}
	memberRequestRepository := provideRoomshipMemberRequestRepository(db, eventRepository)
	operationIDGenerator := provideOperationIDGenerator()
	sendMemberRequestUseCase, err := provideSendMemberRequestUseCase(roomshipRepository2, memberRequestRepository, roomRepository, eventIDGenerator, operationIDGenerator, hasher)
	if err != nil {
		return nil, err
	}
	agreeMemberRequestUseCase, err := provideAgreeMemberRequestUseCase(memberRequestRepository, roomshipRepository2, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	refuseMemberRequestUseCase, err := provideRefuseMemberRequestUseCase(memberRequestRepository, roomshipRepository2)
	if err != nil {
		return nil, err
	}
	listMemberRequestsUseCase, err := provideListMemberRequestsUseCase(memberRequestRepository)
	if err != nil {
		return nil, err
	}
	listRoomshipsUseCase, err := provideListRoomshipsUseCase(roomshipRepository2)
	if err != nil {
		return nil, err
	}
	leaveRoomUseCase, err := provideLeaveRoomUseCase(roomRepository, roomshipRepository2)
	if err != nil {
		return nil, err
	}
	repositoryFriendshipRepository := provideFriendshipFriendshipRepository(db, eventRepository)
	friendRequestRepository := provideFriendshipFriendRequestRepository(db, eventRepository)
	sendFriendRequestUseCase, err := provideSendFriendRequestUseCase(repositoryFriendshipRepository, friendRequestRepository, eventIDGenerator, operationIDGenerator)
	if err != nil {
		return nil, err
	}
	agreeFriendRequestUseCase, err := provideAgreeFriendRequestUseCase(friendRequestRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	refuseFriendRequestUseCase, err := provideRefuseFriendRequestUseCase(friendRequestRepository)
	if err != nil {
		return nil, err
	}
	listFriendshipsUseCase, err := provideListFriendshipsUseCase(repositoryFriendshipRepository)
	if err != nil {
		return nil, err
	}
	listFriendRequestsUseCase, err := provideListFriendRequestsUseCase(friendRequestRepository)
	if err != nil {
		return nil, err
	}
	systemMessageRepository := provideNotificationSystemMessageRepository(db)
	listSystemMessagesUseCase, err := provideListSystemMessagesUseCase(systemMessageRepository)
	if err != nil {
		return nil, err
	}
	validator, err := provideValidator()
	if err != nil {
		return nil, err
	}
	upgrader := provideWebsocketUpgrader(appConfig)
	websocketLimiter := provideWebsocketLimiter(client, appConfig)
	router := provideWebsocketRouter(appConfig, websocketLimiter, validator, sendPrivateMessageUseCase, sendRoomMessageUseCase)
	userSessionStartedUseCase, err := provideWebsocketUserSessionStartedUseCase(eventIDGenerator, eventRepository)
	if err != nil {
		return nil, err
	}
	websocketHandler := provideWebsocketHandler(appConfig, upgrader, manager, router, userSessionStartedUseCase)
	producer, err := provideKafkaProducer(appConfig)
	if err != nil {
		return nil, err
	}
	kafkaLimiter := provideKafkaLimiter(client, appConfig)
	userCreatedUseCase, err := provideAuthUserCreatedUseCase(eventIDGenerator, eventRepository, userRepository)
	if err != nil {
		return nil, err
	}
	authKafkaConsumer, err := provideAuthEventConsumer(appConfig, kafkaLimiter, producer, eventRepository, userCreatedUseCase)
	if err != nil {
		return nil, err
	}
	repositoryUserRepository := provideProfileUserRepository(db)
	applicationUserCreatedUseCase, err := provideProfileUserCreatedUseCase(repositoryUserRepository, userProfileRepository)
	if err != nil {
		return nil, err
	}
	repositoryRoomRepository := provideProfileRoomRepository(db)
	roomCreatedUseCase, err := provideProfileRoomCreatedUseCase(repositoryRoomRepository, roomProfileRepository)
	if err != nil {
		return nil, err
	}
	roomshipCreatedUseCase, err := provideProfileRoomshipCreatedUseCase(roomshipRepository)
	if err != nil {
		return nil, err
	}
	profileKafkaConsumer, err := provideProfileEventConsumer(appConfig, kafkaLimiter, producer, eventRepository, applicationUserCreatedUseCase, roomCreatedUseCase, roomshipCreatedUseCase)
	if err != nil {
		return nil, err
	}
	userRepository2 := provideChatUserRepository(db)
	userCreatedUseCase2, err := provideChatUserCreatedUseCase(userRepository2)
	if err != nil {
		return nil, err
	}
	roomRepository2 := provideChatRoomRepository(db)
	applicationRoomCreatedUseCase, err := provideChatRoomCreatedUseCase(roomRepository2)
	if err != nil {
		return nil, err
	}
	applicationRoomshipCreatedUseCase, err := provideChatRoomshipCreatedUseCase(repositoryRoomshipRepository)
	if err != nil {
		return nil, err
	}
	friendshipCreatedUseCase, err := provideChatFriendshipCreatedUseCase(friendshipRepository)
	if err != nil {
		return nil, err
	}
	undeliveredMessagesPushRequestedUseCase, err := provideChatUndeliveredMessagesPushRequestedUseCase(privateMessageRepository, privateMessageNotifier, roomMessageRepository, roomMessageNotifier)
	if err != nil {
		return nil, err
	}
	chatKafkaConsumer, err := provideChatEventConsumer(appConfig, kafkaLimiter, producer, eventRepository, userCreatedUseCase2, applicationRoomCreatedUseCase, applicationRoomshipCreatedUseCase, friendshipCreatedUseCase, undeliveredMessagesPushRequestedUseCase)
	if err != nil {
		return nil, err
	}
	dialer := provideGomailDialer(appConfig)
	diEmailServiceAvailable := provideEmailAvailable(dialer)
	emailNotifier := provideEmailNotifier(appConfig, dialer)
	welcomeEmailNotificationRequestedUseCase, err := provideNotificationWelcomeEmailNotificationRequestedUseCase(emailNotifier)
	if err != nil {
		return nil, err
	}
	systemMessageNotifier := provideSystemMessageNotifier(manager)
	systemMessageNotificationRequestedUseCase, err := provideNotificationSystemMessageNotificationRequestedUseCase(messageIDGenerator, systemMessageRepository, systemMessageNotifier)
	if err != nil {
		return nil, err
	}
	undeliveredMessagesNotificationRequestedUseCase, err := provideNotificationUndeliveredMessagesNotificationRequestedUseCase(systemMessageRepository, systemMessageNotifier)
	if err != nil {
		return nil, err
	}
	notificationKafkaConsumer, err := provideNotificationEventConsumer(appConfig, diEmailServiceAvailable, kafkaLimiter, producer, eventRepository, welcomeEmailNotificationRequestedUseCase, systemMessageNotificationRequestedUseCase, undeliveredMessagesNotificationRequestedUseCase)
	if err != nil {
		return nil, err
	}
	userRepository3 := provideRoomshipUserRepository(db)
	userCreatedUseCase3, err := provideRoomshipUserCreatedUseCase(userRepository3)
	if err != nil {
		return nil, err
	}
	roomshipIDGenerator := provideRoomshipRoomshipIDGenerator()
	roomCreatedUseCase2, err := provideRoomshipRoomCreatedUseCase(roomshipIDGenerator, eventIDGenerator, roomRepository, roomshipRepository2, eventRepository)
	if err != nil {
		return nil, err
	}
	memberRequestAgreedUseCase, err := provideRoomshipMemberRequestAgreedUseCase(roomshipIDGenerator, eventIDGenerator, memberRequestRepository, roomshipRepository2)
	if err != nil {
		return nil, err
	}
	memberRequestCreatedUseCase, err := provideRoomshipMemberRequestCreatedUseCase(memberRequestRepository, roomshipRepository2, eventIDGenerator, eventRepository)
	if err != nil {
		return nil, err
	}
	roomshipCreatedUseCase2, err := provideRoomshipRoomshipCreatedUseCase(roomshipRepository2, eventRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	roomshipKafkaConsumer, err := provideRoomshipEventConsumer(appConfig, kafkaLimiter, producer, eventRepository, userCreatedUseCase3, roomCreatedUseCase2, memberRequestAgreedUseCase, memberRequestCreatedUseCase, roomshipCreatedUseCase2)
	if err != nil {
		return nil, err
	}
	userRepository4 := provideFriendshipUserRepository(db)
	userCreatedUseCase4, err := provideFriendshipUserCreatedUseCase(userRepository4)
	if err != nil {
		return nil, err
	}
	friendshipIDGenerator := provideFriendshipFriendshipIDGenerator()
	friendRequestAgreedUseCase, err := provideFriendshipFriendRequestAgreedUseCase(friendRequestRepository, repositoryFriendshipRepository, friendshipIDGenerator, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	friendRequestCreatedUseCase, err := provideFriendshipFriendRequestCreatedUseCase(friendRequestRepository, eventRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	applicationFriendshipCreatedUseCase, err := provideFriendshipFriendshipCreatedUseCase(repositoryFriendshipRepository, eventRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	friendshipKafkaConsumer, err := provideFriendshipEventConsumer(appConfig, kafkaLimiter, producer, eventRepository, userCreatedUseCase4, friendRequestAgreedUseCase, friendRequestCreatedUseCase, applicationFriendshipCreatedUseCase)
	if err != nil {
		return nil, err
	}
	v := provideKafkaConsumers(authKafkaConsumer, profileKafkaConsumer, chatKafkaConsumer, notificationKafkaConsumer, roomshipKafkaConsumer, friendshipKafkaConsumer)
	v2 := provideIsReadyChecker(db, client, producer, v)
	otelShutdown, err := provideObservability(appConfig)
	if err != nil {
		return nil, err
	}
	engine := provideHttpRouter(appConfig, signUpUseCase, loginUseCase, refreshAccessTokenUseCase, parseAccessTokenUseCase, getUserProfileUseCase, httpLimiter, getRoomProfileUseCase, updateUserProfileUseCase, updateRoomProfileUseCase, sendPrivateMessageUseCase, sendRoomMessageUseCase, readPrivateMessagesUseCase, readRoomMessagesUseCase, listPrivateMessagesUseCase, listRoomMessagesUseCase, createRoomUseCase, listRoomMembersUseCase, sendMemberRequestUseCase, agreeMemberRequestUseCase, refuseMemberRequestUseCase, listMemberRequestsUseCase, listRoomshipsUseCase, leaveRoomUseCase, sendFriendRequestUseCase, agreeFriendRequestUseCase, refuseFriendRequestUseCase, listFriendshipsUseCase, listFriendRequestsUseCase, listSystemMessagesUseCase, validator, websocketHandler, v2, otelShutdown)
	server := provideHttpServer(appConfig, engine)
	eventPublisher, err := provideKafkaPublisher(appConfig, eventRepository)
	if err != nil {
		return nil, err
	}
	canal, err := provideCanal(appConfig)
	if err != nil {
		return nil, err
	}
	unpublishedEventsCreatedUseCase, err := provideUnpublishedEventsCreatedCase(eventPublisher, eventRepository)
	if err != nil {
		return nil, err
	}
	eventHandler := provideCanalBinlogReaderHandler(unpublishedEventsCreatedUseCase)
	binlogReader := provideCanalBinlogReader(canal, eventHandler)
	dependencies, err := BuildDependencies(server, eventPublisher, v, binlogReader, emailNotifier, otelShutdown, diEmailServiceAvailable)
	if err != nil {
		return nil, err
	}
	return dependencies, nil
}
