// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gochat/config"
)

// Injectors from wire.go:

// Initialize wires up the dependencies for main
func Initialize(appConfig *config.App) (*Dependencies, error) {
	eventIDGenerator := provideEventIDGenerator()
	userIDGenerator := provideAuthorizationUserIDGenerator()
	userNumberGenerator, err := provideAuthorizationUserNumberGenerator(appConfig)
	if err != nil {
		return nil, err
	}
	hasher := provideHasher(appConfig)
	db, err := provideMysqlConnection(appConfig)
	if err != nil {
		return nil, err
	}
	eventRepository := provideEventRepository(db)
	userRepository := provideAuthorizationUserRepository(db, eventRepository)
	signUpUseCase, err := provideSignUpUseCase(eventIDGenerator, userIDGenerator, userNumberGenerator, hasher, userRepository)
	if err != nil {
		return nil, err
	}
	accessTokenManager := provideAccessTokenManager(appConfig)
	refreshTokenGenerator := provideRefreshTokenGenerator(appConfig)
	client, err := provideRedisConnection(appConfig)
	if err != nil {
		return nil, err
	}
	refreshTokenRepository := provideAuthorizationRefreshTokenRepository(client)
	loginByNumberUseCase, err := provideLoginByNumberUseCase(hasher, accessTokenManager, refreshTokenGenerator, userRepository, refreshTokenRepository)
	if err != nil {
		return nil, err
	}
	loginByEmailUseCase, err := provideLoginByEmailUseCase(hasher, accessTokenManager, refreshTokenGenerator, userRepository, refreshTokenRepository)
	if err != nil {
		return nil, err
	}
	refreshAccessTokenUseCase, err := provideRefreshAccessTokenUseCase(refreshTokenRepository, accessTokenManager, refreshTokenGenerator)
	if err != nil {
		return nil, err
	}
	parseAccessTokenUseCase, err := provideParseAccessTokenUseCase(accessTokenManager)
	if err != nil {
		return nil, err
	}
	userProfileRepository := provideProfileUserProfileRepository(db)
	getUserProfileUseCase, err := provideProfileGetUserProfileUseCase(userProfileRepository)
	if err != nil {
		return nil, err
	}
	httpLimiter := provideHTTPLimiter(client, appConfig)
	roomProfileRepository := provideProfileRoomProfileRepository(db)
	getRoomProfileUseCase, err := provideProfileGetRoomProfileUseCase(roomProfileRepository)
	if err != nil {
		return nil, err
	}
	updateUserProfileUseCase, err := provideProfileUpdateUserProfileUseCase(userProfileRepository)
	if err != nil {
		return nil, err
	}
	roomshipRepository := provideProfileRoomshipRepository(db)
	updateRoomProfileUseCase, err := provideProfileUpdateRoomProfileUseCase(roomshipRepository, roomProfileRepository)
	if err != nil {
		return nil, err
	}
	messageIDGenerator := provideMessageIDGenerator()
	privateMessageRepository := provideChatPrivateMessageRepository(db, eventRepository)
	friendshipRepository := provideChatFriendshipRepository(db)
	sendPrivateMessageUseCase, err := provideSendPrivateMessageUseCase(eventIDGenerator, messageIDGenerator, privateMessageRepository, friendshipRepository)
	if err != nil {
		return nil, err
	}
	repositoryRoomshipRepository := provideChatRoomshipRepository(db)
	roomMessageRepository := provideChatRoomMessageRepository(db, eventRepository)
	sendRoomMessageUseCase, err := provideSendRoomMessageUseCase(messageIDGenerator, eventIDGenerator, repositoryRoomshipRepository, roomMessageRepository)
	if err != nil {
		return nil, err
	}
	listPrivateMessagesUseCase, err := provideListPrivateMessagesUseCase(privateMessageRepository)
	if err != nil {
		return nil, err
	}
	listRoomMessagesUseCase, err := provideListRoomMessagesUseCase(roomMessageRepository)
	if err != nil {
		return nil, err
	}
	roomRepository := provideRoomshipRoomRepository(db, eventRepository)
	roomIDGenerator := provideRoomshipRoomIDGenerator()
	roomNumberGenerator, err := provideRoomshipRoomNumberGenerator(appConfig)
	if err != nil {
		return nil, err
	}
	createRoomUseCase, err := provideCreateRoomUseCase(hasher, roomRepository, eventIDGenerator, roomIDGenerator, roomNumberGenerator)
	if err != nil {
		return nil, err
	}
	roomshipRepository2 := provideRoomshipRoomshipRepository(db, eventRepository)
	listRoomMembersUseCase, err := provideListRoomMembersUseCase(roomshipRepository2)
	if err != nil {
		return nil, err
	}
	memberRequestRepository := provideRoomshipMemberRequestRepository(db, eventRepository)
	operationIDGenerator := provideOperationIDGenerator()
	sendMemberRequestUseCase, err := provideSendMemberRequestUseCase(roomshipRepository2, memberRequestRepository, roomRepository, operationIDGenerator, hasher)
	if err != nil {
		return nil, err
	}
	agreeMemberRequestUseCase, err := provideAgreeMemberRequestUseCase(memberRequestRepository, roomshipRepository2, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	refuseMemberRequestUseCase, err := provideRefuseMemberRequestUseCase(memberRequestRepository, roomshipRepository2)
	if err != nil {
		return nil, err
	}
	listMemberRequestsUseCase, err := provideListMemberRequestsUseCase(memberRequestRepository)
	if err != nil {
		return nil, err
	}
	listRoomshipsUseCase, err := provideListRoomshipsUseCase(roomshipRepository2)
	if err != nil {
		return nil, err
	}
	leaveRoomUseCase, err := provideLeaveRoomUseCase(roomRepository, roomshipRepository2)
	if err != nil {
		return nil, err
	}
	repositoryFriendshipRepository := provideFriendshipFriendshipRepository(db, eventRepository)
	friendRequestRepository := provideFriendshipFriendRequestRepository(db, eventRepository)
	sendFriendRequestUseCase, err := provideSendFriendRequestUseCase(repositoryFriendshipRepository, friendRequestRepository, operationIDGenerator)
	if err != nil {
		return nil, err
	}
	agreeFriendRequestUseCase, err := provideAgreeFriendRequestUseCase(friendRequestRepository, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	refuseFriendRequestUseCase, err := provideRefuseFriendRequestUseCase(friendRequestRepository)
	if err != nil {
		return nil, err
	}
	listFriendshipsUseCase, err := provideListFriendshipsUseCase(repositoryFriendshipRepository)
	if err != nil {
		return nil, err
	}
	listFriendRequestsUseCase, err := provideListFriendRequestsUseCase(friendRequestRepository)
	if err != nil {
		return nil, err
	}
	validator, err := provideValidator()
	if err != nil {
		return nil, err
	}
	manager := provideGatewayManager()
	eventSyncPublisher, err := provideKafkaSyncPublisher(appConfig)
	if err != nil {
		return nil, err
	}
	allowedAction := provideAllowedAction()
	upstreamHandler := provideGatewayUpstreamHandler(eventSyncPublisher, eventIDGenerator, allowedAction)
	sessionIDGenerator := provideSessionIDGenerator()
	diCheckOrigin := provideCheckOrigin(appConfig)
	ingressHandler := provideGatewayIngressHandler(manager, upstreamHandler, sessionIDGenerator, diCheckOrigin)
	producer, err := provideKafkaProducer(appConfig)
	if err != nil {
		return nil, err
	}
	kafkaLimiter := provideKafkaLimiter(client, appConfig)
	gatewayService := provideGatewayService(manager)
	diIsRetriableError := provideIsRetriableError()
	repositoryUserRepository := provideProfileUserRepository(db)
	userCreatedUseCase, err := provideProfileUserCreatedUseCase(repositoryUserRepository, userProfileRepository)
	if err != nil {
		return nil, err
	}
	repositoryRoomRepository := provideProfileRoomRepository(db)
	roomCreatedUseCase, err := provideProfileRoomCreatedUseCase(repositoryRoomRepository, roomProfileRepository)
	if err != nil {
		return nil, err
	}
	roomshipCreatedUseCase, err := provideProfileRoomshipCreatedUseCase(roomshipRepository)
	if err != nil {
		return nil, err
	}
	userRepository2 := provideChatUserRepository(db)
	applicationUserCreatedUseCase, err := provideChatUserCreatedUseCase(userRepository2)
	if err != nil {
		return nil, err
	}
	roomRepository2 := provideChatRoomRepository(db)
	applicationRoomCreatedUseCase, err := provideChatRoomCreatedUseCase(roomRepository2)
	if err != nil {
		return nil, err
	}
	applicationRoomshipCreatedUseCase, err := provideChatRoomshipCreatedUseCase(repositoryRoomshipRepository)
	if err != nil {
		return nil, err
	}
	friendshipCreatedUseCase, err := provideChatFriendshipCreatedUseCase(friendshipRepository)
	if err != nil {
		return nil, err
	}
	userRepository3 := provideRoomshipUserRepository(db)
	userCreatedUseCase2, err := provideRoomshipUserCreatedUseCase(userRepository3)
	if err != nil {
		return nil, err
	}
	roomshipIDGenerator := provideRoomshipRoomshipIDGenerator()
	roomCreatedUseCase2, err := provideRoomshipRoomCreatedUseCase(roomshipIDGenerator, eventIDGenerator, roomRepository, roomshipRepository2)
	if err != nil {
		return nil, err
	}
	memberRequestAgreedUseCase, err := provideRoomshipMemberRequestAgreedUseCase(roomshipIDGenerator, eventIDGenerator, memberRequestRepository, roomshipRepository2)
	if err != nil {
		return nil, err
	}
	userRepository4 := provideFriendshipUserRepository(db)
	userCreatedUseCase3, err := provideFriendshipUserCreatedUseCase(userRepository4)
	if err != nil {
		return nil, err
	}
	friendshipIDGenerator := provideFriendshipFriendshipIDGenerator()
	friendRequestAgreedUseCase, err := provideFriendshipFriendRequestAgreedUseCase(friendRequestRepository, repositoryFriendshipRepository, friendshipIDGenerator, eventIDGenerator)
	if err != nil {
		return nil, err
	}
	deliverService := provideNotificationGatewayDelivery(gatewayService)
	notificationCreatedUseCase, err := provideNotificationCreatedUseCase(deliverService)
	if err != nil {
		return nil, err
	}
	v, err := provideKafkaConsumers(appConfig, kafkaLimiter, client, producer, eventRepository, gatewayService, diIsRetriableError, userCreatedUseCase, roomCreatedUseCase, roomshipCreatedUseCase, applicationUserCreatedUseCase, applicationRoomCreatedUseCase, applicationRoomshipCreatedUseCase, friendshipCreatedUseCase, sendPrivateMessageUseCase, sendRoomMessageUseCase, userCreatedUseCase2, roomCreatedUseCase2, memberRequestAgreedUseCase, userCreatedUseCase3, friendRequestAgreedUseCase, notificationCreatedUseCase)
	if err != nil {
		return nil, err
	}
	v2 := provideIsReadyChecker(db, client, producer, v)
	otelShutdown, err := provideObservability(appConfig)
	if err != nil {
		return nil, err
	}
	engine := provideHttpRouter(appConfig, signUpUseCase, loginByNumberUseCase, loginByEmailUseCase, refreshAccessTokenUseCase, parseAccessTokenUseCase, getUserProfileUseCase, httpLimiter, getRoomProfileUseCase, updateUserProfileUseCase, updateRoomProfileUseCase, sendPrivateMessageUseCase, sendRoomMessageUseCase, listPrivateMessagesUseCase, listRoomMessagesUseCase, createRoomUseCase, listRoomMembersUseCase, sendMemberRequestUseCase, agreeMemberRequestUseCase, refuseMemberRequestUseCase, listMemberRequestsUseCase, listRoomshipsUseCase, leaveRoomUseCase, sendFriendRequestUseCase, agreeFriendRequestUseCase, refuseFriendRequestUseCase, listFriendshipsUseCase, listFriendRequestsUseCase, validator, ingressHandler, v2, otelShutdown)
	server := provideHttpServer(appConfig, engine)
	eventAsyncPublisher, err := provideKafkaAsyncPublisher(appConfig, eventRepository)
	if err != nil {
		return nil, err
	}
	unpublishedEventsCreatedUseCase, err := provideUnpublishedEventsCreatedCase(appConfig, eventAsyncPublisher, eventRepository)
	if err != nil {
		return nil, err
	}
	dispatcher, err := provideOutboxDispatcher(appConfig, unpublishedEventsCreatedUseCase)
	if err != nil {
		return nil, err
	}
	canal, err := provideCanal(appConfig)
	if err != nil {
		return nil, err
	}
	eventHandler := provideCanalBinlogReaderHandler(dispatcher)
	binlogReader := provideCanalBinlogReader(canal, eventHandler)
	dependencies, err := BuildDependencies(server, db, client, eventAsyncPublisher, eventSyncPublisher, dispatcher, v, binlogReader, otelShutdown)
	if err != nil {
		return nil, err
	}
	return dependencies, nil
}
