// Code generated by MockGen. DO NOT EDIT.
// Source: friend_request_repository.go
//
// Generated by this command:
//
//	mockgen -source=friend_request_repository.go -destination=./mocks/friend_request_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/friendship/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFriendRequestRepository is a mock of FriendRequestRepository interface.
type MockFriendRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFriendRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockFriendRequestRepositoryMockRecorder is the mock recorder for MockFriendRequestRepository.
type MockFriendRequestRepositoryMockRecorder struct {
	mock *MockFriendRequestRepository
}

// NewMockFriendRequestRepository creates a new mock instance.
func NewMockFriendRequestRepository(ctrl *gomock.Controller) *MockFriendRequestRepository {
	mock := &MockFriendRequestRepository{ctrl: ctrl}
	mock.recorder = &MockFriendRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendRequestRepository) EXPECT() *MockFriendRequestRepositoryMockRecorder {
	return m.recorder
}

// MockFriendRequestsFinderByUserID is a mock of FriendRequestsFinderByUserID interface.
type MockFriendRequestsFinderByUserID struct {
	ctrl     *gomock.Controller
	recorder *MockFriendRequestsFinderByUserIDMockRecorder
	isgomock struct{}
}

// MockFriendRequestsFinderByUserIDMockRecorder is the mock recorder for MockFriendRequestsFinderByUserID.
type MockFriendRequestsFinderByUserIDMockRecorder struct {
	mock *MockFriendRequestsFinderByUserID
}

// NewMockFriendRequestsFinderByUserID creates a new mock instance.
func NewMockFriendRequestsFinderByUserID(ctrl *gomock.Controller) *MockFriendRequestsFinderByUserID {
	mock := &MockFriendRequestsFinderByUserID{ctrl: ctrl}
	mock.recorder = &MockFriendRequestsFinderByUserIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendRequestsFinderByUserID) EXPECT() *MockFriendRequestsFinderByUserIDMockRecorder {
	return m.recorder
}

// FindsByUserID mocks base method.
func (m *MockFriendRequestsFinderByUserID) FindsByUserID(ctx context.Context, userID kernel.UserID, baseID kernel.OperationID, limit int) ([]*domain.FriendRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserID", ctx, userID, baseID, limit)
	ret0, _ := ret[0].([]*domain.FriendRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserID indicates an expected call of FindsByUserID.
func (mr *MockFriendRequestsFinderByUserIDMockRecorder) FindsByUserID(ctx, userID, baseID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserID", reflect.TypeOf((*MockFriendRequestsFinderByUserID)(nil).FindsByUserID), ctx, userID, baseID, limit)
}
