// Code generated by MockGen. DO NOT EDIT.
// Source: friendship_repository.go
//
// Generated by this command:
//
//	mockgen -source=friendship_repository.go -destination=./mocks/friendship_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/friendship/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFriendshipRepository is a mock of FriendshipRepository interface.
type MockFriendshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipRepositoryMockRecorder
	isgomock struct{}
}

// MockFriendshipRepositoryMockRecorder is the mock recorder for MockFriendshipRepository.
type MockFriendshipRepositoryMockRecorder struct {
	mock *MockFriendshipRepository
}

// NewMockFriendshipRepository creates a new mock instance.
func NewMockFriendshipRepository(ctrl *gomock.Controller) *MockFriendshipRepository {
	mock := &MockFriendshipRepository{ctrl: ctrl}
	mock.recorder = &MockFriendshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipRepository) EXPECT() *MockFriendshipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFriendshipRepository) Create(ctx context.Context, friendship *domain.Friendship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, friendship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFriendshipRepositoryMockRecorder) Create(ctx, friendship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFriendshipRepository)(nil).Create), ctx, friendship)
}

// ExistByUserID mocks base method.
func (m *MockFriendshipRepository) ExistByUserID(ctx context.Context, userID1, userID2 kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserID", ctx, userID1, userID2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserID indicates an expected call of ExistByUserID.
func (mr *MockFriendshipRepositoryMockRecorder) ExistByUserID(ctx, userID1, userID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserID", reflect.TypeOf((*MockFriendshipRepository)(nil).ExistByUserID), ctx, userID1, userID2)
}

// MockFriendshipCreator is a mock of FriendshipCreator interface.
type MockFriendshipCreator struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipCreatorMockRecorder
	isgomock struct{}
}

// MockFriendshipCreatorMockRecorder is the mock recorder for MockFriendshipCreator.
type MockFriendshipCreatorMockRecorder struct {
	mock *MockFriendshipCreator
}

// NewMockFriendshipCreator creates a new mock instance.
func NewMockFriendshipCreator(ctrl *gomock.Controller) *MockFriendshipCreator {
	mock := &MockFriendshipCreator{ctrl: ctrl}
	mock.recorder = &MockFriendshipCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipCreator) EXPECT() *MockFriendshipCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFriendshipCreator) Create(ctx context.Context, friendship *domain.Friendship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, friendship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFriendshipCreatorMockRecorder) Create(ctx, friendship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFriendshipCreator)(nil).Create), ctx, friendship)
}

// MockFriendshipExisterByUserID is a mock of FriendshipExisterByUserID interface.
type MockFriendshipExisterByUserID struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipExisterByUserIDMockRecorder
	isgomock struct{}
}

// MockFriendshipExisterByUserIDMockRecorder is the mock recorder for MockFriendshipExisterByUserID.
type MockFriendshipExisterByUserIDMockRecorder struct {
	mock *MockFriendshipExisterByUserID
}

// NewMockFriendshipExisterByUserID creates a new mock instance.
func NewMockFriendshipExisterByUserID(ctrl *gomock.Controller) *MockFriendshipExisterByUserID {
	mock := &MockFriendshipExisterByUserID{ctrl: ctrl}
	mock.recorder = &MockFriendshipExisterByUserIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipExisterByUserID) EXPECT() *MockFriendshipExisterByUserIDMockRecorder {
	return m.recorder
}

// ExistByUserID mocks base method.
func (m *MockFriendshipExisterByUserID) ExistByUserID(ctx context.Context, userID1, userID2 kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserID", ctx, userID1, userID2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserID indicates an expected call of ExistByUserID.
func (mr *MockFriendshipExisterByUserIDMockRecorder) ExistByUserID(ctx, userID1, userID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserID", reflect.TypeOf((*MockFriendshipExisterByUserID)(nil).ExistByUserID), ctx, userID1, userID2)
}
