// Code generated by MockGen. DO NOT EDIT.
// Source: friend_request_repository.go
//
// Generated by this command:
//
//	mockgen -source=friend_request_repository.go -destination=./mocks/friend_request_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFriendRequestRepository is a mock of FriendRequestRepository interface.
type MockFriendRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFriendRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockFriendRequestRepositoryMockRecorder is the mock recorder for MockFriendRequestRepository.
type MockFriendRequestRepositoryMockRecorder struct {
	mock *MockFriendRequestRepository
}

// NewMockFriendRequestRepository creates a new mock instance.
func NewMockFriendRequestRepository(ctrl *gomock.Controller) *MockFriendRequestRepository {
	mock := &MockFriendRequestRepository{ctrl: ctrl}
	mock.recorder = &MockFriendRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendRequestRepository) EXPECT() *MockFriendRequestRepositoryMockRecorder {
	return m.recorder
}

// Exist mocks base method.
func (m *MockFriendRequestRepository) Exist(ctx context.Context, from, to kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exist", ctx, from, to)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exist indicates an expected call of Exist.
func (mr *MockFriendRequestRepositoryMockRecorder) Exist(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exist", reflect.TypeOf((*MockFriendRequestRepository)(nil).Exist), ctx, from, to)
}

// MockFriendRequestExister is a mock of FriendRequestExister interface.
type MockFriendRequestExister struct {
	ctrl     *gomock.Controller
	recorder *MockFriendRequestExisterMockRecorder
	isgomock struct{}
}

// MockFriendRequestExisterMockRecorder is the mock recorder for MockFriendRequestExister.
type MockFriendRequestExisterMockRecorder struct {
	mock *MockFriendRequestExister
}

// NewMockFriendRequestExister creates a new mock instance.
func NewMockFriendRequestExister(ctrl *gomock.Controller) *MockFriendRequestExister {
	mock := &MockFriendRequestExister{ctrl: ctrl}
	mock.recorder = &MockFriendRequestExisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendRequestExister) EXPECT() *MockFriendRequestExisterMockRecorder {
	return m.recorder
}

// Exist mocks base method.
func (m *MockFriendRequestExister) Exist(ctx context.Context, from, to kernel.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exist", ctx, from, to)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exist indicates an expected call of Exist.
func (mr *MockFriendRequestExisterMockRecorder) Exist(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exist", reflect.TypeOf((*MockFriendRequestExister)(nil).Exist), ctx, from, to)
}
