// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// initializeDependencies builds the application Dependencies using Google Wire.
func initializeDependencies(configPath ConfigPath, envPath EnvPath) (*Dependencies, error) {
	app, err := provideAppConfig(configPath, envPath)
	if err != nil {
		return nil, err
	}
	db, err := provideMysql(app)
	if err != nil {
		return nil, err
	}
	eventRepository := provideEventRepository(db)
	eventPublisher, err := provideKafkaPublisher(app, eventRepository)
	if err != nil {
		return nil, err
	}
	eventSubscriber, err := provideKafkaSubscriber(app)
	if err != nil {
		return nil, err
	}
	outboxConsumer, err := provideOutboxConsumer(app, eventPublisher, eventRepository)
	if err != nil {
		return nil, err
	}
	emailNotifier := provideEmailNotifier(app)
	eventIDGenerator := provideEventIDGenerator()
	userIDGenerator := provideAuthorizationUserIDGenerator()
	userNumberGenerator, err := provideAuthorizationUserNumberGenerator(app)
	if err != nil {
		return nil, err
	}
	hasher := provideHasher(app)
	userRepository := provideAuthorizationUserRepository(db)
	signUpUseCase := provideSignUpUseCase(eventIDGenerator, userIDGenerator, userNumberGenerator, hasher, userRepository, eventRepository)
	client, err := provideRedis(app)
	if err != nil {
		return nil, err
	}
	refreshTokenRepository := provideAuthorizationRefreshTokenRepository(client)
	accessTokenManager := provideAccessTokenManager(app)
	refreshTokenGenerator := provideRefreshTokenGenerator(app)
	loginUseCase := provideLoginUseCase(eventIDGenerator, hasher, userRepository, userRepository, refreshTokenRepository, accessTokenManager, refreshTokenGenerator, eventRepository)
	refreshAccessTokenUseCase := provideRefreshAccessTokenUseCase(refreshTokenRepository, refreshTokenRepository, accessTokenManager, refreshTokenGenerator)
	parseAccessTokenUseCase := provideParseAccessTokenUseCase(accessTokenManager)
	messageIDGenerator := provideMessageIDGenerator()
	repositoryUserRepository := provideChatUserRepository(db)
	messageRepository := provideChatMessageRepository(db)
	sendPrivateMessageUseCase := provideSendPrivateMessageUseCase(messageIDGenerator, eventIDGenerator, repositoryUserRepository, messageRepository, eventRepository)
	roomRepository := provideChatRoomRepository(db)
	sendRoomMessageUseCase := provideSendRoomMessageUseCase(messageIDGenerator, eventIDGenerator, roomRepository, messageRepository, eventRepository)
	roomIDGenerator := provideSocialRoomIDGenerator()
	roomNumberGenerator, err := provideSocialRoomNumberGenerator(app)
	if err != nil {
		return nil, err
	}
	repositoryRoomRepository := provideSocialRoomRepository(db)
	createRoomUseCase := provideCreateRoomUseCase(eventIDGenerator, roomIDGenerator, roomNumberGenerator, hasher, repositoryRoomRepository, eventRepository)
	joinRoomUseCase := provideJoinRoomUseCase(eventIDGenerator, eventRepository, repositoryRoomRepository, hasher, repositoryRoomRepository)
	leaveRoomUseCase := provideLeaveRoomUseCase(eventIDGenerator, repositoryRoomRepository, repositoryRoomRepository, eventRepository)
	validator, err := provideValidator()
	if err != nil {
		return nil, err
	}
	upgrader := provideWebsocketUpgrader(app)
	manager := provideWebsocketManager(upgrader)
	repositoryMessageRepository := provideNotificationMessageRepository(db)
	messageReadUseCase := provideNotificationMessageReadUseCase(repositoryMessageRepository)
	router := provideWebsocketRouter(messageReadUseCase)
	server := provideWebsocketServer(manager, router, eventPublisher, eventIDGenerator)
	engine := provideHttpRouter(app, signUpUseCase, loginUseCase, refreshAccessTokenUseCase, parseAccessTokenUseCase, sendPrivateMessageUseCase, sendRoomMessageUseCase, createRoomUseCase, joinRoomUseCase, leaveRoomUseCase, validator, client, server)
	userSessionStartedUseCase := provideWebsocketUserSessionStartedUseCase(eventIDGenerator, eventPublisher)
	userCreatedUseCase := provideAuthUserCreatedUseCase(eventIDGenerator, eventPublisher, userRepository)
	userRepository2 := provideSocialUserRepository(db)
	usecaseUserCreatedUseCase := provideSocialUserCreatedUseCase(userRepository2)
	roomCreatedUseCase := provideSocialRoomCreatedUseCase(eventIDGenerator, eventPublisher, repositoryRoomRepository)
	roomJoinedUseCase := provideSocialRoomJoinedUseCase(eventIDGenerator, eventPublisher)
	roomLeftUseCase := provideSocialRoomLeftUseCase(eventIDGenerator, eventPublisher)
	userCreatedUseCase2 := provideChatUserCreatedUseCase(repositoryUserRepository)
	usecaseRoomCreatedUseCase := provideChatRoomCreatedUseCase(roomRepository)
	usecaseRoomJoinedUseCase := provideChatRoomJoinedUseCase(roomRepository)
	usecaseRoomLeftUseCase := provideChatRoomLeftUseCase(roomRepository)
	privateMessageCreatedUseCase := provideChatPrivateMessageCreatedUseCase(eventIDGenerator, eventPublisher, messageRepository)
	roomMessageCreatedUseCase := provideChatRoomMessageCreatedUseCase(eventIDGenerator, eventPublisher, messageRepository)
	welcomeEmailNotificationRequestedUseCase := provideNotificationWelcomeEmailNotificationRequestedUseCase(emailNotifier)
	messageNotifier := provideMessageNotifier(manager)
	messageNotificationRequestedUseCase := provideNotificationMessageNotificationRequestedUseCase(repositoryMessageRepository, messageNotifier)
	undeliveredMessageNotificationRequestedUseCase := provideNotificationUndeliveredMessageNotificationRequestedUseCase(repositoryMessageRepository, messageNotifier)
	error2 := provideKafkaSubscriptions(eventSubscriber, userSessionStartedUseCase, userCreatedUseCase, usecaseUserCreatedUseCase, roomCreatedUseCase, roomJoinedUseCase, roomLeftUseCase, userCreatedUseCase2, usecaseRoomCreatedUseCase, usecaseRoomJoinedUseCase, usecaseRoomLeftUseCase, privateMessageCreatedUseCase, roomMessageCreatedUseCase, welcomeEmailNotificationRequestedUseCase, messageNotificationRequestedUseCase, undeliveredMessageNotificationRequestedUseCase)
	dependencies, err := BuildDependencies(app, db, eventPublisher, eventSubscriber, outboxConsumer, emailNotifier, engine, error2)
	if err != nil {
		return nil, err
	}
	return dependencies, nil
}
