// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// initializeDependencies builds the application Dependencies using Google Wire.
func initializeDependencies(configPath ConfigPath, envPath EnvPath) (*Dependencies, error) {
	app, err := provideAppConfig(configPath, envPath)
	if err != nil {
		return nil, err
	}
	db, err := provideMysql(app)
	if err != nil {
		return nil, err
	}
	client, err := provideRedis(app)
	if err != nil {
		return nil, err
	}
	validator, err := provideValidator()
	if err != nil {
		return nil, err
	}
	eventRepository := provideEventRepository(db)
	eventPublisher, err := provideKafkaPublisher(app, eventRepository)
	if err != nil {
		return nil, err
	}
	eventSubscriber, err := provideKafkaSubscriber(app)
	if err != nil {
		return nil, err
	}
	outboxConsumer, err := provideOutboxConsumer(app, eventPublisher, eventRepository)
	if err != nil {
		return nil, err
	}
	emailNotifier := provideEmailNotifier(app)
	eventIDGenerator := provideEventIDGenerator()
	userIDGenerator := provideAuthorizationUserIDGenerator()
	userNumberGenerator, err := provideAuthorizationUserNumberGenerator(app)
	if err != nil {
		return nil, err
	}
	hasher := provideHasher(app)
	userRepository := provideAuthorizationUserRepository(db)
	signUpUseCase := provideSignUpUseCase(eventIDGenerator, userIDGenerator, userNumberGenerator, hasher, userRepository, eventRepository)
	refreshTokenRepository := provideAuthorizationRefreshTokenRepository(client)
	accessTokenManager := provideAccessTokenManager(app)
	refreshTokenGenerator := provideRefreshTokenGenerator(app)
	loginUseCase := provideLoginUseCase(eventIDGenerator, hasher, userRepository, userRepository, refreshTokenRepository, accessTokenManager, refreshTokenGenerator, eventRepository)
	refreshAccessTokenUseCase := provideRefreshAccessTokenUseCase(refreshTokenRepository, refreshTokenRepository, accessTokenManager, refreshTokenGenerator)
	parseAccessTokenUseCase := provideParseAccessTokenUseCase(accessTokenManager)
	messageIDGenerator := provideMessageIDGenerator()
	repositoryUserRepository := provideChatUserRepository(db)
	messageRepository := provideChatMessageRepository(db)
	sendPrivateMessageUseCase := provideSendPrivateMessageUseCase(messageIDGenerator, eventIDGenerator, repositoryUserRepository, messageRepository, eventRepository)
	roomRepository := provideChatRoomRepository(db)
	sendRoomMessageUseCase := provideSendRoomMessageUseCase(messageIDGenerator, eventIDGenerator, roomRepository, messageRepository, eventRepository)
	roomIDGenerator := provideSocialRoomIDGenerator()
	roomNumberGenerator, err := provideSocialRoomNumberGenerator(app)
	if err != nil {
		return nil, err
	}
	repositoryRoomRepository := provideSocialRoomRepository(db)
	createRoomUseCase := provideCreateRoomUseCase(eventIDGenerator, roomIDGenerator, roomNumberGenerator, hasher, repositoryRoomRepository, eventRepository)
	joinRoomUseCase := provideJoinRoomUseCase(eventIDGenerator, eventRepository, repositoryRoomRepository, hasher, repositoryRoomRepository)
	leaveRoomUseCase := provideLeaveRoomUseCase(eventIDGenerator, repositoryRoomRepository, repositoryRoomRepository, eventRepository)
	userCreatedUseCase := provideAuthUserCreatedUseCase(eventIDGenerator, eventPublisher, userRepository)
	userRepository2 := provideSocialUserRepository(db)
	usecaseUserCreatedUseCase := provideSocialUserCreatedUseCase(userRepository2)
	roomCreatedUseCase := provideSocialRoomCreatedUseCase(eventIDGenerator, eventPublisher, repositoryRoomRepository)
	roomJoinedUseCase := provideSocialRoomJoinedUseCase(eventIDGenerator, eventPublisher)
	roomLeftUseCase := provideSocialRoomLeftUseCase(eventIDGenerator, eventPublisher)
	userCreatedUseCase2 := provideChatUserCreatedUseCase(repositoryUserRepository)
	usecaseRoomCreatedUseCase := provideChatRoomCreatedUseCase(roomRepository)
	usecaseRoomJoinedUseCase := provideChatRoomJoinedUseCase(roomRepository)
	usecaseRoomLeftUseCase := provideChatRoomLeftUseCase(roomRepository)
	userRepository3 := provideNotificationUserRepository(db)
	userCreatedUseCase3 := provideNotificationUserCreatedUseCase(userRepository3)
	roomRepository2 := provideNotificationRoomRepository(db)
	roomCreatedUseCase2 := provideNotificationRoomCreatedUseCase(roomRepository2)
	roomJoinedUseCase2 := provideNotificationRoomJoinedUseCase(roomRepository2)
	roomLeftUseCase2 := provideNotificationRoomLeftUseCase(roomRepository2)
	privateMessageCreatedUseCase := provideNotificationPrivateMessageCreatedUseCase()
	roomMessageCreatedUseCase := provideNotificationRoomMessageCreatedUseCase()
	error2 := provideKafkaSubscriptions(eventSubscriber, userCreatedUseCase, usecaseUserCreatedUseCase, roomCreatedUseCase, roomJoinedUseCase, roomLeftUseCase, userCreatedUseCase2, usecaseRoomCreatedUseCase, usecaseRoomJoinedUseCase, usecaseRoomLeftUseCase, userCreatedUseCase3, roomCreatedUseCase2, roomJoinedUseCase2, roomLeftUseCase2, privateMessageCreatedUseCase, roomMessageCreatedUseCase, eventIDGenerator, eventPublisher)
	dependencies, err := BuildDependencies(app, db, client, validator, eventPublisher, eventSubscriber, outboxConsumer, emailNotifier, signUpUseCase, loginUseCase, refreshAccessTokenUseCase, parseAccessTokenUseCase, sendPrivateMessageUseCase, sendRoomMessageUseCase, createRoomUseCase, joinRoomUseCase, leaveRoomUseCase, error2)
	if err != nil {
		return nil, err
	}
	return dependencies, nil
}
