// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "gochat/internal/roomship/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncryptor is a mock of Encryptor interface.
type MockEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorMockRecorder
	isgomock struct{}
}

// MockEncryptorMockRecorder is the mock recorder for MockEncryptor.
type MockEncryptorMockRecorder struct {
	mock *MockEncryptor
}

// NewMockEncryptor creates a new mock instance.
func NewMockEncryptor(ctrl *gomock.Controller) *MockEncryptor {
	mock := &MockEncryptor{ctrl: ctrl}
	mock.recorder = &MockEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptor) EXPECT() *MockEncryptorMockRecorder {
	return m.recorder
}

// Encrypt mocks base method.
func (m *MockEncryptor) Encrypt(origin string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", origin)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptorMockRecorder) Encrypt(origin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptor)(nil).Encrypt), origin)
}

// MockComparator is a mock of Comparator interface.
type MockComparator struct {
	ctrl     *gomock.Controller
	recorder *MockComparatorMockRecorder
	isgomock struct{}
}

// MockComparatorMockRecorder is the mock recorder for MockComparator.
type MockComparatorMockRecorder struct {
	mock *MockComparator
}

// NewMockComparator creates a new mock instance.
func NewMockComparator(ctrl *gomock.Controller) *MockComparator {
	mock := &MockComparator{ctrl: ctrl}
	mock.recorder = &MockComparatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComparator) EXPECT() *MockComparatorMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockComparator) Compare(encrypted, origin string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", encrypted, origin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockComparatorMockRecorder) Compare(encrypted, origin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockComparator)(nil).Compare), encrypted, origin)
}

// MockRoomNumberGenerator is a mock of RoomNumberGenerator interface.
type MockRoomNumberGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomNumberGeneratorMockRecorder
	isgomock struct{}
}

// MockRoomNumberGeneratorMockRecorder is the mock recorder for MockRoomNumberGenerator.
type MockRoomNumberGeneratorMockRecorder struct {
	mock *MockRoomNumberGenerator
}

// NewMockRoomNumberGenerator creates a new mock instance.
func NewMockRoomNumberGenerator(ctrl *gomock.Controller) *MockRoomNumberGenerator {
	mock := &MockRoomNumberGenerator{ctrl: ctrl}
	mock.recorder = &MockRoomNumberGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomNumberGenerator) EXPECT() *MockRoomNumberGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockRoomNumberGenerator) Generate() domain.RoomNumber {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(domain.RoomNumber)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockRoomNumberGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRoomNumberGenerator)(nil).Generate))
}

// MockRoomIDGenerator is a mock of RoomIDGenerator interface.
type MockRoomIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomIDGeneratorMockRecorder
	isgomock struct{}
}

// MockRoomIDGeneratorMockRecorder is the mock recorder for MockRoomIDGenerator.
type MockRoomIDGeneratorMockRecorder struct {
	mock *MockRoomIDGenerator
}

// NewMockRoomIDGenerator creates a new mock instance.
func NewMockRoomIDGenerator(ctrl *gomock.Controller) *MockRoomIDGenerator {
	mock := &MockRoomIDGenerator{ctrl: ctrl}
	mock.recorder = &MockRoomIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomIDGenerator) EXPECT() *MockRoomIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockRoomIDGenerator) Generate() kernel.RoomID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(kernel.RoomID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockRoomIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRoomIDGenerator)(nil).Generate))
}

// MockRoomshipIDGenerator is a mock of RoomshipIDGenerator interface.
type MockRoomshipIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipIDGeneratorMockRecorder
	isgomock struct{}
}

// MockRoomshipIDGeneratorMockRecorder is the mock recorder for MockRoomshipIDGenerator.
type MockRoomshipIDGeneratorMockRecorder struct {
	mock *MockRoomshipIDGenerator
}

// NewMockRoomshipIDGenerator creates a new mock instance.
func NewMockRoomshipIDGenerator(ctrl *gomock.Controller) *MockRoomshipIDGenerator {
	mock := &MockRoomshipIDGenerator{ctrl: ctrl}
	mock.recorder = &MockRoomshipIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipIDGenerator) EXPECT() *MockRoomshipIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockRoomshipIDGenerator) Generate() domain.RoomshipID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(domain.RoomshipID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockRoomshipIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRoomshipIDGenerator)(nil).Generate))
}

// MockOperationIDGenerator is a mock of OperationIDGenerator interface.
type MockOperationIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockOperationIDGeneratorMockRecorder
	isgomock struct{}
}

// MockOperationIDGeneratorMockRecorder is the mock recorder for MockOperationIDGenerator.
type MockOperationIDGeneratorMockRecorder struct {
	mock *MockOperationIDGenerator
}

// NewMockOperationIDGenerator creates a new mock instance.
func NewMockOperationIDGenerator(ctrl *gomock.Controller) *MockOperationIDGenerator {
	mock := &MockOperationIDGenerator{ctrl: ctrl}
	mock.recorder = &MockOperationIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationIDGenerator) EXPECT() *MockOperationIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockOperationIDGenerator) Generate() kernel.OperationID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(kernel.OperationID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockOperationIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockOperationIDGenerator)(nil).Generate))
}
