// Code generated by MockGen. DO NOT EDIT.
// Source: room_repository.go
//
// Generated by this command:
//
//	mockgen -source=room_repository.go -destination=./mocks/mock_room_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/roomship/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomRepository is a mock of RoomRepository interface.
type MockRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomRepositoryMockRecorder is the mock recorder for MockRoomRepository.
type MockRoomRepositoryMockRecorder struct {
	mock *MockRoomRepository
}

// NewMockRoomRepository creates a new mock instance.
func NewMockRoomRepository(ctrl *gomock.Controller) *MockRoomRepository {
	mock := &MockRoomRepository{ctrl: ctrl}
	mock.recorder = &MockRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepository) EXPECT() *MockRoomRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomRepository) Create(ctx context.Context, room *domain.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomRepositoryMockRecorder) Create(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomRepository)(nil).Create), ctx, room)
}

// FindByID mocks base method.
func (m *MockRoomRepository) FindByID(ctx context.Context, id kernel.RoomID) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoomRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoomRepository)(nil).FindByID), ctx, id)
}

// FindByNumber mocks base method.
func (m *MockRoomRepository) FindByNumber(ctx context.Context, number kernel.RoomNumber) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNumber", ctx, number)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNumber indicates an expected call of FindByNumber.
func (mr *MockRoomRepositoryMockRecorder) FindByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNumber", reflect.TypeOf((*MockRoomRepository)(nil).FindByNumber), ctx, number)
}

// Update mocks base method.
func (m *MockRoomRepository) Update(ctx context.Context, room *domain.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoomRepositoryMockRecorder) Update(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoomRepository)(nil).Update), ctx, room)
}

// MockRoomCreator is a mock of RoomCreator interface.
type MockRoomCreator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomCreatorMockRecorder
	isgomock struct{}
}

// MockRoomCreatorMockRecorder is the mock recorder for MockRoomCreator.
type MockRoomCreatorMockRecorder struct {
	mock *MockRoomCreator
}

// NewMockRoomCreator creates a new mock instance.
func NewMockRoomCreator(ctrl *gomock.Controller) *MockRoomCreator {
	mock := &MockRoomCreator{ctrl: ctrl}
	mock.recorder = &MockRoomCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomCreator) EXPECT() *MockRoomCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomCreator) Create(ctx context.Context, room *domain.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomCreatorMockRecorder) Create(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomCreator)(nil).Create), ctx, room)
}

// MockRoomUpdater is a mock of RoomUpdater interface.
type MockRoomUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockRoomUpdaterMockRecorder
	isgomock struct{}
}

// MockRoomUpdaterMockRecorder is the mock recorder for MockRoomUpdater.
type MockRoomUpdaterMockRecorder struct {
	mock *MockRoomUpdater
}

// NewMockRoomUpdater creates a new mock instance.
func NewMockRoomUpdater(ctrl *gomock.Controller) *MockRoomUpdater {
	mock := &MockRoomUpdater{ctrl: ctrl}
	mock.recorder = &MockRoomUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomUpdater) EXPECT() *MockRoomUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockRoomUpdater) Update(ctx context.Context, room *domain.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoomUpdaterMockRecorder) Update(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoomUpdater)(nil).Update), ctx, room)
}

// MockRoomFinderByNumber is a mock of RoomFinderByNumber interface.
type MockRoomFinderByNumber struct {
	ctrl     *gomock.Controller
	recorder *MockRoomFinderByNumberMockRecorder
	isgomock struct{}
}

// MockRoomFinderByNumberMockRecorder is the mock recorder for MockRoomFinderByNumber.
type MockRoomFinderByNumberMockRecorder struct {
	mock *MockRoomFinderByNumber
}

// NewMockRoomFinderByNumber creates a new mock instance.
func NewMockRoomFinderByNumber(ctrl *gomock.Controller) *MockRoomFinderByNumber {
	mock := &MockRoomFinderByNumber{ctrl: ctrl}
	mock.recorder = &MockRoomFinderByNumberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomFinderByNumber) EXPECT() *MockRoomFinderByNumberMockRecorder {
	return m.recorder
}

// FindByNumber mocks base method.
func (m *MockRoomFinderByNumber) FindByNumber(ctx context.Context, number kernel.RoomNumber) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNumber", ctx, number)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNumber indicates an expected call of FindByNumber.
func (mr *MockRoomFinderByNumberMockRecorder) FindByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNumber", reflect.TypeOf((*MockRoomFinderByNumber)(nil).FindByNumber), ctx, number)
}

// MockRoomFinderByID is a mock of RoomFinderByID interface.
type MockRoomFinderByID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomFinderByIDMockRecorder
	isgomock struct{}
}

// MockRoomFinderByIDMockRecorder is the mock recorder for MockRoomFinderByID.
type MockRoomFinderByIDMockRecorder struct {
	mock *MockRoomFinderByID
}

// NewMockRoomFinderByID creates a new mock instance.
func NewMockRoomFinderByID(ctrl *gomock.Controller) *MockRoomFinderByID {
	mock := &MockRoomFinderByID{ctrl: ctrl}
	mock.recorder = &MockRoomFinderByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomFinderByID) EXPECT() *MockRoomFinderByIDMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockRoomFinderByID) FindByID(ctx context.Context, id kernel.RoomID) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoomFinderByIDMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoomFinderByID)(nil).FindByID), ctx, id)
}
