// Code generated by MockGen. DO NOT EDIT.
// Source: roomship_repository.go
//
// Generated by this command:
//
//	mockgen -source=roomship_repository.go -destination=./mocks/mock_roomship_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/roomship/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomshipRepository is a mock of RoomshipRepository interface.
type MockRoomshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomshipRepositoryMockRecorder is the mock recorder for MockRoomshipRepository.
type MockRoomshipRepositoryMockRecorder struct {
	mock *MockRoomshipRepository
}

// NewMockRoomshipRepository creates a new mock instance.
func NewMockRoomshipRepository(ctrl *gomock.Controller) *MockRoomshipRepository {
	mock := &MockRoomshipRepository{ctrl: ctrl}
	mock.recorder = &MockRoomshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipRepository) EXPECT() *MockRoomshipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomshipRepository) Create(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomshipRepositoryMockRecorder) Create(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomshipRepository)(nil).Create), ctx, roomship)
}

// ExistByUserIDAndRoomID mocks base method.
func (m *MockRoomshipRepository) ExistByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomID indicates an expected call of ExistByUserIDAndRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) ExistByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).ExistByUserIDAndRoomID), ctx, userID, roomID)
}

// FindByID mocks base method.
func (m *MockRoomshipRepository) FindByID(ctx context.Context, id domain.RoomshipID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoomshipRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindByID), ctx, id)
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipRepository) FindByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) FindByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindByUserIDAndRoomID), ctx, userID, roomID)
}

// FindsByRoomID mocks base method.
func (m *MockRoomshipRepository) FindsByRoomID(ctx context.Context, id kernel.RoomID) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomID", ctx, id)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomID indicates an expected call of FindsByRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) FindsByRoomID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindsByRoomID), ctx, id)
}

// FindsByRoomIDAndRole mocks base method.
func (m *MockRoomshipRepository) FindsByRoomIDAndRole(ctx context.Context, roomID kernel.RoomID, role domain.RoomshipRole) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomIDAndRole", ctx, roomID, role)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomIDAndRole indicates an expected call of FindsByRoomIDAndRole.
func (mr *MockRoomshipRepositoryMockRecorder) FindsByRoomIDAndRole(ctx, roomID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomIDAndRole", reflect.TypeOf((*MockRoomshipRepository)(nil).FindsByRoomIDAndRole), ctx, roomID, role)
}

// MockRoomshipCreator is a mock of RoomshipCreator interface.
type MockRoomshipCreator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipCreatorMockRecorder
	isgomock struct{}
}

// MockRoomshipCreatorMockRecorder is the mock recorder for MockRoomshipCreator.
type MockRoomshipCreatorMockRecorder struct {
	mock *MockRoomshipCreator
}

// NewMockRoomshipCreator creates a new mock instance.
func NewMockRoomshipCreator(ctrl *gomock.Controller) *MockRoomshipCreator {
	mock := &MockRoomshipCreator{ctrl: ctrl}
	mock.recorder = &MockRoomshipCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipCreator) EXPECT() *MockRoomshipCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomshipCreator) Create(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomshipCreatorMockRecorder) Create(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomshipCreator)(nil).Create), ctx, roomship)
}

// MockRoomshipFinderByID is a mock of RoomshipFinderByID interface.
type MockRoomshipFinderByID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipFinderByIDMockRecorder
	isgomock struct{}
}

// MockRoomshipFinderByIDMockRecorder is the mock recorder for MockRoomshipFinderByID.
type MockRoomshipFinderByIDMockRecorder struct {
	mock *MockRoomshipFinderByID
}

// NewMockRoomshipFinderByID creates a new mock instance.
func NewMockRoomshipFinderByID(ctrl *gomock.Controller) *MockRoomshipFinderByID {
	mock := &MockRoomshipFinderByID{ctrl: ctrl}
	mock.recorder = &MockRoomshipFinderByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipFinderByID) EXPECT() *MockRoomshipFinderByIDMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockRoomshipFinderByID) FindByID(ctx context.Context, id domain.RoomshipID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoomshipFinderByIDMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoomshipFinderByID)(nil).FindByID), ctx, id)
}

// MockRoomshipsFinderByRoomID is a mock of RoomshipsFinderByRoomID interface.
type MockRoomshipsFinderByRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipsFinderByRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipsFinderByRoomIDMockRecorder is the mock recorder for MockRoomshipsFinderByRoomID.
type MockRoomshipsFinderByRoomIDMockRecorder struct {
	mock *MockRoomshipsFinderByRoomID
}

// NewMockRoomshipsFinderByRoomID creates a new mock instance.
func NewMockRoomshipsFinderByRoomID(ctrl *gomock.Controller) *MockRoomshipsFinderByRoomID {
	mock := &MockRoomshipsFinderByRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipsFinderByRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipsFinderByRoomID) EXPECT() *MockRoomshipsFinderByRoomIDMockRecorder {
	return m.recorder
}

// FindsByRoomID mocks base method.
func (m *MockRoomshipsFinderByRoomID) FindsByRoomID(ctx context.Context, id kernel.RoomID) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomID", ctx, id)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomID indicates an expected call of FindsByRoomID.
func (mr *MockRoomshipsFinderByRoomIDMockRecorder) FindsByRoomID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomID", reflect.TypeOf((*MockRoomshipsFinderByRoomID)(nil).FindsByRoomID), ctx, id)
}

// MockRoomshipsFinderByRoomIDAndRole is a mock of RoomshipsFinderByRoomIDAndRole interface.
type MockRoomshipsFinderByRoomIDAndRole struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipsFinderByRoomIDAndRoleMockRecorder
	isgomock struct{}
}

// MockRoomshipsFinderByRoomIDAndRoleMockRecorder is the mock recorder for MockRoomshipsFinderByRoomIDAndRole.
type MockRoomshipsFinderByRoomIDAndRoleMockRecorder struct {
	mock *MockRoomshipsFinderByRoomIDAndRole
}

// NewMockRoomshipsFinderByRoomIDAndRole creates a new mock instance.
func NewMockRoomshipsFinderByRoomIDAndRole(ctrl *gomock.Controller) *MockRoomshipsFinderByRoomIDAndRole {
	mock := &MockRoomshipsFinderByRoomIDAndRole{ctrl: ctrl}
	mock.recorder = &MockRoomshipsFinderByRoomIDAndRoleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipsFinderByRoomIDAndRole) EXPECT() *MockRoomshipsFinderByRoomIDAndRoleMockRecorder {
	return m.recorder
}

// FindsByRoomIDAndRole mocks base method.
func (m *MockRoomshipsFinderByRoomIDAndRole) FindsByRoomIDAndRole(ctx context.Context, roomID kernel.RoomID, role domain.RoomshipRole) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByRoomIDAndRole", ctx, roomID, role)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByRoomIDAndRole indicates an expected call of FindsByRoomIDAndRole.
func (mr *MockRoomshipsFinderByRoomIDAndRoleMockRecorder) FindsByRoomIDAndRole(ctx, roomID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByRoomIDAndRole", reflect.TypeOf((*MockRoomshipsFinderByRoomIDAndRole)(nil).FindsByRoomIDAndRole), ctx, roomID, role)
}

// MockRoomshipFinderByUserIDAndRoomID is a mock of RoomshipFinderByUserIDAndRoomID interface.
type MockRoomshipFinderByUserIDAndRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipFinderByUserIDAndRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipFinderByUserIDAndRoomIDMockRecorder is the mock recorder for MockRoomshipFinderByUserIDAndRoomID.
type MockRoomshipFinderByUserIDAndRoomIDMockRecorder struct {
	mock *MockRoomshipFinderByUserIDAndRoomID
}

// NewMockRoomshipFinderByUserIDAndRoomID creates a new mock instance.
func NewMockRoomshipFinderByUserIDAndRoomID(ctrl *gomock.Controller) *MockRoomshipFinderByUserIDAndRoomID {
	mock := &MockRoomshipFinderByUserIDAndRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipFinderByUserIDAndRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipFinderByUserIDAndRoomID) EXPECT() *MockRoomshipFinderByUserIDAndRoomIDMockRecorder {
	return m.recorder
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipFinderByUserIDAndRoomID) FindByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipFinderByUserIDAndRoomIDMockRecorder) FindByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipFinderByUserIDAndRoomID)(nil).FindByUserIDAndRoomID), ctx, userID, roomID)
}

// MockRoomshipExisterByUserIDAndRoomID is a mock of RoomshipExisterByUserIDAndRoomID interface.
type MockRoomshipExisterByUserIDAndRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipExisterByUserIDAndRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipExisterByUserIDAndRoomIDMockRecorder is the mock recorder for MockRoomshipExisterByUserIDAndRoomID.
type MockRoomshipExisterByUserIDAndRoomIDMockRecorder struct {
	mock *MockRoomshipExisterByUserIDAndRoomID
}

// NewMockRoomshipExisterByUserIDAndRoomID creates a new mock instance.
func NewMockRoomshipExisterByUserIDAndRoomID(ctrl *gomock.Controller) *MockRoomshipExisterByUserIDAndRoomID {
	mock := &MockRoomshipExisterByUserIDAndRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipExisterByUserIDAndRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipExisterByUserIDAndRoomID) EXPECT() *MockRoomshipExisterByUserIDAndRoomIDMockRecorder {
	return m.recorder
}

// ExistByUserIDAndRoomID mocks base method.
func (m *MockRoomshipExisterByUserIDAndRoomID) ExistByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomID indicates an expected call of ExistByUserIDAndRoomID.
func (mr *MockRoomshipExisterByUserIDAndRoomIDMockRecorder) ExistByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipExisterByUserIDAndRoomID)(nil).ExistByUserIDAndRoomID), ctx, userID, roomID)
}

// MockRoomshipsFinderByUserID is a mock of RoomshipsFinderByUserID interface.
type MockRoomshipsFinderByUserID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipsFinderByUserIDMockRecorder
	isgomock struct{}
}

// MockRoomshipsFinderByUserIDMockRecorder is the mock recorder for MockRoomshipsFinderByUserID.
type MockRoomshipsFinderByUserIDMockRecorder struct {
	mock *MockRoomshipsFinderByUserID
}

// NewMockRoomshipsFinderByUserID creates a new mock instance.
func NewMockRoomshipsFinderByUserID(ctrl *gomock.Controller) *MockRoomshipsFinderByUserID {
	mock := &MockRoomshipsFinderByUserID{ctrl: ctrl}
	mock.recorder = &MockRoomshipsFinderByUserIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipsFinderByUserID) EXPECT() *MockRoomshipsFinderByUserIDMockRecorder {
	return m.recorder
}

// FindsByUserID mocks base method.
func (m *MockRoomshipsFinderByUserID) FindsByUserID(ctx context.Context, userID kernel.UserID, limit int, baseID domain.RoomshipID) ([]*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserID", ctx, userID, limit, baseID)
	ret0, _ := ret[0].([]*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserID indicates an expected call of FindsByUserID.
func (mr *MockRoomshipsFinderByUserIDMockRecorder) FindsByUserID(ctx, userID, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserID", reflect.TypeOf((*MockRoomshipsFinderByUserID)(nil).FindsByUserID), ctx, userID, limit, baseID)
}
