// Code generated by MockGen. DO NOT EDIT.
// Source: roomship_repository.go
//
// Generated by this command:
//
//	mockgen -source=roomship_repository.go -destination=./mocks/mock_roomship_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/roomship/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomshipRepository is a mock of RoomshipRepository interface.
type MockRoomshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomshipRepositoryMockRecorder is the mock recorder for MockRoomshipRepository.
type MockRoomshipRepositoryMockRecorder struct {
	mock *MockRoomshipRepository
}

// NewMockRoomshipRepository creates a new mock instance.
func NewMockRoomshipRepository(ctrl *gomock.Controller) *MockRoomshipRepository {
	mock := &MockRoomshipRepository{ctrl: ctrl}
	mock.recorder = &MockRoomshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipRepository) EXPECT() *MockRoomshipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomshipRepository) Create(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomshipRepositoryMockRecorder) Create(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomshipRepository)(nil).Create), ctx, roomship)
}

// ExistByUserIDAndRoomID mocks base method.
func (m *MockRoomshipRepository) ExistByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomID indicates an expected call of ExistByUserIDAndRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) ExistByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).ExistByUserIDAndRoomID), ctx, userID, roomID)
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipRepository) FindByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipRepositoryMockRecorder) FindByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipRepository)(nil).FindByUserIDAndRoomID), ctx, userID, roomID)
}

// MockRoomshipCreator is a mock of RoomshipCreator interface.
type MockRoomshipCreator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipCreatorMockRecorder
	isgomock struct{}
}

// MockRoomshipCreatorMockRecorder is the mock recorder for MockRoomshipCreator.
type MockRoomshipCreatorMockRecorder struct {
	mock *MockRoomshipCreator
}

// NewMockRoomshipCreator creates a new mock instance.
func NewMockRoomshipCreator(ctrl *gomock.Controller) *MockRoomshipCreator {
	mock := &MockRoomshipCreator{ctrl: ctrl}
	mock.recorder = &MockRoomshipCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipCreator) EXPECT() *MockRoomshipCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoomshipCreator) Create(ctx context.Context, roomship *domain.Roomship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, roomship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoomshipCreatorMockRecorder) Create(ctx, roomship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoomshipCreator)(nil).Create), ctx, roomship)
}

// MockRoomshipFinderByUserIDAndRoomID is a mock of RoomshipFinderByUserIDAndRoomID interface.
type MockRoomshipFinderByUserIDAndRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipFinderByUserIDAndRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipFinderByUserIDAndRoomIDMockRecorder is the mock recorder for MockRoomshipFinderByUserIDAndRoomID.
type MockRoomshipFinderByUserIDAndRoomIDMockRecorder struct {
	mock *MockRoomshipFinderByUserIDAndRoomID
}

// NewMockRoomshipFinderByUserIDAndRoomID creates a new mock instance.
func NewMockRoomshipFinderByUserIDAndRoomID(ctrl *gomock.Controller) *MockRoomshipFinderByUserIDAndRoomID {
	mock := &MockRoomshipFinderByUserIDAndRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipFinderByUserIDAndRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipFinderByUserIDAndRoomID) EXPECT() *MockRoomshipFinderByUserIDAndRoomIDMockRecorder {
	return m.recorder
}

// FindByUserIDAndRoomID mocks base method.
func (m *MockRoomshipFinderByUserIDAndRoomID) FindByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (*domain.Roomship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(*domain.Roomship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndRoomID indicates an expected call of FindByUserIDAndRoomID.
func (mr *MockRoomshipFinderByUserIDAndRoomIDMockRecorder) FindByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipFinderByUserIDAndRoomID)(nil).FindByUserIDAndRoomID), ctx, userID, roomID)
}

// MockRoomshipExisterByUserIDAndRoomID is a mock of RoomshipExisterByUserIDAndRoomID interface.
type MockRoomshipExisterByUserIDAndRoomID struct {
	ctrl     *gomock.Controller
	recorder *MockRoomshipExisterByUserIDAndRoomIDMockRecorder
	isgomock struct{}
}

// MockRoomshipExisterByUserIDAndRoomIDMockRecorder is the mock recorder for MockRoomshipExisterByUserIDAndRoomID.
type MockRoomshipExisterByUserIDAndRoomIDMockRecorder struct {
	mock *MockRoomshipExisterByUserIDAndRoomID
}

// NewMockRoomshipExisterByUserIDAndRoomID creates a new mock instance.
func NewMockRoomshipExisterByUserIDAndRoomID(ctrl *gomock.Controller) *MockRoomshipExisterByUserIDAndRoomID {
	mock := &MockRoomshipExisterByUserIDAndRoomID{ctrl: ctrl}
	mock.recorder = &MockRoomshipExisterByUserIDAndRoomIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomshipExisterByUserIDAndRoomID) EXPECT() *MockRoomshipExisterByUserIDAndRoomIDMockRecorder {
	return m.recorder
}

// ExistByUserIDAndRoomID mocks base method.
func (m *MockRoomshipExisterByUserIDAndRoomID) ExistByUserIDAndRoomID(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomID", ctx, userID, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomID indicates an expected call of ExistByUserIDAndRoomID.
func (mr *MockRoomshipExisterByUserIDAndRoomIDMockRecorder) ExistByUserIDAndRoomID(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomID", reflect.TypeOf((*MockRoomshipExisterByUserIDAndRoomID)(nil).ExistByUserIDAndRoomID), ctx, userID, roomID)
}
