// Code generated by MockGen. DO NOT EDIT.
// Source: member_request_repository.go
//
// Generated by this command:
//
//	mockgen -source=member_request_repository.go -destination=./mocks/mock_member_request_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/roomship/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMemberRequestRepository is a mock of MemberRequestRepository interface.
type MockMemberRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockMemberRequestRepositoryMockRecorder is the mock recorder for MockMemberRequestRepository.
type MockMemberRequestRepositoryMockRecorder struct {
	mock *MockMemberRequestRepository
}

// NewMockMemberRequestRepository creates a new mock instance.
func NewMockMemberRequestRepository(ctrl *gomock.Controller) *MockMemberRequestRepository {
	mock := &MockMemberRequestRepository{ctrl: ctrl}
	mock.recorder = &MockMemberRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRequestRepository) EXPECT() *MockMemberRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMemberRequestRepository) Create(ctx context.Context, memberRequest *domain.MemberRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, memberRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMemberRequestRepositoryMockRecorder) Create(ctx, memberRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMemberRequestRepository)(nil).Create), ctx, memberRequest)
}

// ExistByUserIDAndRoomIDAndState mocks base method.
func (m *MockMemberRequestRepository) ExistByUserIDAndRoomIDAndState(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID, state domain.MemberRequestState) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomIDAndState", ctx, userID, roomID, state)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomIDAndState indicates an expected call of ExistByUserIDAndRoomIDAndState.
func (mr *MockMemberRequestRepositoryMockRecorder) ExistByUserIDAndRoomIDAndState(ctx, userID, roomID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomIDAndState", reflect.TypeOf((*MockMemberRequestRepository)(nil).ExistByUserIDAndRoomIDAndState), ctx, userID, roomID, state)
}

// FindByID mocks base method.
func (m *MockMemberRequestRepository) FindByID(ctx context.Context, requestID kernel.OperationID) (*domain.MemberRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, requestID)
	ret0, _ := ret[0].(*domain.MemberRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMemberRequestRepositoryMockRecorder) FindByID(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMemberRequestRepository)(nil).FindByID), ctx, requestID)
}

// FindsByUserID mocks base method.
func (m *MockMemberRequestRepository) FindsByUserID(ctx context.Context, userID kernel.UserID, limit int, baseID kernel.OperationID) ([]*domain.MemberRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserID", ctx, userID, limit, baseID)
	ret0, _ := ret[0].([]*domain.MemberRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserID indicates an expected call of FindsByUserID.
func (mr *MockMemberRequestRepositoryMockRecorder) FindsByUserID(ctx, userID, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserID", reflect.TypeOf((*MockMemberRequestRepository)(nil).FindsByUserID), ctx, userID, limit, baseID)
}

// Update mocks base method.
func (m *MockMemberRequestRepository) Update(ctx context.Context, memberRequest *domain.MemberRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, memberRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMemberRequestRepositoryMockRecorder) Update(ctx, memberRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMemberRequestRepository)(nil).Update), ctx, memberRequest)
}

// MockMemberRequestCreator is a mock of MemberRequestCreator interface.
type MockMemberRequestCreator struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRequestCreatorMockRecorder
	isgomock struct{}
}

// MockMemberRequestCreatorMockRecorder is the mock recorder for MockMemberRequestCreator.
type MockMemberRequestCreatorMockRecorder struct {
	mock *MockMemberRequestCreator
}

// NewMockMemberRequestCreator creates a new mock instance.
func NewMockMemberRequestCreator(ctrl *gomock.Controller) *MockMemberRequestCreator {
	mock := &MockMemberRequestCreator{ctrl: ctrl}
	mock.recorder = &MockMemberRequestCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRequestCreator) EXPECT() *MockMemberRequestCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMemberRequestCreator) Create(ctx context.Context, memberRequest *domain.MemberRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, memberRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMemberRequestCreatorMockRecorder) Create(ctx, memberRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMemberRequestCreator)(nil).Create), ctx, memberRequest)
}

// MockMemberRequestUpdater is a mock of MemberRequestUpdater interface.
type MockMemberRequestUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRequestUpdaterMockRecorder
	isgomock struct{}
}

// MockMemberRequestUpdaterMockRecorder is the mock recorder for MockMemberRequestUpdater.
type MockMemberRequestUpdaterMockRecorder struct {
	mock *MockMemberRequestUpdater
}

// NewMockMemberRequestUpdater creates a new mock instance.
func NewMockMemberRequestUpdater(ctrl *gomock.Controller) *MockMemberRequestUpdater {
	mock := &MockMemberRequestUpdater{ctrl: ctrl}
	mock.recorder = &MockMemberRequestUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRequestUpdater) EXPECT() *MockMemberRequestUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockMemberRequestUpdater) Update(ctx context.Context, memberRequest *domain.MemberRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, memberRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMemberRequestUpdaterMockRecorder) Update(ctx, memberRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMemberRequestUpdater)(nil).Update), ctx, memberRequest)
}

// MockMemberRequestFinderByID is a mock of MemberRequestFinderByID interface.
type MockMemberRequestFinderByID struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRequestFinderByIDMockRecorder
	isgomock struct{}
}

// MockMemberRequestFinderByIDMockRecorder is the mock recorder for MockMemberRequestFinderByID.
type MockMemberRequestFinderByIDMockRecorder struct {
	mock *MockMemberRequestFinderByID
}

// NewMockMemberRequestFinderByID creates a new mock instance.
func NewMockMemberRequestFinderByID(ctrl *gomock.Controller) *MockMemberRequestFinderByID {
	mock := &MockMemberRequestFinderByID{ctrl: ctrl}
	mock.recorder = &MockMemberRequestFinderByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRequestFinderByID) EXPECT() *MockMemberRequestFinderByIDMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockMemberRequestFinderByID) FindByID(ctx context.Context, requestID kernel.OperationID) (*domain.MemberRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, requestID)
	ret0, _ := ret[0].(*domain.MemberRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMemberRequestFinderByIDMockRecorder) FindByID(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMemberRequestFinderByID)(nil).FindByID), ctx, requestID)
}

// MockMemberRequestExisterByUserIDAndRoomIDAndState is a mock of MemberRequestExisterByUserIDAndRoomIDAndState interface.
type MockMemberRequestExisterByUserIDAndRoomIDAndState struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRequestExisterByUserIDAndRoomIDAndStateMockRecorder
	isgomock struct{}
}

// MockMemberRequestExisterByUserIDAndRoomIDAndStateMockRecorder is the mock recorder for MockMemberRequestExisterByUserIDAndRoomIDAndState.
type MockMemberRequestExisterByUserIDAndRoomIDAndStateMockRecorder struct {
	mock *MockMemberRequestExisterByUserIDAndRoomIDAndState
}

// NewMockMemberRequestExisterByUserIDAndRoomIDAndState creates a new mock instance.
func NewMockMemberRequestExisterByUserIDAndRoomIDAndState(ctrl *gomock.Controller) *MockMemberRequestExisterByUserIDAndRoomIDAndState {
	mock := &MockMemberRequestExisterByUserIDAndRoomIDAndState{ctrl: ctrl}
	mock.recorder = &MockMemberRequestExisterByUserIDAndRoomIDAndStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRequestExisterByUserIDAndRoomIDAndState) EXPECT() *MockMemberRequestExisterByUserIDAndRoomIDAndStateMockRecorder {
	return m.recorder
}

// ExistByUserIDAndRoomIDAndState mocks base method.
func (m *MockMemberRequestExisterByUserIDAndRoomIDAndState) ExistByUserIDAndRoomIDAndState(ctx context.Context, userID kernel.UserID, roomID kernel.RoomID, state domain.MemberRequestState) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByUserIDAndRoomIDAndState", ctx, userID, roomID, state)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByUserIDAndRoomIDAndState indicates an expected call of ExistByUserIDAndRoomIDAndState.
func (mr *MockMemberRequestExisterByUserIDAndRoomIDAndStateMockRecorder) ExistByUserIDAndRoomIDAndState(ctx, userID, roomID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByUserIDAndRoomIDAndState", reflect.TypeOf((*MockMemberRequestExisterByUserIDAndRoomIDAndState)(nil).ExistByUserIDAndRoomIDAndState), ctx, userID, roomID, state)
}

// MockMemberRequestsFinderByUserID is a mock of MemberRequestsFinderByUserID interface.
type MockMemberRequestsFinderByUserID struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRequestsFinderByUserIDMockRecorder
	isgomock struct{}
}

// MockMemberRequestsFinderByUserIDMockRecorder is the mock recorder for MockMemberRequestsFinderByUserID.
type MockMemberRequestsFinderByUserIDMockRecorder struct {
	mock *MockMemberRequestsFinderByUserID
}

// NewMockMemberRequestsFinderByUserID creates a new mock instance.
func NewMockMemberRequestsFinderByUserID(ctrl *gomock.Controller) *MockMemberRequestsFinderByUserID {
	mock := &MockMemberRequestsFinderByUserID{ctrl: ctrl}
	mock.recorder = &MockMemberRequestsFinderByUserIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRequestsFinderByUserID) EXPECT() *MockMemberRequestsFinderByUserIDMockRecorder {
	return m.recorder
}

// FindsByUserID mocks base method.
func (m *MockMemberRequestsFinderByUserID) FindsByUserID(ctx context.Context, userID kernel.UserID, limit int, baseID kernel.OperationID) ([]*domain.MemberRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindsByUserID", ctx, userID, limit, baseID)
	ret0, _ := ret[0].([]*domain.MemberRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindsByUserID indicates an expected call of FindsByUserID.
func (mr *MockMemberRequestsFinderByUserIDMockRecorder) FindsByUserID(ctx, userID, limit, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindsByUserID", reflect.TypeOf((*MockMemberRequestsFinderByUserID)(nil).FindsByUserID), ctx, userID, limit, baseID)
}
