// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=./mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	event "gochat/internal/shared/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateDeadLetter mocks base method.
func (m *MockRepository) CreateDeadLetter(ctx context.Context, e event.Event, reason error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeadLetter", ctx, e, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeadLetter indicates an expected call of CreateDeadLetter.
func (mr *MockRepositoryMockRecorder) CreateDeadLetter(ctx, e, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeadLetter", reflect.TypeOf((*MockRepository)(nil).CreateDeadLetter), ctx, e, reason)
}

// CreateUnpublishedEvents mocks base method.
func (m *MockRepository) CreateUnpublishedEvents(ctx context.Context, evs []event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUnpublishedEvents", ctx, evs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUnpublishedEvents indicates an expected call of CreateUnpublishedEvents.
func (mr *MockRepositoryMockRecorder) CreateUnpublishedEvents(ctx, evs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUnpublishedEvents", reflect.TypeOf((*MockRepository)(nil).CreateUnpublishedEvents), ctx, evs)
}

// ListUnpublishedEvents mocks base method.
func (m *MockRepository) ListUnpublishedEvents(ctx context.Context) ([]event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublishedEvents", ctx)
	ret0, _ := ret[0].([]event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublishedEvents indicates an expected call of ListUnpublishedEvents.
func (mr *MockRepositoryMockRecorder) ListUnpublishedEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublishedEvents", reflect.TypeOf((*MockRepository)(nil).ListUnpublishedEvents), ctx)
}

// MarkAsNotProcessing mocks base method.
func (m *MockRepository) MarkAsNotProcessing(ctx context.Context, ID event.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsNotProcessing", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsNotProcessing indicates an expected call of MarkAsNotProcessing.
func (mr *MockRepositoryMockRecorder) MarkAsNotProcessing(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsNotProcessing", reflect.TypeOf((*MockRepository)(nil).MarkAsNotProcessing), ctx, ID)
}

// MarkAsPublishedAndNotProcessing mocks base method.
func (m *MockRepository) MarkAsPublishedAndNotProcessing(ctx context.Context, ID event.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPublishedAndNotProcessing", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPublishedAndNotProcessing indicates an expected call of MarkAsPublishedAndNotProcessing.
func (mr *MockRepositoryMockRecorder) MarkAsPublishedAndNotProcessing(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPublishedAndNotProcessing", reflect.TypeOf((*MockRepository)(nil).MarkAsPublishedAndNotProcessing), ctx, ID)
}

// MockUnpublishedEventsCreator is a mock of UnpublishedEventsCreator interface.
type MockUnpublishedEventsCreator struct {
	ctrl     *gomock.Controller
	recorder *MockUnpublishedEventsCreatorMockRecorder
	isgomock struct{}
}

// MockUnpublishedEventsCreatorMockRecorder is the mock recorder for MockUnpublishedEventsCreator.
type MockUnpublishedEventsCreatorMockRecorder struct {
	mock *MockUnpublishedEventsCreator
}

// NewMockUnpublishedEventsCreator creates a new mock instance.
func NewMockUnpublishedEventsCreator(ctrl *gomock.Controller) *MockUnpublishedEventsCreator {
	mock := &MockUnpublishedEventsCreator{ctrl: ctrl}
	mock.recorder = &MockUnpublishedEventsCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnpublishedEventsCreator) EXPECT() *MockUnpublishedEventsCreatorMockRecorder {
	return m.recorder
}

// CreateUnpublishedEvents mocks base method.
func (m *MockUnpublishedEventsCreator) CreateUnpublishedEvents(ctx context.Context, evs []event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUnpublishedEvents", ctx, evs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUnpublishedEvents indicates an expected call of CreateUnpublishedEvents.
func (mr *MockUnpublishedEventsCreatorMockRecorder) CreateUnpublishedEvents(ctx, evs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUnpublishedEvents", reflect.TypeOf((*MockUnpublishedEventsCreator)(nil).CreateUnpublishedEvents), ctx, evs)
}

// MockUnpublishedEventsLister is a mock of UnpublishedEventsLister interface.
type MockUnpublishedEventsLister struct {
	ctrl     *gomock.Controller
	recorder *MockUnpublishedEventsListerMockRecorder
	isgomock struct{}
}

// MockUnpublishedEventsListerMockRecorder is the mock recorder for MockUnpublishedEventsLister.
type MockUnpublishedEventsListerMockRecorder struct {
	mock *MockUnpublishedEventsLister
}

// NewMockUnpublishedEventsLister creates a new mock instance.
func NewMockUnpublishedEventsLister(ctrl *gomock.Controller) *MockUnpublishedEventsLister {
	mock := &MockUnpublishedEventsLister{ctrl: ctrl}
	mock.recorder = &MockUnpublishedEventsListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnpublishedEventsLister) EXPECT() *MockUnpublishedEventsListerMockRecorder {
	return m.recorder
}

// ListUnpublishedEvents mocks base method.
func (m *MockUnpublishedEventsLister) ListUnpublishedEvents(ctx context.Context) ([]event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublishedEvents", ctx)
	ret0, _ := ret[0].([]event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublishedEvents indicates an expected call of ListUnpublishedEvents.
func (mr *MockUnpublishedEventsListerMockRecorder) ListUnpublishedEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublishedEvents", reflect.TypeOf((*MockUnpublishedEventsLister)(nil).ListUnpublishedEvents), ctx)
}

// MockPublishedAndNotProcessingMarker is a mock of PublishedAndNotProcessingMarker interface.
type MockPublishedAndNotProcessingMarker struct {
	ctrl     *gomock.Controller
	recorder *MockPublishedAndNotProcessingMarkerMockRecorder
	isgomock struct{}
}

// MockPublishedAndNotProcessingMarkerMockRecorder is the mock recorder for MockPublishedAndNotProcessingMarker.
type MockPublishedAndNotProcessingMarkerMockRecorder struct {
	mock *MockPublishedAndNotProcessingMarker
}

// NewMockPublishedAndNotProcessingMarker creates a new mock instance.
func NewMockPublishedAndNotProcessingMarker(ctrl *gomock.Controller) *MockPublishedAndNotProcessingMarker {
	mock := &MockPublishedAndNotProcessingMarker{ctrl: ctrl}
	mock.recorder = &MockPublishedAndNotProcessingMarkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublishedAndNotProcessingMarker) EXPECT() *MockPublishedAndNotProcessingMarkerMockRecorder {
	return m.recorder
}

// MarkAsPublishedAndNotProcessing mocks base method.
func (m *MockPublishedAndNotProcessingMarker) MarkAsPublishedAndNotProcessing(ctx context.Context, ID event.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPublishedAndNotProcessing", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPublishedAndNotProcessing indicates an expected call of MarkAsPublishedAndNotProcessing.
func (mr *MockPublishedAndNotProcessingMarkerMockRecorder) MarkAsPublishedAndNotProcessing(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPublishedAndNotProcessing", reflect.TypeOf((*MockPublishedAndNotProcessingMarker)(nil).MarkAsPublishedAndNotProcessing), ctx, ID)
}

// MockNotProcessingMarker is a mock of NotProcessingMarker interface.
type MockNotProcessingMarker struct {
	ctrl     *gomock.Controller
	recorder *MockNotProcessingMarkerMockRecorder
	isgomock struct{}
}

// MockNotProcessingMarkerMockRecorder is the mock recorder for MockNotProcessingMarker.
type MockNotProcessingMarkerMockRecorder struct {
	mock *MockNotProcessingMarker
}

// NewMockNotProcessingMarker creates a new mock instance.
func NewMockNotProcessingMarker(ctrl *gomock.Controller) *MockNotProcessingMarker {
	mock := &MockNotProcessingMarker{ctrl: ctrl}
	mock.recorder = &MockNotProcessingMarkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotProcessingMarker) EXPECT() *MockNotProcessingMarkerMockRecorder {
	return m.recorder
}

// MarkAsNotProcessing mocks base method.
func (m *MockNotProcessingMarker) MarkAsNotProcessing(ctx context.Context, ID event.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsNotProcessing", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsNotProcessing indicates an expected call of MarkAsNotProcessing.
func (mr *MockNotProcessingMarkerMockRecorder) MarkAsNotProcessing(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsNotProcessing", reflect.TypeOf((*MockNotProcessingMarker)(nil).MarkAsNotProcessing), ctx, ID)
}

// MockDeadLetterCreator is a mock of DeadLetterCreator interface.
type MockDeadLetterCreator struct {
	ctrl     *gomock.Controller
	recorder *MockDeadLetterCreatorMockRecorder
	isgomock struct{}
}

// MockDeadLetterCreatorMockRecorder is the mock recorder for MockDeadLetterCreator.
type MockDeadLetterCreatorMockRecorder struct {
	mock *MockDeadLetterCreator
}

// NewMockDeadLetterCreator creates a new mock instance.
func NewMockDeadLetterCreator(ctrl *gomock.Controller) *MockDeadLetterCreator {
	mock := &MockDeadLetterCreator{ctrl: ctrl}
	mock.recorder = &MockDeadLetterCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeadLetterCreator) EXPECT() *MockDeadLetterCreatorMockRecorder {
	return m.recorder
}

// CreateDeadLetter mocks base method.
func (m *MockDeadLetterCreator) CreateDeadLetter(ctx context.Context, e event.Event, reason error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeadLetter", ctx, e, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeadLetter indicates an expected call of CreateDeadLetter.
func (mr *MockDeadLetterCreatorMockRecorder) CreateDeadLetter(ctx, e, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeadLetter", reflect.TypeOf((*MockDeadLetterCreator)(nil).CreateDeadLetter), ctx, e, reason)
}
