// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	event "gochat/internal/shared/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAsyncPublisher is a mock of AsyncPublisher interface.
type MockAsyncPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncPublisherMockRecorder
	isgomock struct{}
}

// MockAsyncPublisherMockRecorder is the mock recorder for MockAsyncPublisher.
type MockAsyncPublisherMockRecorder struct {
	mock *MockAsyncPublisher
}

// NewMockAsyncPublisher creates a new mock instance.
func NewMockAsyncPublisher(ctrl *gomock.Controller) *MockAsyncPublisher {
	mock := &MockAsyncPublisher{ctrl: ctrl}
	mock.recorder = &MockAsyncPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncPublisher) EXPECT() *MockAsyncPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockAsyncPublisher) Publish(ctx context.Context, arg1 event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockAsyncPublisherMockRecorder) Publish(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAsyncPublisher)(nil).Publish), ctx, arg1)
}

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockIDGenerator) Generate() event.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(event.ID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockIDGenerator)(nil).Generate))
}
