// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=./mocks/mock_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	event "gochat/internal/shared/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAsyncPublisher is a mock of AsyncPublisher interface.
type MockAsyncPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncPublisherMockRecorder
	isgomock struct{}
}

// MockAsyncPublisherMockRecorder is the mock recorder for MockAsyncPublisher.
type MockAsyncPublisherMockRecorder struct {
	mock *MockAsyncPublisher
}

// NewMockAsyncPublisher creates a new mock instance.
func NewMockAsyncPublisher(ctrl *gomock.Controller) *MockAsyncPublisher {
	mock := &MockAsyncPublisher{ctrl: ctrl}
	mock.recorder = &MockAsyncPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncPublisher) EXPECT() *MockAsyncPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockAsyncPublisher) Publish(ctx context.Context, arg1 event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockAsyncPublisherMockRecorder) Publish(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAsyncPublisher)(nil).Publish), ctx, arg1)
}

// MockSyncPublisher is a mock of SyncPublisher interface.
type MockSyncPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockSyncPublisherMockRecorder
	isgomock struct{}
}

// MockSyncPublisherMockRecorder is the mock recorder for MockSyncPublisher.
type MockSyncPublisherMockRecorder struct {
	mock *MockSyncPublisher
}

// NewMockSyncPublisher creates a new mock instance.
func NewMockSyncPublisher(ctrl *gomock.Controller) *MockSyncPublisher {
	mock := &MockSyncPublisher{ctrl: ctrl}
	mock.recorder = &MockSyncPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncPublisher) EXPECT() *MockSyncPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSyncPublisher) Publish(ctx context.Context, arg1 event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockSyncPublisherMockRecorder) Publish(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSyncPublisher)(nil).Publish), ctx, arg1)
}
