// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -source=event.go -destination=./mocks/mock_event.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	event "gochat/internal/shared/event"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// AddHeader mocks base method.
func (m *MockEvent) AddHeader(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeader", key, value)
}

// AddHeader indicates an expected call of AddHeader.
func (mr *MockEventMockRecorder) AddHeader(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeader", reflect.TypeOf((*MockEvent)(nil).AddHeader), key, value)
}

// AddHeaders mocks base method.
func (m *MockEvent) AddHeaders(headers map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeaders", headers)
}

// AddHeaders indicates an expected call of AddHeaders.
func (mr *MockEventMockRecorder) AddHeaders(headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeaders", reflect.TypeOf((*MockEvent)(nil).AddHeaders), headers)
}

// AggregateID mocks base method.
func (m *MockEvent) AggregateID() kernel.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateID")
	ret0, _ := ret[0].(kernel.ID)
	return ret0
}

// AggregateID indicates an expected call of AggregateID.
func (mr *MockEventMockRecorder) AggregateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateID", reflect.TypeOf((*MockEvent)(nil).AggregateID))
}

// Headers mocks base method.
func (m *MockEvent) Headers() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headers")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Headers indicates an expected call of Headers.
func (mr *MockEventMockRecorder) Headers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headers", reflect.TypeOf((*MockEvent)(nil).Headers))
}

// ID mocks base method.
func (m *MockEvent) ID() event.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(event.ID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockEventMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockEvent)(nil).ID))
}

// OccurredAt mocks base method.
func (m *MockEvent) OccurredAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OccurredAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// OccurredAt indicates an expected call of OccurredAt.
func (mr *MockEventMockRecorder) OccurredAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OccurredAt", reflect.TypeOf((*MockEvent)(nil).OccurredAt))
}

// Payload mocks base method.
func (m *MockEvent) Payload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Payload indicates an expected call of Payload.
func (mr *MockEventMockRecorder) Payload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockEvent)(nil).Payload))
}

// Topic mocks base method.
func (m *MockEvent) Topic() event.Topic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Topic")
	ret0, _ := ret[0].(event.Topic)
	return ret0
}

// Topic indicates an expected call of Topic.
func (mr *MockEventMockRecorder) Topic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Topic", reflect.TypeOf((*MockEvent)(nil).Topic))
}

// MockSpecificEvent is a mock of SpecificEvent interface.
type MockSpecificEvent struct {
	ctrl     *gomock.Controller
	recorder *MockSpecificEventMockRecorder
	isgomock struct{}
}

// MockSpecificEventMockRecorder is the mock recorder for MockSpecificEvent.
type MockSpecificEventMockRecorder struct {
	mock *MockSpecificEvent
}

// NewMockSpecificEvent creates a new mock instance.
func NewMockSpecificEvent(ctrl *gomock.Controller) *MockSpecificEvent {
	mock := &MockSpecificEvent{ctrl: ctrl}
	mock.recorder = &MockSpecificEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecificEvent) EXPECT() *MockSpecificEventMockRecorder {
	return m.recorder
}

// AddHeader mocks base method.
func (m *MockSpecificEvent) AddHeader(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeader", key, value)
}

// AddHeader indicates an expected call of AddHeader.
func (mr *MockSpecificEventMockRecorder) AddHeader(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeader", reflect.TypeOf((*MockSpecificEvent)(nil).AddHeader), key, value)
}

// AddHeaders mocks base method.
func (m *MockSpecificEvent) AddHeaders(headers map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeaders", headers)
}

// AddHeaders indicates an expected call of AddHeaders.
func (mr *MockSpecificEventMockRecorder) AddHeaders(headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeaders", reflect.TypeOf((*MockSpecificEvent)(nil).AddHeaders), headers)
}

// AggregateID mocks base method.
func (m *MockSpecificEvent) AggregateID() kernel.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateID")
	ret0, _ := ret[0].(kernel.ID)
	return ret0
}

// AggregateID indicates an expected call of AggregateID.
func (mr *MockSpecificEventMockRecorder) AggregateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateID", reflect.TypeOf((*MockSpecificEvent)(nil).AggregateID))
}

// Headers mocks base method.
func (m *MockSpecificEvent) Headers() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headers")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Headers indicates an expected call of Headers.
func (mr *MockSpecificEventMockRecorder) Headers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headers", reflect.TypeOf((*MockSpecificEvent)(nil).Headers))
}

// ID mocks base method.
func (m *MockSpecificEvent) ID() event.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(event.ID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockSpecificEventMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockSpecificEvent)(nil).ID))
}

// Marshal mocks base method.
func (m *MockSpecificEvent) Marshal() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockSpecificEventMockRecorder) Marshal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockSpecificEvent)(nil).Marshal))
}

// OccurredAt mocks base method.
func (m *MockSpecificEvent) OccurredAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OccurredAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// OccurredAt indicates an expected call of OccurredAt.
func (mr *MockSpecificEventMockRecorder) OccurredAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OccurredAt", reflect.TypeOf((*MockSpecificEvent)(nil).OccurredAt))
}

// Payload mocks base method.
func (m *MockSpecificEvent) Payload() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Payload indicates an expected call of Payload.
func (mr *MockSpecificEventMockRecorder) Payload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockSpecificEvent)(nil).Payload))
}

// Topic mocks base method.
func (m *MockSpecificEvent) Topic() event.Topic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Topic")
	ret0, _ := ret[0].(event.Topic)
	return ret0
}

// Topic indicates an expected call of Topic.
func (mr *MockSpecificEventMockRecorder) Topic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Topic", reflect.TypeOf((*MockSpecificEvent)(nil).Topic))
}

// Unmarshal mocks base method.
func (m *MockSpecificEvent) Unmarshal(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockSpecificEventMockRecorder) Unmarshal(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockSpecificEvent)(nil).Unmarshal), data)
}
