// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=./mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "gochat/internal/authorization/domain"
	kernel "gochat/internal/shared/kernel"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncryptor is a mock of Encryptor interface.
type MockEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorMockRecorder
	isgomock struct{}
}

// MockEncryptorMockRecorder is the mock recorder for MockEncryptor.
type MockEncryptorMockRecorder struct {
	mock *MockEncryptor
}

// NewMockEncryptor creates a new mock instance.
func NewMockEncryptor(ctrl *gomock.Controller) *MockEncryptor {
	mock := &MockEncryptor{ctrl: ctrl}
	mock.recorder = &MockEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptor) EXPECT() *MockEncryptorMockRecorder {
	return m.recorder
}

// Encrypt mocks base method.
func (m *MockEncryptor) Encrypt(origin string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", origin)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptorMockRecorder) Encrypt(origin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptor)(nil).Encrypt), origin)
}

// MockComparator is a mock of Comparator interface.
type MockComparator struct {
	ctrl     *gomock.Controller
	recorder *MockComparatorMockRecorder
	isgomock struct{}
}

// MockComparatorMockRecorder is the mock recorder for MockComparator.
type MockComparatorMockRecorder struct {
	mock *MockComparator
}

// NewMockComparator creates a new mock instance.
func NewMockComparator(ctrl *gomock.Controller) *MockComparator {
	mock := &MockComparator{ctrl: ctrl}
	mock.recorder = &MockComparatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComparator) EXPECT() *MockComparatorMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockComparator) Compare(encrypted, origin string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", encrypted, origin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockComparatorMockRecorder) Compare(encrypted, origin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockComparator)(nil).Compare), encrypted, origin)
}

// MockAccessTokenGenerator is a mock of AccessTokenGenerator interface.
type MockAccessTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockAccessTokenGeneratorMockRecorder is the mock recorder for MockAccessTokenGenerator.
type MockAccessTokenGeneratorMockRecorder struct {
	mock *MockAccessTokenGenerator
}

// NewMockAccessTokenGenerator creates a new mock instance.
func NewMockAccessTokenGenerator(ctrl *gomock.Controller) *MockAccessTokenGenerator {
	mock := &MockAccessTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockAccessTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenGenerator) EXPECT() *MockAccessTokenGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAccessTokenGenerator) Generate(userID kernel.UserID) (domain.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", userID)
	ret0, _ := ret[0].(domain.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAccessTokenGeneratorMockRecorder) Generate(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAccessTokenGenerator)(nil).Generate), userID)
}

// MockRefreshTokenGenerator is a mock of RefreshTokenGenerator interface.
type MockRefreshTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockRefreshTokenGeneratorMockRecorder is the mock recorder for MockRefreshTokenGenerator.
type MockRefreshTokenGeneratorMockRecorder struct {
	mock *MockRefreshTokenGenerator
}

// NewMockRefreshTokenGenerator creates a new mock instance.
func NewMockRefreshTokenGenerator(ctrl *gomock.Controller) *MockRefreshTokenGenerator {
	mock := &MockRefreshTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenGenerator) EXPECT() *MockRefreshTokenGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockRefreshTokenGenerator) Generate() (domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockRefreshTokenGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRefreshTokenGenerator)(nil).Generate))
}

// MockUserNumberGenerator is a mock of UserNumberGenerator interface.
type MockUserNumberGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockUserNumberGeneratorMockRecorder
	isgomock struct{}
}

// MockUserNumberGeneratorMockRecorder is the mock recorder for MockUserNumberGenerator.
type MockUserNumberGeneratorMockRecorder struct {
	mock *MockUserNumberGenerator
}

// NewMockUserNumberGenerator creates a new mock instance.
func NewMockUserNumberGenerator(ctrl *gomock.Controller) *MockUserNumberGenerator {
	mock := &MockUserNumberGenerator{ctrl: ctrl}
	mock.recorder = &MockUserNumberGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserNumberGenerator) EXPECT() *MockUserNumberGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockUserNumberGenerator) Generate() kernel.UserNumber {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(kernel.UserNumber)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockUserNumberGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUserNumberGenerator)(nil).Generate))
}

// MockUserIDGenerator is a mock of UserIDGenerator interface.
type MockUserIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockUserIDGeneratorMockRecorder
	isgomock struct{}
}

// MockUserIDGeneratorMockRecorder is the mock recorder for MockUserIDGenerator.
type MockUserIDGeneratorMockRecorder struct {
	mock *MockUserIDGenerator
}

// NewMockUserIDGenerator creates a new mock instance.
func NewMockUserIDGenerator(ctrl *gomock.Controller) *MockUserIDGenerator {
	mock := &MockUserIDGenerator{ctrl: ctrl}
	mock.recorder = &MockUserIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIDGenerator) EXPECT() *MockUserIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockUserIDGenerator) Generate() kernel.UserID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(kernel.UserID)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockUserIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUserIDGenerator)(nil).Generate))
}
