// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_token_repository.go
//
// Generated by this command:
//
//	mockgen -source=refresh_token_repository.go -destination=./mocks/mock_refresh_token_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "gochat/internal/authorization/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// FindByToken mocks base method.
func (m *MockRefreshTokenRepository) FindByToken(ctx context.Context, token domain.RefreshToken) (*domain.RefreshTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, token)
	ret0, _ := ret[0].(*domain.RefreshTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindByToken), ctx, token)
}

// Upsert mocks base method.
func (m *MockRefreshTokenRepository) Upsert(ctx context.Context, token *domain.RefreshTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRefreshTokenRepositoryMockRecorder) Upsert(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Upsert), ctx, token)
}

// MockRefreshTokenUpserter is a mock of RefreshTokenUpserter interface.
type MockRefreshTokenUpserter struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenUpserterMockRecorder
	isgomock struct{}
}

// MockRefreshTokenUpserterMockRecorder is the mock recorder for MockRefreshTokenUpserter.
type MockRefreshTokenUpserterMockRecorder struct {
	mock *MockRefreshTokenUpserter
}

// NewMockRefreshTokenUpserter creates a new mock instance.
func NewMockRefreshTokenUpserter(ctrl *gomock.Controller) *MockRefreshTokenUpserter {
	mock := &MockRefreshTokenUpserter{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenUpserterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenUpserter) EXPECT() *MockRefreshTokenUpserterMockRecorder {
	return m.recorder
}

// Upsert mocks base method.
func (m *MockRefreshTokenUpserter) Upsert(ctx context.Context, token *domain.RefreshTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRefreshTokenUpserterMockRecorder) Upsert(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRefreshTokenUpserter)(nil).Upsert), ctx, token)
}

// MockRefreshTokenFinder is a mock of RefreshTokenFinder interface.
type MockRefreshTokenFinder struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenFinderMockRecorder
	isgomock struct{}
}

// MockRefreshTokenFinderMockRecorder is the mock recorder for MockRefreshTokenFinder.
type MockRefreshTokenFinderMockRecorder struct {
	mock *MockRefreshTokenFinder
}

// NewMockRefreshTokenFinder creates a new mock instance.
func NewMockRefreshTokenFinder(ctrl *gomock.Controller) *MockRefreshTokenFinder {
	mock := &MockRefreshTokenFinder{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenFinder) EXPECT() *MockRefreshTokenFinderMockRecorder {
	return m.recorder
}

// FindByToken mocks base method.
func (m *MockRefreshTokenFinder) FindByToken(ctx context.Context, token domain.RefreshToken) (*domain.RefreshTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, token)
	ret0, _ := ret[0].(*domain.RefreshTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockRefreshTokenFinderMockRecorder) FindByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockRefreshTokenFinder)(nil).FindByToken), ctx, token)
}
